Repository metabrainz/musicbrainz-server, pull requests merged in 2019-11, with the labels that each got.

#1247 MBS-10448: Add Dynamic Range DB to otherdbs whitelist
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/DynamicRangeDB.pm
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#1227 MBS-10394 and MBS-10395 Convert alias edit details to React
  lib/MusicBrainz/Server/Edit.pm
  lib/MusicBrainz/Server/Edit/Alias/Add.pm
  lib/MusicBrainz/Server/Edit/Alias/Delete.pm
  lib/MusicBrainz/Server/Edit/Alias/Edit.pm
  root/edit/details/AddRemoveAlias.js
  root/edit/details/EditAlias.js
  root/edit/details/add_remove_alias.tt
  root/edit/details/edit_alias.tt
  root/server/components.js
  root/types.js
  t/lib/t/MusicBrainz/Server/Controller/Artist/DeleteAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/DeleteAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/DeleteAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Series/DeleteAlias.pm
Labels: React

#1197 MBS-3839: Allow removing from queue during merge
  lib/MusicBrainz/Server/Controller/Artist.pm
  root/area/merge.tt
  root/artist/ArtistMerge.js
  root/components/RemoveFromMergeTableCell.js
  root/components/RemoveFromMergeTableHeader.js
  root/components/common-macros.tt
  root/components/list/ArtistList.js
  root/components/list/RecordingList.js
  root/event/merge.tt
  root/instrument/merge.tt
  root/label/merge.tt
  root/layout/components/MergeHelper.js
  root/place/merge.tt
  root/recording/RecordingMerge.js
  root/release/merge.tt
  root/release_group/merge.tt
  root/series/merge.tt
  root/static/scripts/common/components/ArtistListEntry.js
  root/static/scripts/common/utility/renderMergeCheckboxElement.js
  root/types.js
  root/work/merge.tt
Labels: QoL

#1209 MBS-10361: Move edit note help for better tabbing
  root/edit/notes.tt
  root/static/styles/common.less
  root/static/styles/edit.less
  root/static/styles/forms.less
  root/static/styles/help.less
Labels: QoL

#1243 MBS-10403 / MBS-10440: Removal page improvements
  lib/MusicBrainz/Server/Controller/Series.pm
  root/area/delete.tt
  root/components/forms.tt
  root/instrument/delete.tt
  root/label/delete.tt
  root/recording/delete.tt
  root/release/delete.tt
  root/series/delete.tt
  t/lib/t/MusicBrainz/Server/Controller/Series/Delete.pm
Labels: Bug, QoL

#1089 MBS-10206: Convert user profile to React
  lib/MusicBrainz/Server/Controller/User.pm
  lib/MusicBrainz/Server/Entity/Editor.pm
  lib/MusicBrainz/Server/Entity/EditorLanguage.pm
  root/server/components.js
  root/static/scripts/account/components/EditProfileForm.js
  root/static/scripts/common/constants.js
  root/types.js
  root/user/UserProfile.js
  root/user/profile.tt
  root/utility/voting.js
  t/lib/t/MusicBrainz/Server/Controller/User/Edit.pm
Labels: React

#1173 MBS-10299: Add page with suggested edit searches
  lib/MusicBrainz/Server/Controller/Vote.pm
  root/layout/components/BottomMenu.js
  root/server/components.js
  root/vote/VotingIndex.js
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
Labels: New feature

#1259 MBS-10465: Beta: Handle legacy time zones in formatUserDate
  root/utility/formatUserDate.js
Labels: Bug, Regression/Beta

#1263 MBS-10467: whitelist new_edit_notes_mtime stash key
  lib/MusicBrainz/Server.pm
Labels: Regression/Beta

#1265 MBS-10473: Make terser-webpack-plugin a full dependency
  package.json
Labels: Bug

#1261 MBS-10466: Wish a happy birthday in user timezone
  root/layout/index.js
Labels: QoL

#1257 MBS-9922: Convert the series index page to React
  lib/MusicBrainz/Server/Controller/Series.pm
  root/components/CleanupBanner.js
  root/layout/components/sidebar/SidebarType.js
  root/series/SeriesIndex.js
  root/series/index.tt
  root/server/components.js
  root/types.js
Labels: React

#1094 MBS-10204: Sum accepted/rejected edits in stats
  lib/MusicBrainz/Server/Controller/User/Edits.pm
  root/static/styles/layout.less
  root/user/UserProfile.js
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
Labels: QoL

#1162 MBS-4299: Show expanded AC in merge release warning
  root/components/common-macros.tt
  root/release/merge.tt
Labels: QoL

#1274 New eslint rules (eslint 6 recommended)
  .eslintrc.yaml
Labels: New feature, Refactoring

#1140 MBS-7097: Avoid listing releases multiple times
  lib/MusicBrainz/Server/Report/ReleasesWithDownloadRelationships.pm
Labels: QoL

#1262 MBS-10471: Add option to view edits by date closed
  lib/MusicBrainz/Server/EditSearch/Query.pm
  root/edit/search_macros.tt
  root/static/styles/layout.less
Labels: New feature

#1062 MBS-9491: Use DB genres in more places
  entities.json
  lib/MusicBrainz/Server.pm
  lib/MusicBrainz/Server/Controller/Role/Tag.pm
  lib/MusicBrainz/Server/Controller/Tag.pm
  lib/MusicBrainz/Server/Controller/User.pm
  lib/MusicBrainz/Server/Controller/WS/js.pm
  lib/MusicBrainz/Server/Controller/WS/js/Genre.pm
  lib/MusicBrainz/Server/ControllerBase/WS/2.pm
  lib/MusicBrainz/Server/Data/EntityTag.pm
  lib/MusicBrainz/Server/Data/Search.pm
  lib/MusicBrainz/Server/Data/Tag.pm
  lib/MusicBrainz/Server/Entity/Tag.pm
  lib/MusicBrainz/Server/Entity/Types.pm
  lib/MusicBrainz/Server/WebService/JSONSerializer.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Genre.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Utils.pm
  root/entity/Tags.js
  root/layout/components/sidebar/SidebarTags.js
  root/search/components/TagResults.js
  root/static/scripts/common/components/TagEditor.js
  root/static/scripts/common/constants.js
  root/tag/EntityList.js
  root/tag/TagCloud.js
  root/tag/TagIndex.js
  root/tag/TagLayout.js
  root/types.js
  root/utility/sanitizedContext.js
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupDiscID.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupDiscID.pm
  t/sql/lori_cooke.sql
  t/sql/webservice.sql
Labels: New feature

#1160 MBS-4091: Avoid breaking lists while trimming annotations
  lib/MusicBrainz/Server/Form/Annotation.pm
Labels: Bug

#1214 MBS-4776: Require confirmation for VA track artist
  root/release/edit/tracklist.tt
  root/static/scripts/release-editor/fields.js
  root/static/styles/layout.less
Labels: QoL

#1281 MBS-10482: Block and skip changing Patreon posts
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug

#1284 MBS-10488: Fix profile subscription links
  root/user/UserProfile.js
Labels: Regression/Beta

#1286 MBS-10490: Fix broken "last 24h" edit search link
  root/user/UserProfile.js
Labels: Regression/Beta
