Repository metabrainz/musicbrainz-server, pull requests merged in 2019-12, with the labels that each got.

#1291 Improvements to script/dump-entities-sql.pl
  lib/MusicBrainz/Script/EntityDump.pm
  lib/MusicBrainz/Script/SampleDataDump.pm
  script/dump-entities-sql.pl
Labels: New feature

#1290 MBS-10495: Update Discourse API authentication method
  lib/MusicBrainz/Server/Controller/Discourse.pm
Labels: New feature

#1287 MBS-10491: Add "Add instrument" to search results
  root/search/components/InstrumentResults.js
Labels: QoL

#1293 REFACTOR: Convert var or let to const
  root/layout/components/Head.js
  root/server.js
  root/server/createServer.js
  root/static/scripts/common/MB/Control/Autocomplete.js
  root/static/scripts/common/components/ArtistCreditLink.js
  root/static/scripts/common/utility/getBooleanCookie.js
  root/static/scripts/common/utility/reactTextContent.js
  root/static/scripts/edit/components/ArtistCreditEditor.js
  root/static/scripts/edit/components/forms.js
  root/static/scripts/edit/utility/guessFeat.js
  root/static/scripts/relationship-editor/common/entity.js
  root/static/scripts/relationship-editor/common/viewModel.js
  root/static/scripts/release-editor/edits.js
  root/static/scripts/release-editor/init.js
  root/static/scripts/tests/react-macros.js
  root/static/scripts/tests/utility.js
  root/static/scripts/timeline.js
  root/static/scripts/voting.js
Labels: Refactoring

#1282 MBS-10350: Stop highlighting Google+ links
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/GooglePlus.pm
  root/static/images/favicons/googleplus-32.png
  root/static/scripts/common/constants.js
  root/static/styles/favicons.less
Labels: QoL

#1276 MBS-10468: Stop breaking Bandcamp merch links
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug

#1267 Adding flow/require-indexer-name to eslintrc
  .eslintrc.yaml
Labels: New feature, Refactoring

#1275 MBS-10479: Show RG types on recording page
  lib/MusicBrainz/Server/Controller/Recording.pm
  root/recording/RecordingIndex.js
Labels: QoL

#1285 MBS-10489: Make EnterEditNote text less redundant
  root/components/EnterEditNote.js
Labels: QoL

#1288 MBS-10422: Add ISRCs to release editor recording search
  root/static/scripts/release-editor/utils.js
Labels: Bug

#1148 Fix release merge issues MBS-10188 and MBS-10279
  lib/MusicBrainz/Server/Controller/Release.pm
  lib/MusicBrainz/Server/Controller/Role/Merge.pm
  lib/MusicBrainz/Server/Data/Medium.pm
  lib/MusicBrainz/Server/Data/Release.pm
  lib/MusicBrainz/Server/Data/Track.pm
  lib/MusicBrainz/Server/Data/Utils.pm
  lib/MusicBrainz/Server/Edit/Release/Merge.pm
  lib/MusicBrainz/Server/Edit/Types.pm
  lib/MusicBrainz/Server/Edit/Utils.pm
  lib/MusicBrainz/Server/Entity/EditNote.pm
  root/components/common-macros.tt
  root/edit/details/merge_releases.tt
  t/lib/t/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/OAuth2.pm
  t/lib/t/MusicBrainz/Server/Data/CDTOC.pm
  t/lib/t/MusicBrainz/Server/Data/Language.pm
  t/lib/t/MusicBrainz/Server/Data/Medium.pm
  t/lib/t/MusicBrainz/Server/Data/Rating.pm
  t/lib/t/MusicBrainz/Server/Data/Release.pm
  t/lib/t/MusicBrainz/Server/Data/Statistics.pm
  t/lib/t/MusicBrainz/Server/Data/Tag.pm
  t/selenium.js
  t/selenium/MBS-10188.html
  t/sql/autoeditor_election.sql
  t/sql/edit_note.sql
  t/sql/editor.sql
  t/sql/initial.sql
  t/sql/mbs-10188.sql
  t/sql/medium-cdtoc.sql
  t/sql/oauth.sql
  t/sql/tag_raw.sql
Labels: Bug

#1292 Eliminate warnings caused by eslint rule react/jsx-handler-names
  root/static/scripts/common/components/TagEditor.js
  root/static/scripts/edit/check-duplicates.js
  root/static/scripts/edit/components/ArtistCreditEditor.js
  root/static/scripts/edit/components/ArtistCreditNameEditor.js
  root/static/scripts/edit/components/PossibleDuplicates.js
  root/static/scripts/edit/components/RemoveButton.js
  root/static/scripts/edit/externalLinks.js
  root/static/scripts/tests/autocomplete2.js
Labels: Refactoring

#1147 MBS-10255: Explanations for "copy all" checkboxes
  root/release/edit/recordings.tt
Labels: QoL

#1134 MBS-10248: Show relationship types in instrument lists
  lib/MusicBrainz/Server/Controller/Instrument.pm
  lib/MusicBrainz/Server/Data/Recording.pm
  lib/MusicBrainz/Server/Data/Release.pm
  root/components/InstrumentRelTypes.js
  root/components/list/RecordingList.js
  root/components/list/ReleaseList.js
  root/instrument/recordings.tt
  root/instrument/releases.tt
  root/types.js
Labels: QoL

#1300 Fix issues relating to eslint rule no-negated-condition
  root/layout/components/Head.js
  root/layout/components/sidebar/ReleaseSidebar.js
  root/static/scripts/edit/ExampleRelationships.js
  root/static/scripts/edit/MB/CoverArt.js
  root/static/scripts/guess-case/MB/GuessCase/Handler/Base.js
  root/static/scripts/guess-case/MB/GuessCase/Output.js
Labels: GCI, Refactoring

#1109 MBS-10228 / MBS-10243 / MBS-10244: Various fixes for no-media releases
  lib/MusicBrainz/Server/Edit/Release/Merge.pm
  root/components/list/ReleaseList.js
  root/edit/details/merge_releases.tt
  root/release_group/ReleaseGroupIndex.js
  root/search/components/ReleaseResults.js
  root/static/scripts/release-editor/duplicates.js
Labels: Bug

#1289 MBS-10493: Better sizing for edit search selects
  root/edit/search_macros.tt
  root/static/styles/forms.less
Labels: QoL

#1246 MBS-10439: Convert user collections list to React
  flow-typed/npm/react-table_v7.x.x.js
  lib/MusicBrainz/Server/Controller/User.pm
  lib/MusicBrainz/Server/Entity/Collection.pm
  package.json
  root/components/Table.js
  root/server/components.js
  root/types.js
  root/user/UserCollections.js
  root/user/collections.tt
  root/utility/tableColumns.js
  t/lib/t/MusicBrainz/Server/Controller/User/Collections.pm
  t/sql/collection.sql
  yarn.lock
Labels: React

#1301 REFACTOR: Make line breaks inside parentheses more consistent
  root/components/PaginatedResults.js
  root/static/scripts/common/MB/Control/Autocomplete.js
  root/static/scripts/edit/ExampleRelationships.js
  root/static/scripts/edit/MB/CoverArt.js
  root/static/scripts/edit/components/PossibleDuplicates.js
  root/static/scripts/edit/forms.js
  root/static/scripts/release-editor/recordingAssociation.js
  root/static/scripts/release-editor/trackParser.js
  root/static/scripts/timeline.js
Labels: GCI

#1308 MBS-10512: Do not show [missing media] for deleted/merged releases
  root/edit/details/merge_releases.tt
Labels: Regression/Beta

#1320 MBS-10510 (regression): Fix ISE merging releases with different recording artists
  lib/MusicBrainz/Server/Controller/Release.pm
  t/lib/t/MusicBrainz/Server/Data/ReleasePackaging.pm
  t/selenium.js
  t/selenium/MBS-10510.html
  t/sql/initial.sql
  t/sql/mbs-10510.sql
Labels: Regression/Beta

#1306 Delete unused rev-manifest.js
  root/static/rev-manifest.js
Labels: Refactoring

#1305 MBS-10365: Convert AreaList to React Table
  root/components/list/AreaList.js
  root/static/scripts/common/components/DescriptiveLink.js
  root/user/UserCollections.js
  root/utility/tableColumns.js
Labels: Refactoring

#1323 Add eslint-plugin-react-hooks
  .eslintrc.yaml
  package.json
  root/static/scripts/common/components/Autocomplete2.js
  root/static/scripts/common/components/FingerprintTable.js
  root/static/scripts/common/hooks/useOutsideClickEffect.js
  script/check_eslint_rule
  yarn.lock
Labels: Refactoring

#1311 Fix JS on MusicBrainz to have newlines after each call in a method chain where needed
  root/static/scripts/common/MB/Control/Autocomplete.js
  root/static/scripts/common/MB/Control/EditList.js
  root/static/scripts/common/artworkViewer.js
  root/static/scripts/common/coverart.js
  root/static/scripts/common/dialogs.js
  root/static/scripts/common/entity.js
  root/static/scripts/edit/MB/CoverArt.js
  root/static/scripts/edit/MB/TextList.js
  root/static/scripts/edit/MB/edit.js
  root/static/scripts/edit/MB/reltypeslist.js
  root/static/scripts/edit/components/ArtistCreditEditor.js
  root/static/scripts/edit/forms.js
  root/static/scripts/guess-case/MB/Control/GuessCase.js
  root/static/scripts/relationship-editor/common/dialog.js
  root/static/scripts/relationship-editor/common/entity.js
  root/static/scripts/relationship-editor/common/viewModel.js
  root/static/scripts/relationship-editor/generic.js
  root/static/scripts/relationship-editor/release.js
  root/static/scripts/release-editor/bindingHandlers.js
  root/static/scripts/release-editor/duplicates.js
  root/static/scripts/release-editor/edits.js
  root/static/scripts/release-editor/recordingAssociation.js
  root/static/scripts/release-editor/trackParser.js
  root/static/scripts/tests/relationship-editor.js
  root/static/scripts/tests/release-editor/dialogs.js
  root/static/scripts/tests/release-editor/trackParser.js
  root/static/scripts/timeline.js
Labels: GCI, Refactoring

#1329 MBS-10526: Only show private collab collections to collaborators
  lib/MusicBrainz/Server/Controller/User.pm
  lib/MusicBrainz/Server/Data/Collection.pm
Labels: Bug

#1258 Make entity types read only + few Eslint fixes
  root/layout/components/sidebar/SidebarBeginDate.js
  root/layout/components/sidebar/SidebarIpis.js
  root/layout/components/sidebar/SidebarIsnis.js
  root/static/scripts/common/utility/formatDatePeriod.js
  root/static/scripts/common/utility/formatEndDate.js
  root/types.js
  root/utility/age.js
Labels: Refactoring

#1322 Fixed files so that snake_case variables are camelCase, going along with the ESLint guidelines.
  root/area/edit_form.tt
  root/entity/alias/edit_form.tt
  root/event/edit_form.tt
  root/instrument/edit_form.tt
  root/label/edit_form.tt
  root/recording/edit_form.tt
  root/release_group/edit_form.tt
  root/static/scripts/common/MB/Control/Autocomplete.js
  root/static/scripts/common/coverart.js
  root/static/scripts/edit/ExampleRelationships.js
  root/static/scripts/edit/MB/Control/ArtistEdit.js
  root/static/scripts/edit/MB/CoverArt.js
  root/static/scripts/edit/MB/TextList.js
  root/static/scripts/edit/MB/edit.js
  root/static/scripts/guess-case/MB/Control/GuessCase.js
  root/static/scripts/place.js
  root/static/scripts/relationship-editor/common/fields.js
  root/static/scripts/relationship-editor/release.js
  root/static/scripts/release-editor/fields.js
  root/static/scripts/release-editor/init.js
  root/static/scripts/release-editor/utils.js
  root/static/scripts/series.js
  root/static/scripts/tests/CoverArt.js
  root/static/scripts/tests/edit.js
  root/static/scripts/tests/entity.js
  root/static/scripts/timeline.js
  root/static/scripts/work.js
Labels: GCI, Refactoring

#1168 MBS-10316: Add "Artists" tab for instruments
  entities.json
  lib/MusicBrainz/Server/Controller/Instrument.pm
  lib/MusicBrainz/Server/Data/Artist.pm
  lib/MusicBrainz/Server/Data/Recording.pm
  lib/MusicBrainz/Server/Data/Release.pm
  root/components/InstrumentRelTypes.js
  root/components/list/ArtistList.js
  root/instrument/artists.tt
  root/static/scripts/common/components/ArtistListEntry.js
  root/types.js
Labels: New feature

#1326 MBS-10365: Convert entity lists to react-table (I)
  flow-typed/npm/react-table_v7.x.x.js
  lib/MusicBrainz/Server/Data/Label.pm
  root/components/list/AreaList.js
  root/components/list/InstrumentList.js
  root/components/list/LabelList.js
  root/components/list/PlaceList.js
  root/components/list/SeriesList.js
  root/components/list/WorkList.js
  root/static/styles/layout.less
  root/utility/tableColumns.js
Labels: Refactoring

#1315 Add names to all Flow object indexer types
  root/components/Paginator.js
  root/components/Relationships.js
  root/edit/details/AddAnnotation.js
  root/edit/details/AddRemoveAlias.js
  root/edit/details/EditAlias.js
  root/instrument/List.js
  root/static/scripts/common/MB.js
  root/static/scripts/common/components/TagEditor.js
  root/static/scripts/common/i18n/expand2.js
  root/static/scripts/common/i18n/expand2html.js
  root/static/scripts/common/i18n/expand2react.js
  root/static/scripts/common/i18n/expand2text.js
  root/static/scripts/common/utility/storage.js
  root/static/scripts/edit/utility/createField.js
  root/static/scripts/edit/utility/linkPhrase.js
  root/static/scripts/work.js
  root/statistics/CoverArt.js
  root/statistics/Edits.js
  root/statistics/Formats.js
  root/statistics/Index.js
  root/statistics/Relationships.js
  root/tag/TagIndex.js
  root/types.js
  root/utility/generateRelationshipAppearancesList.js
  root/utility/groupRelationships.js
  root/vars.js
Labels: GCI, Refactoring

#1297 Fixed: E-mail verification is sometimes called confirmation
  lib/MusicBrainz/Script/SubscriptionEmails.pm
  lib/MusicBrainz/Server/Controller/Account.pm
  lib/MusicBrainz/Server/Controller/User.pm
  lib/MusicBrainz/Server/Controller/WS/2/Recording.pm
  lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
  root/account/sso/DiscourseUnconfirmedEmailAddress.js
  root/user/UserProfile.js
  t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
Labels: GCI

#1331 MBS-9919: Convert the place map tab to React
  lib/MusicBrainz/Server/Controller/Place.pm
  root/place/PlaceMap.js
  root/place/map.tt
  root/server/components.js
Labels: React

#1332 MBS-10455: Block more smart URLs (again)
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#1333 MBS-10292: Normalize and validate QIM URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL
