Repository metabrainz/musicbrainz-server, pull requests merged in 2019-10, with the labels that each got.

#1206 MBS-10353: Enable ratings for release browse
  lib/MusicBrainz/Server/Controller/WS/2/Release.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupReleaseGroup.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupReleaseGroup.pm
  t/sql/webservice.sql
Labels: QoL

#1199 MBS-10346: Remove unneeded <p> inside <td>
  root/user/collections.tt
Labels: QoL

#1200 MBS-10347: Make action columns take only needed space
  root/components/Aliases/AliasTable.js
  root/components/Aliases/AliasTableRow.js
  root/components/Aliases/ArtistCreditList.js
  root/static/styles/layout.less
  root/user/collections.tt
Labels: QoL

#1198 MBS-10345: Redirect away from /merge if not ready to merge
  lib/MusicBrainz/Server/Controller/Role/Merge.pm
Labels: QoL

#1203 MBS-10349: New, more clear headers for rel stats
  root/statistics/Relationships.js
Labels: QoL

#1201 More WS improvements
  INSTALL.md
  cpanfile
  docker/templates/Dockerfile.sitemaps.m4
  docker/templates/macros.m4
  lib/DBDefs/Default.pm
  lib/MusicBrainz/Script/JSONDump/Constants.pm
  lib/MusicBrainz/Server.pm
  lib/MusicBrainz/Server/Controller/Role/ETags.pm
  lib/MusicBrainz/Server/Controller/WS/2/DiscID.pm
  lib/MusicBrainz/Server/Controller/WS/2/Rating.pm
  lib/MusicBrainz/Server/Controller/WS/2/Release.pm
  lib/MusicBrainz/Server/Controller/WS/2/Tag.pm
  lib/MusicBrainz/Server/ControllerBase/WS/2.pm
  lib/MusicBrainz/Server/ControllerBase/WS/js.pm
  lib/MusicBrainz/Server/Data/CoverArt.pm
  lib/MusicBrainz/Server/Data/DurationLookup.pm
  lib/MusicBrainz/Server/Data/Medium.pm
  lib/MusicBrainz/Server/Data/Relationship.pm
  lib/MusicBrainz/Server/Data/Release.pm
  lib/MusicBrainz/Server/Data/Role/EntityCache.pm
  lib/MusicBrainz/Server/Data/Search.pm
  lib/MusicBrainz/Server/Data/Utils.pm
  lib/MusicBrainz/Server/Edit/Historic/Relationship.pm
  lib/MusicBrainz/Server/Edit/Relationship/Create.pm
  lib/MusicBrainz/Server/Edit/Relationship/Delete.pm
  lib/MusicBrainz/Server/Edit/Relationship/Edit.pm
  lib/MusicBrainz/Server/Edit/Relationship/EditLinkType.pm
  lib/MusicBrainz/Server/Edit/Relationship/Reorder.pm
  lib/MusicBrainz/Server/Entity/ArtistCredit.pm
  lib/MusicBrainz/Server/Entity/Relationship.pm
  lib/MusicBrainz/Server/Entity/Release.pm
  lib/MusicBrainz/Server/View/Base.pm
  lib/MusicBrainz/Server/View/WS.pm
  lib/MusicBrainz/Server/WebService/JSONSerializer.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Utils.pm
  lib/MusicBrainz/Server/WebService/WebServiceInc.pm
  lib/MusicBrainz/Server/WebService/WebServiceStash.pm
  lib/MusicBrainz/Server/WebService/XMLSerializer.pm
  lib/MusicBrainz/XML.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseArtists.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseRecordings.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseWork.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupArtist.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupDiscID.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupLabel.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRecording.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupArtist.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupDiscID.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupLabel.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupNonCore.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRecording.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelationship.pm
  t/lib/t/MusicBrainz/Server/Data/CoverArt.pm
  t/lib/t/MusicBrainz/Server/Data/DurationLookup.pm
  t/lib/t/MusicBrainz/Server/Data/Medium.pm
  t/lib/t/MusicBrainz/Server/Data/Release.pm
  t/lib/t/MusicBrainz/Server/Entity/Medium.pm
Labels: Bug, Refactoring

#1182 MBS-10240: Allow seeding "release has no barcode"
  root/static/scripts/release-editor/seeding.js
  t/selenium/release-editor/Seeding.html
  t/selenium/release-editor/seeds/no_barcode.html
Labels: New feature

#1106 MBS-10229: Block more shortened/“smart” URLs
  root/static/scripts/edit/externalLinks.js
  t/selenium/External_Links_Editor.html
Labels: New feature

#1213 MBS-10369: Count descendant countries in stats
  lib/MusicBrainz/Server/Data/Statistics.pm
Labels: Bug

#1139 MBS-8967: Events aren't dupes if all have comment
  lib/MusicBrainz/Server/Report/DuplicateEvents.pm
Labels: QoL

#1215 MBS-9915: Convert the artist public pages to React
  lib/MusicBrainz/Server/Controller/Ajax.pm
  lib/MusicBrainz/Server/Controller/Artist.pm
  lib/MusicBrainz/Server/FilterUtils.pm
  lib/MusicBrainz/Server/Form/Filter/Generic.pm
  lib/MusicBrainz/Server/Form/Filter/ReleaseGroup.pm
  root/artist/ArtistIndex.js
  root/artist/ArtistRecordings.js
  root/artist/ArtistReleases.js
  root/artist/index.tt
  root/artist/recordings.tt
  root/artist/releases.tt
  root/components/SelectField.js
  root/components/common-macros.tt
  root/components/filter-form.tt
  root/components/filter.tt
  root/server/components.js
  root/static/scripts/common.js
  root/static/scripts/common/MB/Control/Filter.js
  root/static/scripts/common/components/Filter.js
  root/static/scripts/common/components/FilterForm.js
  root/static/scripts/common/components/FilterIcon.js
  root/static/styles/forms.less
Labels: React

#1210 MBS-10363: Go back to referer on merge cancel
  lib/MusicBrainz/Server/Controller/Role/Merge.pm
Labels: Bug

#1220 MBS-9920: Convert the recording fingerprints page to React
  lib/MusicBrainz/Server/Controller/Recording.pm
  root/recording/RecordingFingerprints.js
  root/recording/fingerprints.tt
  root/server/components.js
  root/static/scripts/common.js
  root/static/scripts/common/components/FingerprintTable.js
  root/static/styles/layout.less
Labels: React

#1161 MBS-9111: Stricter validation for empty edit notes
  lib/MusicBrainz/Server/Form/Role/EditNote.pm
  lib/MusicBrainz/Server/Validation.pm
  root/components/EnterEditNote.js
  root/components/forms.tt
Labels: Bug

#1193 MBS-8566: Reuse release AC when importing CD stubs
  root/static/scripts/release-editor/dialogs.js
Labels: QoL

#1170 MBS-4486: Remove parentheses around disambiguation
  lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
  lib/MusicBrainz/Server/Data/Utils.pm
  lib/MusicBrainz/Server/Form/Field/Comment.pm
  root/release/edit/information.tt
Labels: QoL

#1124 MBS-10263: Don't insert annotation if edit is open
  lib/MusicBrainz/Server/Edit/Annotation/Edit.pm
  root/edit/details/AddAnnotation.js
  root/edit/details/add_event_annotation.tt
  t/lib/t/MusicBrainz/Server/Edit/Artist/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Edit/Label/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Edit/Recording/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Edit/Release/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Edit/ReleaseGroup/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Edit/Work/AddAnnotation.pm
Labels: Bug

#1152 Eslint for edit_search.js
  root/static/scripts/common/MB/edit_search.js
Labels: Refactoring

#1175 MBS-4913: Indicate the number of CAA pieces on tab
  entities.json
  lib/MusicBrainz/Server.pm
  lib/MusicBrainz/Server/Controller/Release.pm
  lib/MusicBrainz/Server/Data/Artwork.pm
  root/components/EntityTabs.js
  root/types.js
Labels: QoL

#1219 MBS-5479: Add an "Edit Relationships" tab
  root/components/EntityTabs.js
  root/release/edit_relationships.tt
Labels: QoL

#1127 MBS-3112: Switch order of release editor buttons
  root/components/ConfirmLayout.js
  root/release/edit/layout.tt
Labels: QoL

#1185 MBS-4980: Use catnos to sort releases in RG page
  lib/MusicBrainz/Server/Data/Release.pm
Labels: QoL

#1207 MBS-10355: Display track artist on recording pages
  root/recording/RecordingIndex.js
Labels: QoL

#1212 MBS-10370: Add "direction: forward" to XML WS rels
  lib/MusicBrainz/Server/WebService/XMLSerializer.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupArtist.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRecording.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelationship.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm
Labels: QoL

#1117 MBS-2176: Add "Finish" button to go to last tab
  root/release/edit/layout.tt
  root/static/scripts/release-editor/actions.js
Labels: QoL

#1204 MBS-5083: Display recording artist on release view
  lib/MusicBrainz/Server/Data/Medium.pm
  root/components/medium.tt
  t/selenium/release-editor/The_Downward_Spiral.html
Labels: New feature

#1226 MBS-10414: beta: add back artist index paging
  .circleci/config.yml
  lib/MusicBrainz/Server/Controller/Artist.pm
  root/artist/ArtistIndex.js
Labels: Regression/Beta

#1228 Set source attribute in load_entities, if unset
  lib/MusicBrainz/Server/Data/Relationship.pm
Labels: Regression/Beta

#1232 MBS-10420: Remove /all from /edits/all links
  root/layout/components/TopMenu.js
Labels: QoL

#1230 MBS-10419: Beta: Unbreak historical attributes display in edits
  root/static/scripts/edit/utility/linkPhrase.js
Labels: Regression/Beta

#1239 MBS-10430: Add "actions" class to fingerprints
  root/static/scripts/common/components/FingerprintTable.js
Labels: Bug

#1208 MBS-10356: Replace <b> with <strong>
  lib/MusicBrainz/Server/Filters.pm
  root/instrument/edit_form.tt
  root/release/edit/information.tt
  root/static/scripts/area/places-map.js
  root/static/scripts/common/i18n/expand2.js
  root/static/scripts/common/i18n/expand2html.js
  root/static/scripts/common/i18n/expand2react.js
  root/static/scripts/tests/i18n/expand2.js
  root/taglookup/Nag.js
Labels: Refactoring

#1237 Eslint fixes for /account/applications
  root/account/applications/Edit.js
  root/account/applications/Register.js
  root/account/applications/Remove.js
  root/account/applications/RevokeAccess.js
  root/elections/Nominate.js
Labels: Refactoring

#1238 MBS-10428: Show artist aliases for recording ACs
  lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Recording.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Utils.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
  t/script/DumpJSON.t
Labels: Bug

#1233 MBS-9468: Missing check for remove rel edits in search
  lib/MusicBrainz/Server/EditSearch/Predicate/RelationshipType.pm
Labels: Bug

#1235 MBS-10408: Stop AC edits_pending overwriting artist one
  lib/MusicBrainz/Server/Data/ArtistCredit.pm
Labels: Bug

#1240 MBS-10432 / MBS-10433 / MBS-10437: Block adding removal edits for areas that shouldn't be removed
  lib/MusicBrainz/Server/Controller/Role/Delete.pm
  lib/MusicBrainz/Server/Data/Area.pm
  root/area/delete.tt
Labels: Bug

#1241 MBS-10431: Remove 'yourmusic' from 7digital URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#1222 Port the Autocomplete formatters to React
  .eslintrc.yaml
  root/components/Artwork.js
  root/components/CountryAbbr.js
  root/components/ReleaseCatnoList.js
  root/components/ReleaseCountries.js
  root/components/ReleaseLabelList.js
  root/components/common-macros.tt
  root/static/scripts/common/components/Autocomplete2.js
  root/static/scripts/common/components/Autocomplete2/formatters.js
  root/static/scripts/common/components/Autocomplete2/types.js
  root/static/scripts/common/i18n/commaList.js
  root/static/scripts/common/i18n/commaOnlyList.js
  root/static/scripts/tests/autocomplete2.html
  root/static/scripts/tests/autocomplete2.js
  root/types.js
Labels: React

#1236 MBS-10425: Allow rel credits for instruments
  lib/MusicBrainz/Server/Constants.pm
  root/static/scripts/common/constants.js
Labels: New feature

#1195 Add Albanian (sq) to tested languages
  docker/Dockerfile.tests
  docker/musicbrainz-tests/DBDefs.pm
  docker/templates/macros.m4
  po/attributes.sq.po
  po/countries.sq.po
  po/instrument_descriptions.sq.po
  po/instruments.sq.po
  po/languages.sq.po
  po/mb_server.sq.po
  po/relationships.sq.po
  po/scripts.sq.po
  po/statistics.sq.po
Labels: New feature

#1254 MBS-10371: Update the Songfacts logo
  root/static/images/favicons/songfacts-16.png
  root/static/images/favicons/songfacts-32.png
  root/static/styles/favicons.less
Labels: QoL

#1217 MBS-10382: Explain when to use the Update checkbox
  root/artist/ArtistMerge.js
  root/components/FormRowCheckbox.js
  root/static/styles/forms.less
  root/user/ReportUser.js
Labels: QoL
