Repository metabrainz/musicbrainz-server, pull requests merged in 2020-05, with the labels that each got.

#1463 MBS-10764: Convert historic Remove Label Alias edit to React
  lib/MusicBrainz/Server/Edit/Historic/RemoveLabelAlias.pm
  root/edit/details/historic/RemoveLabelAlias.js
  root/edit/details/historic/remove_label_alias.tt
  root/server/components.js
Labels: React

#1464 MBS-10765: Convert historic Add, Move and Remove DiscID edits to React
  entities.json
  lib/MusicBrainz/Server/Edit/Historic/AddDiscID.pm
  lib/MusicBrainz/Server/Edit/Historic/MoveDiscID.pm
  lib/MusicBrainz/Server/Edit/Historic/RemoveDiscID.pm
  lib/MusicBrainz/Server/Entity/CDTOC.pm
  root/components/common-macros.tt
  root/edit/details/historic/AddDiscId.js
  root/edit/details/historic/MoveDiscId.js
  root/edit/details/historic/RemoveDiscId.js
  root/edit/details/historic/add_disc_id.tt
  root/edit/details/historic/move_disc_id.tt
  root/edit/details/historic/remove_disc_id.tt
  root/server/components.js
  root/static/scripts/common/components/CDTocLink.js
  root/static/scripts/common/utility/entityHref.js
  root/types.js
Labels: React

#1469 MBS-10773: Convert historic Change Release Quality edit to React
  lib/MusicBrainz/Server/Edit/Historic/ChangeReleaseQuality.pm
  root/components/common-macros.tt
  root/edit/details/historic/ChangeReleaseQuality.js
  root/edit/details/historic/change_release_quality.tt
  root/server/components.js
Labels: React

#1471 MBS-10775: Convert historic Add/Remove rel edits to React
  lib/MusicBrainz/Server/Edit/Historic/AddLink.pm
  lib/MusicBrainz/Server/Edit/Historic/Relationship.pm
  lib/MusicBrainz/Server/Edit/Historic/RemoveLink.pm
  root/edit/details/historic/AddRelationship.js
  root/edit/details/historic/RemoveRelationship.js
  root/edit/details/historic/add_relationship.tt
  root/edit/details/historic/remove_relationship.tt
  root/server/components.js
  root/static/scripts/common/components/Relationship.js
Labels: React

#1491 MBS-10768: Fix crash in donation check for names with slashes
  lib/MusicBrainz/Server/Data/Editor.pm
Labels: Bug

#1492 MBS-10564: Display non-ASCII YouTube channel names too
  lib/MusicBrainz/Server/Entity/URL/YouTube.pm
Labels: Bug

#1490 MBS-10805: Add support for more Amazon domains
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/AmazonMusic.pm
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#1499 MBS-10811: Convert historic Edit Relationship edit to React
  lib/MusicBrainz/Server/Edit/Historic/EditLink.pm
  root/edit/details/historic/EditRelationship.js
  root/edit/details/historic/edit_relationship.tt
  root/server/components.js
  root/static/scripts/common/components/Relationship.js
Labels: React, Regression/Beta

#1495 MBS-10138: Fix guess case for titles finishing in "f"
  root/static/scripts/guess-case/MB/GuessCase/Handler/Base.js
  root/static/scripts/tests/GuessCase.js
Labels: Bug

#1480 MBS-10790: Convert historic MAC/SAC edits to React
  lib/MusicBrainz/Server/Edit/Historic/MACToSAC.pm
  lib/MusicBrainz/Server/Edit/Historic/SACToMAC.pm
  root/edit/components/HistoricReleaseList.js
  root/edit/details/historic/ChangeReleaseArtist.js
  root/edit/details/historic/convert_release_to_multiple_artists.tt
  root/edit/details/historic/mac_to_sac.tt
  root/server/components.js
Labels: React

#1481 MBS-10791: Convert historic Change RG edit to React
  lib/MusicBrainz/Server/Edit/Historic/ChangeReleaseGroup.pm
  root/edit/details/historic/ChangeReleaseGroup.js
  root/edit/details/historic/change_release_group.tt
  root/server/components.js
Labels: React

#1482 MBS-10792: Convert historic Change Artist Quality edit to React
  lib/MusicBrainz/Server/Edit/Historic/ChangeArtistQuality.pm
  root/edit/details/historic/ChangeArtistQuality.js
  root/edit/details/historic/change_artist_quality.tt
  root/server/components.js
Labels: React

#1505 MBS-10397: Convert Edit Event edit to React
  lib/MusicBrainz/Server/Edit/Event/Edit.pm
  root/edit/details/EditEvent.js
  root/edit/details/edit_event.tt
  root/server/components.js
Labels: React

#1516 Updated Facebook, Google Play, and Spotify icons.
  root/static/images/favicons/facebook-32.png
  root/static/images/favicons/googleplay-32.png
  root/static/images/favicons/spotify-16.png
  root/static/images/favicons/spotify-32.png
  root/static/styles/favicons.less
Labels: QoL

#1478 MBS-10785: Remove FreeDB Gateway from menu
  root/layout/components/BottomMenu.js
Labels: QoL

#1515 MBS-9516: Support custom validation errors in URLCleanup
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/edit/externalLinks.js
  root/static/scripts/relationship-editor/common/dialog.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#1483 MBS-10793: Convert historic Move Release edit to React
  lib/MusicBrainz/Server/Edit/Historic/MoveRelease.pm
  root/edit/details/historic/MoveRelease.js
  root/edit/details/historic/move_release.tt
  root/server/components.js
Labels: React

#1484 MBS-10799: Convert historic Move Release to RG edit to React
  lib/MusicBrainz/Server/Edit/Historic/MoveRelease.pm
  lib/MusicBrainz/Server/Edit/Historic/MoveReleaseToRG.pm
  root/edit/details/historic/MoveReleaseToReleaseGroup.js
  root/edit/details/historic/move_release_to_rg.tt
  root/server/components.js
Labels: React

#1502 MBS-10813: Update the Bandcamp logo
  root/static/images/favicons/bandcamp-16.png
  root/static/images/favicons/bandcamp-32.png
  root/static/styles/favicons.less
Labels: QoL

#1508 MBS-10822: Change tableColumns tables to use named parameters
  root/components/list/AreaList.js
  root/components/list/ArtistList.js
  root/components/list/EventList.js
  root/components/list/InstrumentList.js
  root/components/list/LabelList.js
  root/components/list/PlaceList.js
  root/components/list/RecordingList.js
  root/components/list/ReleaseGroupList.js
  root/components/list/ReleaseList.js
  root/components/list/SeriesList.js
  root/components/list/WorkList.js
  root/user/UserCollections.js
  root/utility/tableColumns.js
Labels: React, Refactoring

#1520 Bump react-table version to 7.1.0
  package.json
  root/components/list/AreaList.js
  root/components/list/ArtistList.js
  root/components/list/EventList.js
  root/components/list/InstrumentList.js
  root/components/list/LabelList.js
  root/components/list/PlaceList.js
  root/components/list/RecordingList.js
  root/components/list/ReleaseGroupList.js
  root/components/list/SeriesList.js
  root/components/list/WorkList.js
  root/utility/tableColumns.js
  yarn.lock
Labels: React

#1525 MBS-10840: Fix key names in English guess case
  root/static/scripts/guess-case/modes.js
  root/static/scripts/tests/GuessCase.js
Labels: New feature

#1524 MBS-10841: Add "Guess case" per medium
  root/release/edit/tracklist.tt
  root/static/scripts/release-editor/actions.js
Labels: QoL

#1523 MBS-10842: Remove report link from deleted editors
  root/user/ReportUser.js
  root/user/UserProfile.js
Labels: QoL

#1522 MBS-10839: Add merge button to recording list in artist overview
  root/artist/ArtistIndex.js
Labels: Bug

#1519 MBS-10834: Account flag to disable writing edit notes
  lib/MusicBrainz/Server/Constants.pm
  lib/MusicBrainz/Server/Controller/Admin.pm
  lib/MusicBrainz/Server/Data/Editor.pm
  lib/MusicBrainz/Server/Edit.pm
  lib/MusicBrainz/Server/Entity/Editor.pm
  lib/MusicBrainz/Server/Form/User/AdjustFlags.pm
  root/admin/edit_user.tt
  root/layout.tt
  root/layout/index.js
  root/types.js
Labels: New feature

#1528 Prevent two statement timeouts in reports
  lib/MusicBrainz/Server/Report/QueryReport.pm
  lib/MusicBrainz/Server/Report/RecordingTrackDifferentName.pm
  lib/MusicBrainz/Server/Report/RecordingsSameNameDifferentArtistsSameName.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/ReportsIndex.js
Labels: Bug, Regression/Beta

#1507 MBS-10817: Convert Edit Label edit to React
  lib/MusicBrainz/Server/Edit/Label/Edit.pm
  root/edit/details/EditLabel.js
  root/edit/details/edit_label.tt
  root/server/components.js
Labels: React

#1479 MBS-9963 / MBS-10789: Genius link improvements
  root/static/images/favicons/genius-16.png
  root/static/images/favicons/genius-32.png
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature

#1496 MBS-10732: Add collaborator validation to collection form
  lib/MusicBrainz/Server/Form/Collection.pm
  root/static/scripts/collection/components/CollectionEditForm.js
  root/static/styles/forms.less
Labels: Bug

#1533 MBS-10853: Include link to subbed users' open edits in sub email
  lib/MusicBrainz/Server/Email/Subscriptions.pm
Labels: QoL

#1510 MBS-10613: Only show git info on staging servers
  root/layout/components/Footer.js
Labels: Bug

#1532 MBS-10855: Show [removed] recording in historic EditTrack
  lib/MusicBrainz/Server/Edit/Historic/ChangeTrackArtist.pm
Labels: Bug

#1467 MBS-8412: Standardize pagination limits
  lib/MusicBrainz/Server/Controller/Edit.pm
  lib/MusicBrainz/Server/Controller/User.pm
  lib/MusicBrainz/Server/Controller/User/Edits.pm
Labels: QoL

#1535 MBS-10863: Fix Edit barcodes edit display for no barcode -> barcode
  root/edit/details/edit_barcodes.tt
Labels: Bug

#1534 MBS-10850: Update BadAmazonURLs report to avoid false positives
  lib/MusicBrainz/Server/Report/BadAmazonURLs.pm
  root/static/scripts/edit/URLCleanup.js
Labels: Bug

#1530 MBS-10849: Check for allowNew on AddReleaseGroup
  root/edit/details/AddReleaseGroup.js
Labels: Bug
