Repository metabrainz/musicbrainz-server, pull requests merged in 2020-08, with the labels that each got.

#1599 MBS-10968: Convert Add ISWCs edit to React
  lib/MusicBrainz/Server/Edit/Work/AddISWCs.pm
  root/edit/details/AddIswcs.js
  root/edit/details/add_iswcs.tt
  root/server/components.js
Labels: React

#1601 MBS-10970: Convert Add Release Label edit to React
  lib/MusicBrainz/Server/Edit/Release/AddReleaseLabel.pm
  root/edit/details/AddReleaseLabel.js
  root/edit/details/add_release_label.tt
  root/server/components.js
Labels: React

#1600 MBS-10969: Convert Add ISRCs edit to React
  lib/MusicBrainz/Server/Edit/Recording/AddISRCs.pm
  root/edit/details/AddIsrcs.js
  root/edit/details/add_isrcs.tt
  root/server/components.js
Labels: React

#1605 MBS-10975: Convert Remove ISWC edit to React
  lib/MusicBrainz/Server/Edit/Work/RemoveISWC.pm
  lib/MusicBrainz/Server/Entity/ISWC.pm
  root/edit/details/RemoveIswc.js
  root/edit/details/remove_iswc.tt
  root/server/components.js
Labels: React

#1603 MBS-10973: Convert Add Relationship Attribute edit to React
  lib/MusicBrainz/Server/Edit/Relationship/AddLinkAttribute.pm
  root/edit/details/AddRelationshipAttribute.js
  root/edit/details/add_relationship_attribute.tt
  root/server/components.js
Labels: React

#1604 MBS-10974: Convert Remove ISRC edit to React
  lib/MusicBrainz/Server/Edit/Recording/RemoveISRC.pm
  lib/MusicBrainz/Server/Entity/ISRC.pm
  root/edit/details/RemoveIsrc.js
  root/edit/details/remove_isrc.tt
  root/server/components.js
  root/static/scripts/common/linkedEntities.js
Labels: React

#1597 MBS-10193: Support Apple Music and Apple Books
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/AppleBooks.pm
  lib/MusicBrainz/Server/Entity/URL/AppleMusic.pm
  root/static/images/favicons/applebooks-32.png
  root/static/images/favicons/applemusic-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature

#1609 MBS-10983: Convert Remove Release Label edit to React
  lib/MusicBrainz/Server/Edit/Release/DeleteReleaseLabel.pm
  root/edit/details/RemoveReleaseLabel.js
  root/edit/details/remove_release_label.tt
  root/server/components.js
Labels: React

#1606 MBS-10980: Convert Remove Entity edit to React
  lib/MusicBrainz/Server/Edit/Generic/Delete.pm
  root/edit/details/RemoveEntity.js
  root/edit/details/remove_entity.tt
  root/server/components.js
  t/lib/t/MusicBrainz/Server/Controller/Edit/Show.pm
Labels: React

#1348 MBS-10562: Add phrases for future (sidebar) dates
  root/artist/utils.js
  root/layout/components/sidebar/ArtistSidebar.js
  root/layout/components/sidebar/PlaceSidebar.js
  root/utility/isFutureDate.js
Labels: QoL

#1614 MBS-10989: Update VocaDB cleanup to support new Es (series) format
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#1612 MBS-10949: Handle and display Migu Music URLs
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/MiguMusic.pm
  root/static/images/favicons/migumusic-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: QoL

#1590 MBS-10932: Allow linking Instagram videos to MusicBrainz recordings
  .circleci/config.yml
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#1572 MBS-7994 / MBS-10746: Add pregap icon and indicate pregap in edits
  lib/MusicBrainz/Server/Edit/Medium/Edit.pm
  root/components/common-macros.tt
  root/components/medium.tt
  root/edit/details/edit_medium.tt
  root/release/edit/tracklist.tt
  root/static/images/attribution.txt
  root/static/images/icons/pregap.png
  root/static/styles/layout.less
  t/selenium/release-editor/Seeding.html
Labels: Bug

#1615 MBS-10990: Limit edit displays to 50 edits per page
  lib/MusicBrainz/Server/Controller/Edit.pm
  lib/MusicBrainz/Server/Controller/Role/EditListing.pm
  lib/MusicBrainz/Server/Controller/User.pm
  lib/MusicBrainz/Server/Controller/User/Edits.pm
Labels: QoL

#1593 MBS-10948: Allow label baike.baidu.com links
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#1643 Drop autoselect for Apple Music
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Regression/Beta

#1648 A few eslint config updates
  .eslintrc.yaml
  script/check_eslint_rule
Labels: Refactoring

#1642 MBS-11028: Convert historic Edit Release Language edit to React
  lib/MusicBrainz/Server/Edit/Historic/EditReleaseLanguage.pm
  root/edit/components/HistoricReleaseList.js
  root/edit/details/historic/EditReleaseLanguage.js
  root/edit/details/historic/edit_release_language.tt
  root/server/components.js
Labels: React

#1641 MBS-11025: Update the SoundCloud logo
  root/static/images/favicons/soundcloud-16.png
Labels: QoL

#1650 Remove seemingly unused add_link.tt
  root/edit/details/add_link.tt
Labels: Refactoring

#1626 MBS-10998 / MBS-11012: Update the WhoSampled and Kickstarter logos
  root/static/images/favicons/kickstarter-32.png
  root/static/images/favicons/whosampled-16.png
  root/static/images/favicons/whosampled-32.png
  root/static/styles/favicons.less
Labels: QoL

#1598 MBS-10965: Convert Add Disc ID edit to React
  entities.json
  lib/MusicBrainz/Server/Edit/Medium/AddDiscID.pm
  lib/MusicBrainz/Server/Entity/MediumCDTOC.pm
  root/edit/details/AddDiscId.js
  root/edit/details/add_disc_id.tt
  root/server/components.js
  root/static/scripts/common/components/MediumLink.js
  root/static/tests/seed-love-bug.html
  root/types.js
Labels: React

#1610 MBS-10984 / MBS-10985: Convert Move / Remove Disc ID edit to React
  lib/MusicBrainz/Server/Edit/Medium/MoveDiscID.pm
  lib/MusicBrainz/Server/Edit/Medium/RemoveDiscID.pm
  root/edit/details/MoveDiscId.js
  root/edit/details/RemoveDiscId.js
  root/edit/details/move_disc_id.tt
  root/edit/details/remove_disc_id.tt
  root/server/components.js
Labels: React

#1625 MBS-10992: Disable ended URL links
  root/components/RelationshipTargetLinks.js
  root/components/StaticRelationshipsDisplay.js
  root/static/scripts/common/components/AreaWithContainmentLink.js
  root/static/scripts/common/components/DescriptiveLink.js
  root/static/scripts/common/components/EntityLink.js
  root/static/scripts/common/components/Relationship.js
  root/static/scripts/edit/components/edit/RelationshipDiff.js
Labels: New feature

#1637 MBS-11020: Convert historic Add Release Annotation edit to React
  lib/MusicBrainz/Server/Edit/Historic/AddReleaseAnnotation.pm
  root/edit/details/historic/AddReleaseAnnotation.js
  root/edit/details/historic/add_release_annotation.tt
  root/server/components.js
Labels: React

#1645 MBS-11030: Convert historic Edit Release Attributes edit to React
  lib/MusicBrainz/Server/Edit/Historic/EditReleaseAttrs.pm
  root/edit/details/historic/EditReleaseAttributes.js
  root/edit/details/historic/edit_release_attributes.tt
  root/server/components.js
Labels: React

#1623 MBS-9420: Load collection info for sidebar in sub split
  lib/MusicBrainz/Server/Controller/Artist.pm
Labels: Bug

#1622 MBS-11005: Add Kosovo flag
  root/static/images/attribution.txt
  root/static/images/flags/xk.png
  root/static/styles/flags.less
Labels: New feature

#1618 MBS-10994: Convert user/message.tt to React
  lib/MusicBrainz/Server/Controller/User.pm
  root/server/components.js
  root/user/UserMessage.js
  root/user/email_sent.tt
  root/user/message.tt
Labels: React

#1646 MBS-11031: Convert historic Edit Track edit to React
  lib/MusicBrainz/Server/Edit/Historic/ChangeTrackArtist.pm
  lib/MusicBrainz/Server/Edit/Historic/EditTrackNum.pm
  root/edit/details/historic/EditTrack.js
  root/edit/details/historic/edit_track.tt
  root/server/components.js
Labels: React

#1644 MBS-11029: Convert historic Edit Release Name edit to React
  lib/MusicBrainz/Server/Edit/Historic/EditReleaseName.pm
  root/edit/details/historic/EditReleaseName.js
  root/edit/details/historic/edit_release_name.tt
  root/server/components.js
Labels: React

#1639 MBS-11022: Convert historic Add Release edit to React
  lib/MusicBrainz/Server/Edit/Historic/AddRelease.pm
  root/edit/details/historic/AddRelease.js
  root/edit/details/historic/add_release.tt
  root/server/components.js
Labels: React

#1628 MBS-11004: Support laboiteauxparoles label links
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#1638 MBS-11021: Convert historic Add Track edits to React
  lib/MusicBrainz/Server/Edit/Historic/AddTrack.pm
  lib/MusicBrainz/Server/Edit/Historic/AddTrackKV.pm
  root/edit/details/historic/AddTrackKV.js
  root/edit/details/historic/AddTrackOld.js
  root/edit/details/historic/add_track_kv.tt
  root/edit/details/historic/add_track_old.tt
  root/server/components.js
Labels: React

#1444 MBS-10721: Improve track info in ArtistCreditBubble
  root/static/scripts/common/components/AreaWithContainmentLink.js
  root/static/scripts/common/components/DescriptiveLink.js
  root/static/scripts/common/components/EntityLink.js
  root/static/scripts/edit/components/ArtistCreditBubble.js
Labels: Bug

#1216 MBS-5588, MBS-5611, MBS-8016, MBS-8356, MBS-10376, MBS-10377: "Set cover art" improvements
  lib/MusicBrainz/Server/Controller/ReleaseGroup.pm
  root/components/common-macros.tt
  root/release_group/set_cover_art.tt
  root/static/images/attribution.txt
  root/static/images/no-cover-art.png
  root/static/styles/edit.less
Labels: Bug, QoL

#1575 MBS-10901: Fix ISE when historic EditRelationship data is broken
  root/edit/details/historic/EditRelationship.js
  root/static/scripts/common/components/Warning.js
Labels: Bug

#1611 MBS-10986: Convert edit error templates to React
  lib/MusicBrainz/Server/Controller/Edit.pm
  lib/MusicBrainz/Server/Edit.pm
  root/components/common-macros.tt
  root/edit/CannotApproveEdit.js
  root/edit/CannotCancelEdit.js
  root/edit/CannotVote.js
  root/edit/NoteIsRequired.js
  root/edit/cannot_approve.tt
  root/edit/cannot_cancel.tt
  root/edit/cannot_vote.tt
  root/edit/require_note.tt
  root/server/components.js
  root/static/scripts/common/components/EditLink.js
  root/static/scripts/common/utility/entityHref.js
  root/types.js
Labels: React

#1657 MBS-11044: Drop references to TOBEDELETED edit status
  lib/MusicBrainz/Server/Constants.pm
  lib/MusicBrainz/Server/Data/Edit.pm
  lib/MusicBrainz/Server/EditQueue.pm
  root/components/common-macros.tt
  root/constants.js
  root/edit/components/EditSidebar.js
  root/edit/edit_header.tt
  root/statistics/stats.js
  root/types.js
  root/utility/edit.js
Labels: Refactoring

#1662 Edit diff improvements
  root/edit/details/EditAlias.js
  root/edit/details/EditArtist.js
  root/edit/details/EditEvent.js
  root/edit/details/EditLabel.js
  root/edit/details/EditPlace.js
  root/edit/details/EditRecording.js
  root/edit/details/EditSeries.js
Labels: QoL

#1661 MBS-11048: Convert Edit Area edit to React
  lib/MusicBrainz/Server/Edit/Area/Edit.pm
  root/edit/details/EditArea.js
  root/edit/details/edit_area.tt
  root/server/components.js
Labels: React

#1665 MBS-11051: Convert Edit Artist Credit edit to React
  lib/MusicBrainz/Server/Edit/Artist/EditArtistCredit.pm
  root/edit/details/EditArtistCredit.js
  root/edit/details/edit_artist_credit.tt
  root/server/components.js
Labels: React

#1664 MBS-11050: Convert Edit URL edit to React
  lib/MusicBrainz/Server/Edit/URL/Edit.pm
  root/edit/details/EditUrl.js
  root/edit/details/edit_url.tt
  root/server/components.js
Labels: React

#1667 Hydrate improvements
  .eslintrc.yaml
  root/entity/Tags.js
  root/layout/components/Head.js
  root/layout/components/globalsScript.js
  root/layout/components/sidebar/SidebarTags.js
  root/static/scripts/common/DBDefs-client.js
  root/static/scripts/common/components/TagEditor.js
  root/utility/hydrate.js
  root/utility/sanitizedContext.js
  root/vars.js
  t/selenium/release-editor/The_Downward_Spiral.html
  webpack/definePluginConfig.js
Labels: Refactoring
