Repository metabrainz/musicbrainz-server, pull requests merged in 2020-06, with the labels that each got.

#1504 MBS-10771: Block tagging for unverified users
  lib/MusicBrainz/Server/Controller/Role/Tag.pm
  root/layout/components/sidebar/SidebarTags.js
  root/static/scripts/common/components/TagEditor.js
  root/types.js
  root/utility/sanitizedEditor.js
  t/lib/t/MusicBrainz/Server/Controller/Work/Tags.pm
Labels: New feature

#1500 MBS-10393: Convert Add Standalone Recording edit to React
  lib/MusicBrainz/Server/Edit/Recording/Create.pm
  root/edit/details/AddStandaloneRecording.js
  root/edit/details/add_standalone_recording.tt
  root/server/components.js
Labels: React

#1547 MBS-10882: Remove accidental duplicate push
  lib/MusicBrainz/Server/Data/ReleaseGroup.pm
Labels: Regression/Beta

#1550 MBS-10836: Fix edit / remove collection links
  root/user/UserCollections.js
Labels: Bug

#1545 MBS-10856: Trim whitespace on relationship credits
  lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
Labels: Bug

#1511 MBS-10186: Check for missing CD TOC on SetTrackLengths
  lib/MusicBrainz/Server/Edit/Medium/SetTrackLengths.pm
  t/lib/t/MusicBrainz/Server/Edit/Medium/SetTrackLengths.pm
Labels: Bug

#1503 MBS-9340: Only allow mul and zxx as the only work language
  lib/MusicBrainz/Server/Form/Work.pm
  root/static/scripts/work.js
Labels: Bug

#1514 MBS-9931: Fail gracefully when trying to remove example rel
  lib/MusicBrainz/Server/Edit/Relationship/Delete.pm
  lib/MusicBrainz/Server/Entity/EditNote.pm
  t/lib/t/MusicBrainz/Server/Edit/Relationship/Delete.pm
  t/sql/edit_relationship_delete.sql
Labels: New feature

#1548 MBS-10862: Report "CatNoLooksLikeLabelCode"
  lib/MusicBrainz/Server/Report/CatNoLooksLikeLabelCode.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/CatNoLooksLikeLabelCode.js
  root/report/ReportsIndex.js
  root/server/components.js
Labels: New feature

#1512 MBS-10821: Remove orphaned recordings from collections for deletion
  admin/sql/CreateFunctions.sql
  admin/sql/updates/20200512-mbs-10821-orphaned-recording-collection.sql
  t/pgtap/delete_orphaned_recordings.sql
Labels: Bug

#1573 MBS-10907: Set white background color to HTML body
  root/static/styles/layout.less
Labels: QoL

#1568 MBS-10770: add report about relationships with future dates
  lib/MusicBrainz/Server/Report/RecordingsWithFutureDates.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/DeprecatedRelationshipRecordings.js
  root/report/RecordingsWithFutureDates.js
  root/report/ReportsIndex.js
  root/report/components/RecordingRelationshipList.js
  root/report/types.js
  root/server/components.js
Labels: New feature

#1564 MBS-10895: conflicting discids report
  lib/MusicBrainz/Server/Report/ReleasesConflictingDiscIDs.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/ReleasesConflictingDiscIds.js
  root/report/ReportsIndex.js
  root/report/components/ReleaseList.js
  root/server/components.js
Labels: New feature

#1474 MBS-10777: Convert Add/Remove Relationship edits to React
  lib/MusicBrainz/Server/Edit/Relationship/Create.pm
  lib/MusicBrainz/Server/Edit/Relationship/Delete.pm
  lib/MusicBrainz/Server/Entity/Relationship.pm
  root/edit/details/AddRelationship.js
  root/edit/details/RemoveRelationship.js
  root/edit/details/add_relationship.tt
  root/edit/details/remove_relationship.tt
  root/relationship/linktype/RelationshipTypeIndex.js
  root/server/components.js
  root/static/scripts/common/components/Relationship.js
  root/types.js
Labels: React

#1487 MBS-10801, MBS-10802: Convert Reorder Relationships edit to React
  lib/MusicBrainz/Server/Edit/Relationship/Reorder.pm
  root/components/common-macros.tt
  root/edit/details/ReorderRelationships.js
  root/edit/details/reorder_relationships.tt
  root/server/components.js
  root/static/scripts/common/components/Relationship.js
  root/static/styles/layout.less
Labels: React

#1569 MBS-10894: Add LC code in help bubble after adding label in release editor
  root/static/scripts/common/entity.js
Labels: QoL

#1571 MBS-10903: Update Operabase cleanup / validation
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug

#1517 MBS-10825: Fix Muziekweb cleanup, add work support
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug

#1447 MBS-10736: Add Napster autoselect + sidebar
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/Napster.pm
  root/static/images/favicons/napster-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature

#1574 MBS-10908: Stop recording-of rel edits showing for all recordings of a work
  lib/MusicBrainz/Server/Edit/Relationship/Create.pm
  lib/MusicBrainz/Server/Edit/Relationship/Delete.pm
  lib/MusicBrainz/Server/Edit/Relationship/Edit.pm
  lib/MusicBrainz/Server/Edit/Relationship/RelatedEntities.pm
  lib/MusicBrainz/Server/Edit/Relationship/Reorder.pm
Labels: Bug

#1506 MBS-10816: Convert Add Label Edit to React
  lib/MusicBrainz/Server/Edit/Label/Create.pm
  root/edit/details/AddLabel.js
  root/edit/details/add_label.tt
  root/server/components.js
Labels: React
