Repository metabrainz/musicbrainz-server, pull requests merged in 2020-01, with the labels that each got.

#1064 MBS-9491: List genre on tag search results
  lib/MusicBrainz/Server/Controller/Search.pm
  lib/MusicBrainz/Server/Data/Search.pm
  root/search/components/TagResults.js
Labels: QoL

#1347 Fix MBS-10522: Save subscriptions to merge destination
  lib/MusicBrainz/Server/Data/Artist.pm
  lib/MusicBrainz/Server/Data/Label.pm
  lib/MusicBrainz/Server/Data/Series.pm
  lib/MusicBrainz/Server/Data/Subscription.pm
  lib/MusicBrainz/Server/Edit/Role/MergeSubscription.pm
Labels: Bug

#1346 Fix MBS-10553: Translate report reason only if needed
  lib/MusicBrainz/Server/Form/User/Report.pm
Labels: QoL

#1350 MBS-10565: Fix item_entity_type field name
  lib/MusicBrainz/Server/Form/Admin/Attributes.pm
  root/admin/attributes/form.tt
Labels: Bug

#1334 MBS-10531: Document and fix handling of maps service access token
  lib/DBDefs.pm.sample
  lib/DBDefs/Default.pm
  root/area/AreaPlaces.js
  root/place/PlaceMap.js
Labels: QoL

#1355 MBS-10365: Convert entity lists to react-table (II)
  lib/MusicBrainz/Server/Data/Release.pm
  root/components/InstrumentRelTypes.js
  root/components/list/RecordingList.js
  root/components/list/ReleaseList.js
  root/static/scripts/common/components/ArtistListEntry.js
  root/utility/tableColumns.js
Labels: React

#1354 MBS-10536: Remove span.name-variation around "see all" releases link
  root/release/ReleaseHeader.js
Labels: Regression/Beta

#1353 MBS-10560: Show full country names in release edits
  root/edit/details/add_release.tt
  root/edit/details/edit_release_label.tt
Labels: Regression/Beta

#1351 Fix MBS-10567: Limit series types as per DB constraint
  entities.json
  lib/MusicBrainz/Server/Form/Admin/Attributes.pm
Labels: Bug

#1344 MBS-10552: Add Deezer links to the sidebar
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/Deezer.pm
  root/static/images/favicons/deezer-32.png
  root/static/scripts/common/constants.js
  root/static/styles/favicons.less
Labels: New feature

#1358 MBS-10571: Fix "localized" ModBot email display
  lib/MusicBrainz/Server/Email.pm
  lib/MusicBrainz/Server/Translation.pm
  t/lib/t/MusicBrainz/Server/Email.pm
Labels: Regression/Beta

#1359 Fix MBS-10572: Have one Jed bundle per language
  babel.config.js
  root/account/EditProfile.js
  root/area/create.tt
  root/artist/create.tt
  root/components/UserAccountLayout.js
  root/entity/edit.tt
  root/event/create.tt
  root/forms/dialog.tt
  root/instrument/create.tt
  root/label/create.tt
  root/layout.tt
  root/layout/components/Head.js
  root/place/create.tt
  root/recording/create.tt
  root/release/edit/layout.tt
  root/release/edit_relationships.tt
  root/release/index.tt
  root/release_group/ReleaseGroupIndex.js
  root/release_group/ReleaseGroupLayout.js
  root/release_group/create.tt
  root/series/create.tt
  root/server/gettext.js
  root/static/scripts/common/i18n/wrapGettext.js
  root/static/scripts/jed-data.js
  root/statistics/StatisticsLayout.js
  root/statistics/timeline.tt
  root/work/create.tt
  webpack.client.config.js
Labels: Bug

#1360 Install pkg-config to probe ICU headers/libraries
  INSTALL.md
  docker/Dockerfile.tests
  docker/templates/macros.m4
Labels: Bug

#1229 MBS-10390 and MBS-10398 Place entity edit details
  lib/MusicBrainz/Server/Edit/Place/Create.pm
  lib/MusicBrainz/Server/Edit/Place/Edit.pm
  root/edit/details/AddPlace.js
  root/edit/details/EditAlias.js
  root/edit/details/EditPlace.js
  root/edit/details/add_place.tt
  root/edit/details/edit_place.tt
  root/server/components.js
  root/static/scripts/common/components/DescriptiveLink.js
  root/static/scripts/edit/components/edit/Diff.js
  root/static/scripts/edit/components/edit/FullChangeDiff.js
  root/utility/coordinates.js
  t/lib/t/TemplateMacros.pm
Labels: React

#1211 MBS-5460/MBS-5572: Add shift-click selecting to more places
  root/artist/edit_form.tt
  root/release/edit/recordings.tt
  root/static/scripts/common.js
  root/static/scripts/common/MB/Control/SelectAll.js
  root/static/scripts/edit/MB/Control/ArtistEdit.js
  root/static/scripts/release-editor/init.js
Labels: QoL

#1356 MBS-10365: Convert entity lists to react-table (III)
  root/components/list/EventList.js
  root/utility/tableColumns.js
Labels: React

#1352 Implement MBS-9477, MBS-10568, MBS-10569: DiscID tab improvements
  entities.json
  lib/MusicBrainz/Server.pm
  lib/MusicBrainz/Server/Controller/Release.pm
  lib/MusicBrainz/Server/Data/MediumCDTOC.pm
  lib/MusicBrainz/Server/Entity/Release.pm
  root/components/EntityTabLink.js
  root/components/EntityTabs.js
  root/release/discids.tt
  root/static/styles/entity.less
  root/types.js
  t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
Labels: New feature

#1321 MBS-6539: Allow resolving MBIDs of unknown type
  lib/MusicBrainz/Server/Controller/MBID.pm
  lib/MusicBrainz/Server/Controller/OtherLookup.pm
  root/mbid/NotFound.js
  root/server/components.js
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
Labels: New feature

#1349 Fix MBS-10366: Remove rather than renumber pregap track if DiscID is present
  root/release/edit/tracklist.tt
  root/static/scripts/release-editor/fields.js
Labels: Bug
