Repository metabrainz/musicbrainz-server, pull requests merged in 2020-10, with the labels that each got.

#1722 Remove span.name-variation around "see all" releases link
  root/release/ReleaseHeader.js
Labels: Regression/Beta

#1724 MBS-11140: Build Jed language bundles in prod
  docker/templates/Dockerfile.website.m4
Labels: Bug

#1726 MBS-11149: Fix ironic mis(s)pelling
  root/components/Aliases/index.js
  root/entity/alias/edit_form.tt
Labels: QoL

#1728 MBS-11147: Update autocomplete serialization
  lib/MusicBrainz/Server/WebService/JSONSerializer.pm
Labels: Regression/Beta

#1736 MBS-4118 (fixup): Also use full-icu on docker
  docker/scripts/start_template_renderer.sh
Labels: Bug

#1734 MBS-11148: Stop highlighting Google Play links
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/GooglePlay.pm
  root/static/images/favicons/googleplay-32.png
  root/static/scripts/common/constants.js
  root/static/styles/favicons.less
Labels: QoL

#1735 MBS-11150: Don't send artist gid if none selected
  root/cdtoc/attach_filter_artist.tt
Labels: Bug

#1725 MBS-11141: Convert Edit Relationship edit to React
  lib/MusicBrainz/Server/Edit/Relationship/Edit.pm
  root/edit/details/EditRelationship.js
  root/edit/details/edit_relationship.tt
  root/server/components.js
Labels: React

#1701 MBS-11115: Show extra info when attaching/moving discIDs
  lib/MusicBrainz/Server/Controller/CDTOC.pm
  root/cdtoc/attach_confirm.tt
  root/components/common-macros.tt
  root/static/styles/edit.less
  root/static/styles/layout.less
Labels: QoL

#1727 MBS-11139: Use HTTPS for display on Library of Congress links
  lib/MusicBrainz/Server/Entity/URL/LoC.pm
Labels: QoL

#1730 MBS-11152: Convert entity/ratings page to React
  lib/MusicBrainz/Server/Controller/Role/Rating.pm
  root/components/RatingStars.js
  root/components/rating-macros.tt
  root/entity/Ratings.js
  root/entity/ratings.tt
  root/server/components.js
  root/types.js
Labels: React

#1633 MBS-8725: Allow mediums to have an unknown tracklist
  lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
  lib/MusicBrainz/Server/Data/Track.pm
  lib/MusicBrainz/Server/Edit/Medium/Create.pm
  lib/MusicBrainz/Server/Edit/Medium/Edit.pm
  lib/MusicBrainz/Server/Entity/Medium.pm
  root/components/medium.tt
  root/edit/details/AddMedium.js
  root/release/edit/recordings.tt
  root/release/edit/tracklist.tt
  root/release/edit_relationships.tt
  root/release/index.tt
  root/static/scripts/release-editor/edits.js
  root/static/scripts/release-editor/fields.js
  root/static/scripts/tests/release-editor/edits.js
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm
  t/sql/webservice.sql
Labels: New feature

#1700 MBS-11117: Create report for too long discIDs
  lib/MusicBrainz/Server/Report/CDTOCDubiousLength.pm
  lib/MusicBrainz/Server/Report/CDTOCReport.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/CDTocDubiousLength.js
  root/report/ReportsIndex.js
  root/report/components/CDTocList.js
  root/report/types.js
  root/server/components.js
  root/types.js
Labels: New feature

#1205 Allow showing tracklists everywhere when attaching/viewing discIDs
  lib/MusicBrainz/Server/Controller/CDTOC.pm
  root/cdtoc/attach_list.tt
  root/cdtoc/list.tt
  root/cdtoc/lookup.tt
Labels: QoL

#1365 MBS-7256: Add "Expand all mediums" to release page
  root/components/MediumToolbox.js
  root/release/index.tt
  root/server/components.js
  root/static/scripts/common/MB/release.js
  root/static/scripts/common/utility/request.js
  root/static/styles/layout.less
Labels: QoL

#1743 MBS-11167: Normalize vk.com links to HTTPS
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#1742 MBS-11165: Update the VK logo
  root/static/images/favicons/vk-16.png
  root/static/images/favicons/vk-32.png
  root/static/styles/favicons.less
Labels: QoL

#1745 MBS-11173: Turn pending votes by deleted editor to Abstain
  lib/MusicBrainz/Server/Data/Editor.pm
  root/admin/delete_user.tt
  t/lib/t/MusicBrainz/Server/Data/Editor.pm
  t/sql/vote.sql
Labels: New feature

#1740 MBS-11162: Show correct work type description if preselected
  root/work/edit_form.tt
Labels: Bug

#1746 MBS-11176: Fix missing nonEmpty ternary
  root/layout/components/ExternalLinks.js
Labels: Bug

#1747 MBS-11174: Add historic release adds to added_entities_counts
  lib/MusicBrainz/Server/Data/Editor.pm
Labels: Bug

#1741 MBS-11163: Show type descriptions when editing more entities
  lib/MusicBrainz/Server/Controller/Area.pm
  lib/MusicBrainz/Server/Controller/Artist.pm
  lib/MusicBrainz/Server/Controller/Event.pm
  lib/MusicBrainz/Server/Controller/Place.pm
  lib/MusicBrainz/Server/Entity/AreaType.pm
  lib/MusicBrainz/Server/Entity/ArtistType.pm
  lib/MusicBrainz/Server/Entity/PlaceType.pm
  root/area/edit_form.tt
  root/artist/edit_form.tt
  root/components/forms.tt
  root/event/edit_form.tt
  root/place/edit_form.tt
  root/static/scripts/area.js
  root/static/scripts/artist.js
  root/static/scripts/edit/typeBubble.js
  root/static/scripts/event.js
  root/static/scripts/place.js
  root/static/scripts/work.js
  root/work/edit_form.tt
  webpack.client.config.js
Labels: New feature

#1738 MBS-11158: Make relationship type rowids visible to all
  root/relationship/linktype/RelationshipTypeIndex.js
Labels: QoL

#1750 MBS-11182: Stop highlighting LyricWiki links
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/LyricWiki.pm
  root/static/images/favicons/lyricwiki-32.png
  root/static/scripts/common/constants.js
  root/static/styles/favicons.less
Labels: QoL

#1753 MBS-11189: Stop highlighting PureVolume links
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/PureVolume.pm
Labels: QoL

#1757 MBS-11196: Whitelist saisaibatake.ame-zaiku.com for instruments
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/Gakki.pm
  root/static/images/favicons/gakki-16.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature

#1752 MBS-11186: Add missing space between class names
  root/components/common-macros.tt
Labels: Bug

#1749 MBS-11177: Drop "Description" label from type_bubble
  root/components/forms.tt
Labels: QoL

#1755 MBS-11192: Add voting-icon for Approve
  root/components/common-macros.tt
  root/static/images/attribution.txt
  root/static/images/icons/tick.png
  root/static/styles/edit.less
Labels: QoL

#1760 MBS-11194: Fix ISE when historic EditRelationship data is broken
  root/edit/details/historic/EditRelationship.js
Labels: Bug

#1765 MBS-11204: Avoid crashing if entity1_id is missing
  lib/MusicBrainz/Server/Edit/Historic/Relationship.pm
Labels: Bug

#1764 MBS-11199: Remove superfluous 7digital parameters
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#1748 MBS-11174: Add historic release adds to UserEditsProperty
  root/static/scripts/common/constants/editTypes.js
  root/user/UserProfile.js
Labels: Bug

#1761 MBS-11197: Add validation for Mainly Norfolk links and normalize
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#1763 MBS-11200: Add works to VGMdb autocleanup
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#1756 MBS-11185: Add "is not" operator to link_type edit search
  lib/MusicBrainz/Server/EditSearch/Predicate/RelationshipType.pm
  root/edit/search_macros.tt
  root/static/scripts/common/MB/edit_search.js
Labels: New feature

#1739 MBS-10281, MBS-11160, MBS-11161: ISE fixes
  admin/BuildIncrementalSitemaps.pl
  admin/DumpIncrementalJSON
  admin/DumpJSON
  lib/Catalyst/Plugin/ErrorInfo.pm
  lib/Catalyst/Plugin/Sentry.pm
  lib/MusicBrainz/Errors.pm
  lib/MusicBrainz/Server.pm
  lib/MusicBrainz/Server/Controller/Root.pm
  lib/MusicBrainz/Server/EditQueue.pm
  root/main/info/error.tt
  t/lib/t/MusicBrainz/Server/Controller/Errors.pm
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
Labels: Bug

#1718 MBS-7219: Hide links to empty ArtistRecording subsets
  lib/MusicBrainz/Server/Controller/Artist.pm
  lib/MusicBrainz/Server/Data/Recording.pm
  root/artist/ArtistRecordings.js
Labels: QoL

#1518 MBS-10829: Fix SOLR syntax for recording with no length
  root/static/scripts/release-editor/recordingAssociation.js
Labels: Bug
