Repository metabrainz/musicbrainz-server, pull requests merged in 2020-02, with the labels that each got.

#1368 MBS-10604: Remove allowNew from Add Place edit
  root/edit/details/AddPlace.js
Labels: Regression/Beta

#1169 MBS-9917: Convert instrument list pages to React
  lib/MusicBrainz/Server/Controller/Instrument.pm
  root/instrument/InstrumentArtists.js
  root/instrument/InstrumentRecordings.js
  root/instrument/InstrumentReleases.js
  root/instrument/artists.tt
  root/instrument/recordings.tt
  root/instrument/releases.tt
  root/server/components.js
Labels: React

#462 MBS-9164: Show edit history (but not notes) when not logged in
  lib/MusicBrainz/Server/Controller/Edit.pm
  lib/MusicBrainz/Server/Controller/Role/EditListing.pm
  root/edit/components/EditSidebar.js
  root/edit/components/EditSummary.js
  root/edit/edit_header.tt
  root/edit/index.tt
  root/edit/list.tt
  root/edit/search_macros.tt
  root/layout/components/BottomMenu.js
  root/layout/components/sidebar/CollectionSidebar.js
  root/layout/components/sidebar/EditLinks.js
  root/robots.txt.production
Labels: New feature

#1179 Link from guess case options to guess case documentation page
  root/components/forms.tt
  root/static/styles/release-editor.less
Labels: QoL

#1136 MBS-3873: Report: non-matching RG/release titles
  lib/MusicBrainz/Server/Report/ReleaseRGDifferentName.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/ReleaseRgDifferentName.js
  root/report/ReportsIndex.js
  root/report/types.js
  root/server/components.js
Labels: New feature

#1371 MBS-10308: Clean up and validate maniadb URLs
  lib/MusicBrainz/Server/Entity/URL/Maniadb.pm
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#1374 MBS-10625: Block even more smart URLs
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#1125 MBS-10209: Finetune instagram regex
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug

#1196 MBS-2436: Link to created recordings on EditMedium
  lib/MusicBrainz/Server/Edit/Medium/Edit.pm
  t/lib/t/MusicBrainz/Server/Edit/Medium/Edit.pm
Labels: QoL

#1364 MBS-10584: Collapse work artists if too many
  root/server/components.js
  root/static/scripts/common.js
  root/static/scripts/common/components/WorkArtists.js
  root/static/scripts/common/components/WorkListEntry.js
  root/static/styles/entity.less
  root/utility/tableColumns.js
Labels: QoL

#1164 MBS-4326: Show DiscID edits in RG and artist history
  lib/MusicBrainz/Server/Edit/Medium/AddDiscID.pm
  lib/MusicBrainz/Server/Edit/Medium/MoveDiscID.pm
  t/lib/t/MusicBrainz/Server/Edit/Medium/MoveDiscID.pm
Labels: QoL

#1373 MBS-10620: Add DAHR to the otherdbs whitelist
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/DAHR.pm
  root/static/images/favicons/dahr-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature

#1376 Fix MBS-10622, MBS-10627, MBS-10630 (regressions from MBS-7678)
  root/components/StaticRelationshipsDisplay.js
  root/static/scripts/common/constants.js
  root/utility/groupRelationships.js
Labels: Regression/Beta

#1101 MBS-10223: Use relationship credits in ArtistRoles
  lib/MusicBrainz/Server/Data/Event.pm
  lib/MusicBrainz/Server/Data/Search.pm
  lib/MusicBrainz/Server/Data/Work.pm
  lib/MusicBrainz/Server/Entity/Event.pm
  lib/MusicBrainz/Server/Entity/Work.pm
  root/static/scripts/common/components/ArtistRoles.js
  root/types.js
  root/utility/tableColumns.js
Labels: Bug

#1361 Fix MBS-10576: Support errors with HTML
  lib/MusicBrainz/Server/Data/Release.pm
  root/components/FieldErrors.js
  root/components/FormRowSelect.js
  root/components/forms.tt
  root/release/merge.tt
Labels: Bug

#1192 Eslint fixes for guessFeat
  package.json
  root/static/scripts/edit/utility/guessFeat.js
  root/static/scripts/tests/guessFeat.js
  yarn.lock
Labels: Refactoring

#1268 Eslint fixes by rule, pt. 1
  root/release_group/edit_form.tt
  root/static/scripts/common/MB/Control/Autocomplete.js
  root/static/scripts/edit/ExampleRelationships.js
  root/static/scripts/edit/MB/CoverArt.js
  root/static/scripts/edit/utility/similarity.js
  root/static/scripts/guess-case/MB/GuessCase/Main.js
  root/static/scripts/guess-case/MB/GuessCase/Output.js
  root/static/scripts/jquery.flot.musicbrainz_events.js
  root/static/scripts/place.js
  root/static/scripts/relationship-editor/common/dialog.js
  root/static/scripts/relationship-editor/common/fields.js
  root/static/scripts/release-editor/duplicates.js
  root/static/scripts/release-editor/fields.js
  root/static/scripts/release-editor/init.js
  root/static/scripts/release-editor/recordingAssociation.js
  root/static/scripts/release-editor/trackParser.js
  root/static/scripts/release-editor/utils.js
  root/static/scripts/tests/react-macros.js
  root/static/scripts/tests/release-editor/edits.js
  root/static/scripts/tests/release-editor/fields.js
  root/static/scripts/timeline.js
Labels: Refactoring

#1366 Fix MBS-10586 / MBS-10587 / MBS-10588: Release Duplicates medium format fixes
  root/static/scripts/release-editor/duplicates.js
Labels: Bug

#1378 MBS-10623: Auto-add US iTunes store country-code
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#1390 MBS-10608: Restore parameter options for edit note search
  root/edit/search_macros.tt
Labels: Regression/Beta

#1389 Allow number-string equality in assertEditData
  t/selenium.js
Labels: Regression/Beta

#1391 MBS-10611: Remove double brackets from (ended) relationships
  root/components/RelationshipTargetLinks.js
  root/utility/relationshipDateText.js
Labels: Regression/Beta

#1065 MBS-9491: Add genre MBIDs to the WS
  .circleci/config.yml
  docker/Dockerfile.tests
  lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Utils.pm
  lib/MusicBrainz/Server/WebService/XMLSerializer.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseArtists.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseReleaseGroups.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupDiscID.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupDiscID.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupTagsRatings.pm
Labels: New feature

#1370 Move Selenium tests to Jenkins
  .circleci/config.yml
  .dockerignore
  docker/Dockerfile.tests
  docker/musicbrainz-tests/add_mbtest_alias.sh
  docker/musicbrainz-tests/install_pg_extensions.sh
  docker/musicbrainz-tests/postgresql.conf
  docker/musicbrainz-tests/redis.service
  docker/musicbrainz-tests/run_selenium_tests.sh
  lib/MusicBrainz/Server/Data/FileCache.pm
  package.json
  script/compile_resources.sh
  script/reset_selenium_env.sh
  t/selenium.js
  t/selenium/Artist_Credit_Editor.html
  t/selenium/External_Links_Editor.html
  t/selenium/MBS-7456.html
  webpack.client.config.js
  webpack.server.config.js
  webpack/constants.js
  webpack/moduleConfig.js
  yarn.lock
Labels: Refactoring

#1385 MBS-10643: Add autoselect for artists for CPDL
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#1260 MBS-9654: Show expanded ACs on recording merges
  root/components/common-macros.tt
  root/components/list/RecordingList.js
  root/edit/details/merge_recordings.tt
  root/recording/RecordingMerge.js
  root/static/scripts/common/components/ExpandedArtistCredit.js
Labels: QoL

#1379 Reduce noise in webservice server logs
  lib/MusicBrainz/Server/ControllerBase/WS/2.pm
  lib/MusicBrainz/Server/WebService/XMLSerializer.pm
Labels: Refactoring

#1386 MBS-10593 / MBS-10649: Edit Release Label bugfixes
  lib/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm
  root/edit/details/edit_release_label.tt
Labels: Bug

#1388 MBS-10594: Fail add annotation edit if entity is gone
  lib/MusicBrainz/Server/Edit/Annotation/Edit.pm
Labels: Bug

#1066 MBS-10166: Add genre entity to the WS
  lib/MusicBrainz/Server/Controller/WS/2/Genre.pm
  lib/MusicBrainz/Server/ControllerBase/WS/2.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Utils.pm
  lib/MusicBrainz/Server/WebService/XMLSerializer.pm
  root/entity/Details.js
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseArtists.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseReleaseGroups.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupDiscID.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupTagsRatings.pm
  t/sql/webservice.sql
Labels: New feature

#1375 MBS-10058: Convert merge edits to React
  lib/MusicBrainz/Server/Edit.pm
  lib/MusicBrainz/Server/Edit/Area/Merge.pm
  lib/MusicBrainz/Server/Edit/Artist/Merge.pm
  lib/MusicBrainz/Server/Edit/Event/Merge.pm
  lib/MusicBrainz/Server/Edit/Historic/MergeRelease.pm
  lib/MusicBrainz/Server/Edit/Instrument/Merge.pm
  lib/MusicBrainz/Server/Edit/Label/Merge.pm
  lib/MusicBrainz/Server/Edit/Place/Merge.pm
  lib/MusicBrainz/Server/Edit/Recording/Merge.pm
  lib/MusicBrainz/Server/Edit/ReleaseGroup/Merge.pm
  lib/MusicBrainz/Server/Edit/Series/Merge.pm
  lib/MusicBrainz/Server/Edit/Work/Merge.pm
  root/artist/ArtistIndex.js
  root/collection/CollectionIndex.js
  root/components/list/ReleaseGroupList.js
  root/edit/details/MergeAreas.js
  root/edit/details/MergeArtists.js
  root/edit/details/MergeEvents.js
  root/edit/details/MergeInstruments.js
  root/edit/details/MergeLabels.js
  root/edit/details/MergePlaces.js
  root/edit/details/MergeRecordings.js
  root/edit/details/MergeReleaseGroups.js
  root/edit/details/MergeSeries.js
  root/edit/details/MergeWorks.js
  root/edit/details/historic/MergeReleases.js
  root/edit/details/historic/merge_releases.tt
  root/edit/details/merge_areas.tt
  root/edit/details/merge_artists.tt
  root/edit/details/merge_common.tt
  root/edit/details/merge_events.tt
  root/edit/details/merge_instruments.tt
  root/edit/details/merge_labels.tt
  root/edit/details/merge_places.tt
  root/edit/details/merge_recordings.tt
  root/edit/details/merge_release_groups.tt
  root/edit/details/merge_series.tt
  root/edit/details/merge_works.tt
  root/series/SeriesIndex.js
  root/server/components.js
  root/types.js
Labels: React

#1372 MBS-10617 : Convert Add work edit to React
  lib/MusicBrainz/Server/Edit/Work/Create.pm
  root/edit/details/AddWork.js
  root/edit/details/add_work.tt
  root/server/components.js
Labels: React

#1398 MBS-10659: Always show entity credits in rel edits
  lib/MusicBrainz/Server/Edit/Relationship/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/EditExternalLinks.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/EditRelationships.pm
  t/lib/t/MusicBrainz/Server/Controller/RelationshipEditor.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
  t/lib/t/MusicBrainz/Server/Edit/Relationship/Edit.pm
Labels: Bug

#1399 MBS-10515: Fix sort of release recordings in merge
  lib/MusicBrainz/Server/Data/Release.pm
Labels: Regression/Beta
