Repository metabrainz/musicbrainz-server, pull requests merged in 2020-12, with the labels that each got.

#1803 MBS-11241: Seed annotation, edit_note with textarea
  root/components/PostParameters.js
  root/static/styles/forms.less
Labels: Bug, Regression/Beta

#1813 Set SameSite=None on beta cookie
  lib/MusicBrainz/Server.pm
  lib/MusicBrainz/Server/Controller/Root.pm
Labels: Regression/Beta

#1791 MBS-10590: Implement IROMBOOK images for instruments
  lib/MusicBrainz/Server/Report/InstrumentsWithoutAnImage.pm
  root/layout/components/sidebar/InstrumentSidebar.js
  root/report/InstrumentsWithoutAnImage.js
  root/static/scripts/common/components/IrombookImage.js
Labels: New feature

#1819 Beta: Fix load_first_release_date for empty recording lists
  lib/MusicBrainz/Server/Data/Recording.pm
Labels: Regression/Beta

#1797 MBS-11229: Convert cover art edits to React
  lib/MusicBrainz/Server/Edit/Release/AddCoverArt.pm
  lib/MusicBrainz/Server/Edit/Release/EditCoverArt.pm
  lib/MusicBrainz/Server/Edit/Release/RemoveCoverArt.pm
  lib/MusicBrainz/Server/Edit/Release/ReorderCoverArt.pm
  lib/MusicBrainz/Server/Entity/Artwork.pm
  root/components/Artwork.js
  root/components/common-macros.tt
  root/edit/components/EditArtwork.js
  root/edit/details/AddCoverArt.js
  root/edit/details/EditCoverArt.js
  root/edit/details/RemoveCoverArt.js
  root/edit/details/ReorderCoverArt.js
  root/edit/details/add_cover_art.tt
  root/edit/details/edit_cover_art.tt
  root/edit/details/macros.tt
  root/edit/details/remove_cover_art.tt
  root/edit/details/reorder_cover_art.tt
  root/server/components.js
  root/types.js
Labels: React

#1804 MBS-11243 (I): Convert cover art forms and pages to React
  lib/MusicBrainz/Server/Controller/Release.pm
  lib/MusicBrainz/Server/Entity/Release.pm
  root/components/EnterEdit.js
  root/components/EntityHeader.js
  root/components/EntityTabs.js
  root/components/common-macros.tt
  root/components/forms.tt
  root/release/CoverArt.js
  root/release/CoverArtDarkened.js
  root/release/CoverArtFields.js
  root/release/ReleaseHeader.js
  root/release/ReleaseLayout.js
  root/release/RemoveCoverArt.js
  root/release/add_cover_art.tt
  root/release/caa_darkened.tt
  root/release/cover_art.tt
  root/release/cover_art_fields.tt
  root/release/edit_cover_art.tt
  root/release/remove_cover_art.tt
  root/server/components.js
  root/types.js
  t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
Labels: React

#1795 MBS-11221 / MBS-11234: Normalize whosampled.com links to HTTPS and add validation
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature
