Repository metabrainz/musicbrainz-server, pull requests merged in 2020-07, with the labels that each got.

#1580 Fix some left-behind "import React" imports
  root/static/scripts/common/components/Autocomplete2.js
  root/static/scripts/common/components/FingerprintTable.js
  root/static/scripts/common/components/ReleaseEvents.js
  root/static/scripts/common/components/WorkArtists.js
Labels: Refactoring

#1587 MBS-10937: Run load_meta on event lists for ratings
  lib/MusicBrainz/Server/Controller/Area.pm
  lib/MusicBrainz/Server/Controller/Artist.pm
  lib/MusicBrainz/Server/Controller/Place.pm
Labels: Bug

#1584 MBS-10927: Check whether entity existed before setting allowNew
  root/edit/details/AddRelationship.js
  root/static/scripts/common/components/Relationship.js
Labels: Bug

#1579 MBS-10917: Remove no longer used "attendance"
  lib/MusicBrainz/Server/Controller/Event.pm
Labels: Bug

#1543 MBS-10833: Avoid crashing if entity0_id is missing
  lib/MusicBrainz/Server/Edit/Historic/Relationship.pm
  lib/MusicBrainz/Server/Entity/Relationship.pm
Labels: Bug

#1594 MBS-10943: Fix loading attribute on Relationship::Delete
  lib/MusicBrainz/Server/Edit/Relationship/Delete.pm
Labels: Bug

#1589 MBS-10930: Fix loading relationship entities for removed reltypes
  lib/MusicBrainz/Server/Edit/Relationship/Create.pm
  lib/MusicBrainz/Server/Entity/Relationship.pm
  root/static/scripts/common/components/Relationship.js
  root/types.js
  t/lib/t/MusicBrainz/Server/Controller/WS/js/Release.pm
Labels: Bug

#1570 MBS-9502: Add search for pre-existing barcode value in release editor
  root/release/edit/information.tt
  root/static/scripts/release-editor/fields.js
  root/static/scripts/release-editor/validation.js
Labels: New feature

#1608 Update lodash and react-table to the latest version
  package.json
  yarn.lock
Labels: Refactoring

#1607 Skip looking for latest vote when not logged in
  root/edit/edit_header.tt
Labels: Bug

#1582 MBS-10925, MBS-10928: Update favicons for Baidu Baike and VGMdb
  root/static/images/favicons/baidu-32.png
  root/static/images/favicons/vgmdb-16.png
Labels: QoL

#1103 MBS-8725: Allow mediums to have an unknown tracklist
  lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
  lib/MusicBrainz/Server/Data/Track.pm
  lib/MusicBrainz/Server/Edit/Medium/Create.pm
  lib/MusicBrainz/Server/Edit/Medium/Edit.pm
  lib/MusicBrainz/Server/Entity/Medium.pm
  root/components/medium.tt
  root/edit/details/add_medium.tt
  root/release/edit/recordings.tt
  root/release/edit/tracklist.tt
  root/release/edit_relationships.tt
  root/release/index.tt
  root/static/scripts/release-editor/edits.js
  root/static/scripts/release-editor/fields.js
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm
  t/sql/webservice.sql
Labels: New feature
