Repository metabrainz/musicbrainz-server, pull requests merged in 2020-03, with the labels that each got.

#1402 MBS-10661: Highlight recording-work pending edits in release
  root/components/GroupedTrackRelationships.js
Labels: Bug

#1404 MBS-10671: Block ratings for unverified users
  lib/MusicBrainz/Server/Controller/Rating.pm
  root/components/RatingStars.js
  t/lib/t/MusicBrainz/Server/Controller/Rating.pm
Labels: New feature

#1416 MBS-9359: Only load language for each work once
  lib/MusicBrainz/Server/ControllerBase/WS/2.pm
Labels: Bug

#1409 MBS-9651: Ignore superseded votes for editor stats
  lib/MusicBrainz/Server/Data/Vote.pm
Labels: Bug

#1410 MBS-10683 / MBS-10684 / MBS-10685: Place map fixes
  root/place/edit_form.tt
  root/static/scripts/place.js
Labels: Bug

#1403 MBS-10633: Allow changing username capitalization
  lib/MusicBrainz/Server/Data/Editor.pm
  lib/MusicBrainz/Server/Form/Utils.pm
Labels: Bug

#1417 MBS-10689: Update MapBox API calls
  lib/DBDefs.pm.sample
  lib/DBDefs/Default.pm
  root/static/scripts/common/leaflet.js
Labels: Refactoring

#1397 MBS-10618 Convert Edit work edit to React
  lib/MusicBrainz/Server/Edit/Work/Edit.pm
  root/edit/details/EditWork.js
  root/edit/details/edit_work.tt
  root/server/components.js
Labels: React

#1384 MBS-10628: Make [no label] really special purpose
  lib/MusicBrainz/Server/Constants.pm
  lib/MusicBrainz/Server/Controller/Artist.pm
  lib/MusicBrainz/Server/Controller/Label.pm
  lib/MusicBrainz/Server/Data/Label.pm
  lib/MusicBrainz/Server/Data/Utils.pm
  lib/MusicBrainz/Server/Entity/Label.pm
  root/components/EntityTabs.js
  root/label/SpecialPurpose.js
  root/layout/components/sidebar/ArtistSidebar.js
  root/layout/components/sidebar/LabelSidebar.js
  root/server/components.js
  root/static/scripts/common/constants.js
  root/static/scripts/common/utility/isSpecialPurpose.js
  root/static/scripts/common/utility/isSpecialPurposeArtist.js
  t/lib/t/MusicBrainz/Server/Entity/Label.pm
Labels: New feature

#1419 MBS-10693: Restore FieldErrors for target on artist merges
  root/artist/ArtistMerge.js
Labels: Regression/Beta

#1400 MBS-10607: Add context to (unknown) strings
  lib/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm
  lib/MusicBrainz/Server/Entity/Release.pm
  root/edit/details/add_isrcs.tt
  root/edit/details/historic/convert_release_to_multiple_artists.tt
  root/edit/details/historic/mac_to_sac.tt
  root/entity/Details.js
  root/recording/RecordingIndex.js
  root/release_group/ReleaseGroupIndex.js
  root/static/scripts/release-editor/duplicates.js
Labels: QoL

#1412 Upgrade leaflet
  package.json
  yarn.lock
Labels: Refactoring

#1420 MBS-10695: Show language names on work lists
  root/static/scripts/common/components/WorkListEntry.js
  root/utility/tableColumns.js
Labels: QoL

#1421 MBS-7835: Old Create work edits should display [No lyrics] for zxx
  lib/MusicBrainz/Server/Edit/Work/Create.pm
Labels: Bug

#1156 MBS-4090: Report: non-matching recording/track titles
  lib/MusicBrainz/Server/Report/RecordingTrackDifferentName.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/RecordingTrackDifferentName.js
  root/report/ReportsIndex.js
  root/report/types.js
  root/server/components.js
Labels: New feature

#1426 MBS-10704: Only show Rels header if something to display
  root/components/Relationships.js
Labels: Bug

#1425 MBS-10699: Remove "medley" from guess case
  root/static/scripts/guess-case/utils.js
Labels: QoL

#1413 MBS-10365 (IV): Convert entity lists to react-table
  root/components/Table.js
  root/components/list/ReleaseGroupList.js
  root/utility/tableColumns.js
Labels: React

#1430 MBS-10712: Fix loading old release name if ID is missing
  lib/MusicBrainz/Server/Edit/Historic/MergeRelease.pm
Labels: Bug

#1414 MBS-10365 (V): Convert entity lists to react-table
  flow-typed/npm/react-table_v7.x.x.js
  root/components/RemoveFromMergeTableCell.js
  root/components/RemoveFromMergeTableHeader.js
  root/components/Table.js
  root/components/list/RecordingList.js
  root/utility/tableColumns.js
Labels: React

#1428 MBS-10365 (VI): Convert entity lists to react-table
  root/components/RemoveFromMergeTableHeader.js
  root/components/common-macros.tt
  root/components/list/ArtistList.js
Labels: React

#1427 MBS-10707: Actually remove discID if add edit is rejected
  lib/MusicBrainz/Server/Edit/Medium/AddDiscID.pm
Labels: Bug

#1432 MBS-10669: Clean and validate Metal Archives URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#1437 MBS-10724: Make list sorting options consistent
  lib/MusicBrainz/Server/Data/Artist.pm
  lib/MusicBrainz/Server/Data/Place.pm
  lib/MusicBrainz/Server/Data/ReleaseGroup.pm
  root/collection/CollectionIndex.js
  root/components/list/ArtistList.js
Labels: New feature

#1435 MBS-10722: Entity list regression fixes
  root/components/list/ArtistList.js
  root/components/list/EventList.js
  root/components/list/LabelList.js
  root/components/list/PlaceList.js
  root/components/list/RecordingList.js
  root/components/list/ReleaseGroupList.js
  root/components/list/ReleaseList.js
  root/components/list/WorkList.js
  root/utility/tableColumns.js
Labels: Regression/Beta

#1436 MBS-10723: Separate className for cell and header
  flow-typed/npm/react-table_v7.x.x.js
  root/components/Table.js
  root/components/list/RecordingList.js
  root/components/list/ReleaseGroupList.js
  root/components/list/ReleaseList.js
  root/utility/tableColumns.js
Labels: Regression/Beta
