Repository metabrainz/musicbrainz-server, pull requests merged in 2020-11, with the labels that each got.

#1770 Add flow types to utility/dates.js
  root/static/scripts/edit/utility/dates.js
  root/static/scripts/tests/utility.js
Labels: Refactoring

#1768 MBS-10664: Allow more tags in expand2react
  root/static/scripts/common/i18n/expand2react.js
Labels: Bug

#1636 MBS-11018: Convert Add Relationship Type edit to React
  lib/MusicBrainz/Server/Edit/Relationship/AddLinkType.pm
  root/edit/details/AddRelationshipType.js
  root/edit/details/add_relationship_type.tt
  root/edit/details/edit_relationship_type.tt
  root/relationship/linktype/RelationshipTypeIndex.js
  root/relationship/linktype/RelationshipTypePairTree.js
  root/relationship/linktype/form.tt
  root/server/components.js
Labels: React

#1771 MBS-11207: Avoid double-encoding DBI errors
  lib/MusicBrainz/Server/Connector.pm
Labels: Bug

#1775 MBS-11210: Allow more subpaths for saisaibatake.ame-zaiku.com
  lib/MusicBrainz/Server/Data/URL.pm
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#1782 MBS-11188: Block odesli.co smart links
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#1794 MBS-11225: Autoselect IROMBOOK images
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#1793 MBS-11227: Ensure /release-group/merge also works
  lib/MusicBrainz/Server/Controller/ReleaseGroup.pm
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
Labels: Bug

#1781 MBS-11212: Serialize correct quality for JSON release
  lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Release.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/Collection.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseReleases.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/Collection.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupArtist.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRecording.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupArtist.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupNonCore.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRecording.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelationship.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/SubmitRecording.pm
  t/sql/webservice.sql
Labels: Bug

#1785 MBS-8438: Only return event once in find_by methods
  lib/MusicBrainz/Server/Data/Event.pm
Labels: Bug

#1766 MBS-1424: Add a "First release date" field to recordings
  .circleci/config.yml
  admin/sql/CreateFKConstraints.sql
  admin/sql/CreateFunctions.sql
  admin/sql/CreateIndexes.sql
  admin/sql/CreatePrimaryKeys.sql
  admin/sql/CreateTables.sql
  admin/sql/CreateViews.sql
  admin/sql/DropFKConstraints.sql
  admin/sql/DropFunctions.sql
  admin/sql/DropIndexes.sql
  admin/sql/DropPrimaryKeys.sql
  admin/sql/DropTables.sql
  admin/sql/DropViews.sql
  admin/sql/TruncateTables.sql
  admin/sql/updates/20201028-mbs-1424-fks.sql
  admin/sql/updates/20201028-mbs-1424.sql
  docker/Dockerfile.tests
  docker/musicbrainz-tests/DBDefs.pm
  docker/templates/DBDefs.pm.ctmpl
  lib/DBDefs/Default.pm
  lib/MusicBrainz/Server/Controller/Recording.pm
  lib/MusicBrainz/Server/Controller/WS/2/Recording.pm
  lib/MusicBrainz/Server/Data/Recording.pm
  lib/MusicBrainz/Server/Entity/Recording.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Recording.pm
  lib/MusicBrainz/Server/WebService/XMLSerializer.pm
  root/layout/components/sidebar/RecordingSidebar.js
  root/types.js
  script/dbdefs_to_js.pl
  t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseRecordings.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseRecordings.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRecording.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupNonCore.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRecording.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelationship.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupTagsRatings.pm
  t/sql/standalone_recording.sql
  upgrade.json
Labels: New feature

#1778 Store name in EditLinkType attributes
  lib/MusicBrainz/Server/Controller/Relationship/LinkType.pm
  lib/MusicBrainz/Server/Edit/Relationship/EditLinkType.pm
Labels: QoL

#1792 MBS-11223 / MBS-11224: Relationship editor fixes for missing tracklists / media
  root/release/edit_relationships.tt
  root/static/scripts/relationship-editor/release.js
Labels: Bug

#1784 MBS-11169 / MBS-11214: Fixes for bottom rel credits for mediums
  lib/MusicBrainz/Server/Entity/Medium.pm
  root/components/medium.tt
Labels: Bug

#1802 Use SameSite=Lax for login cookies (fixes MBS-11238)
  lib/MusicBrainz/Server.pm
  lib/MusicBrainz/Server/Controller/CDStub.pm
  lib/MusicBrainz/Server/Controller/Rating.pm
  lib/MusicBrainz/Server/Controller/Role/Merge.pm
  lib/MusicBrainz/Server/Controller/Root.pm
  lib/MusicBrainz/Server/Controller/User.pm
  root/layout/components/MergeHelper.js
Labels: Bug, Regression/Beta
