Repository metabrainz/musicbrainz-server, pull requests merged in 2020-09, with the labels that each got.

#1602 MBS-10972: Convert Add Instrument edit to React
  lib/MusicBrainz/Server/Edit/Instrument/Create.pm
  root/edit/components/IntentionallyUntranslatedIcon.js
  root/edit/details/AddInstrument.js
  root/edit/details/add_instrument.tt
  root/server/components.js
  root/static/scripts/edit/components/InformationIcon.js
  root/static/styles/layout.less
Labels: React

#1647 MBS-11032: Convert Add medium edit to React
  lib/MusicBrainz/Server/Edit/Medium/Create.pm
  root/components/common-macros.tt
  root/edit/details/AddMedium.js
  root/edit/details/add_medium.tt
  root/edit/details/macros.tt
  root/medium/MediumTracklist.js
  root/medium/tracklist.tt
  root/server/components.js
  root/static/scripts/common/components/DataTrackIcon.js
Labels: React

#1652 Support GET requests in ssssss.psgi
  contrib/ssssss.psgi
Labels: New feature

#1631 MBS-11014: Add context to DuplicateViolation on rels editor
  lib/MusicBrainz/Server/Edit/Relationship/Edit.pm
Labels: QoL

#1655 MBS-11043: Add offiziellecharts.de to the otherdbs whitelist
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/OffizielleCharts.pm
  root/static/images/favicons/offiziellecharts-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature

#1654 MBS-11041: Make ModBot leave a note on autoremoval edits
  lib/MusicBrainz/Script/RemoveEmpty.pm
Labels: QoL

#1656 MBS-11039: Don't use entity id as key for seriesItemNumbers
  lib/MusicBrainz/Server/Controller/Series.pm
  root/types.js
  root/utility/tableColumns.js
Labels: Bug

#1592 MBS-10941: Rename XML Web Service into "MusicBrainz API"
  admin/DumpJSON
  admin/nginx/mbserver-rewrites.conf
  lib/MusicBrainz/Server/Release.pm
  lib/MusicBrainz/Server/WebService/Validator.pm
  root/account/applications/Index.js
  root/entity/Details.js
  root/layout/components/BottomMenu.js
Labels: QoL

#1651 MBS-7409: Make "cannot attach discid" more obvious
  root/cdtoc/attach_list.tt
  root/static/styles/layout.less
Labels: QoL

#1649 MBS-11034: Convert Remove medium edit to React
  lib/MusicBrainz/Server/Edit/Medium/Delete.pm
  root/edit/details/RemoveMedium.js
  root/edit/details/remove_medium.tt
  root/server/components.js
Labels: React

#1627 MBS-11000: Avoid "Edit release group" edit ISE when comment is null
  root/edit/details/EditReleaseGroup.js
Labels: Regression/Beta

#1666 MBS-11052: Convert Edit Relationship Attribute edit to React
  lib/MusicBrainz/Server/Edit/Relationship/EditLinkAttribute.pm
  root/edit/details/AddRelationshipAttribute.js
  root/edit/details/EditRelationshipAttribute.js
  root/edit/details/edit_relationship_attribute.tt
  root/server/components.js
  root/static/scripts/edit/components/edit/Diff.js
  root/static/scripts/edit/components/edit/WordDiff.js
Labels: React

#1678 Fix unspecified RG type
  root/components/list/ReleaseGroupList.js
Labels: Regression/Beta

#1684 MBS-11077: Update sort parameter for load_display_reviews
  lib/MusicBrainz/Server/Data/CritiqueBrainz.pm
Labels: Bug

#1686 Add missing N_l import
  lib/MusicBrainz/Script/RemoveEmpty.pm
Labels: Regression/Beta

#1685 MBS-11078 / MBS-11081: Fix pregap bugs in Add medium
  root/components/common-macros.tt
  root/edit/details/AddMedium.js
  root/medium/MediumTracklist.js
  root/medium/tracklist.tt
  root/static/scripts/common/components/PregapTrackIcon.js
Labels: Regression/Beta

#1687 MBS-11085 / MBS-11089: Fix canHaveDiscID check / Fix missing favicons
  root/layout/components/ExternalLinks.js
  root/static/scripts/release-editor/fields.js
Labels: Regression/Beta

#1691 MBS-11069: Fix diff highlighting of white spaces
  root/static/styles/layout.less
Labels: Bug

#1675 MBS-11061: Disallow MusicBrainz URLs in relationships
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#1689 MBS-11086: Add icon for tabs with errors in release editor
  root/release/edit/editnote.tt
  root/static/styles/release-editor.less
Labels: QoL

#1694 Fix innocuous warnings caused by Edit release edit
  lib/MusicBrainz/Server/Edit/Release/Edit.pm
Labels: QoL

#1683 MBS-10880: Reset RGs in cache when first date changes
  lib/MusicBrainz/Server/Data/Release.pm
Labels: Bug

#1693 MBS-11098: Fix validating Big Cartel URL for label
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug

#1674 MBS-11062: Link basic how-tos from the front page
  root/main/index.js
Labels: QoL

#1679 MBS-10835: Don't send verification mail if address in use
  lib/MusicBrainz/Server/Controller/Account.pm
  lib/MusicBrainz/Server/Data/Editor.pm
  lib/MusicBrainz/Server/Email.pm
Labels: New feature

#1695 MBS-11101: Fix series not using seriesOrderingFunc
  root/static/scripts/relationship-editor/generic.js
Labels: Regression/Beta

#1629 MBS-11109 / MBS-10961 / MBS-11001/ MBS-11007 / MBS-11008: Block more smart/short links
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#1680 MBS-11068: Block redirect links: page.link
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#1635 MBS-11017: Normalize IMSLP to HTTPS and add validation
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#1677 MBS-11065: Only block smart links if they have a path
  root/static/scripts/edit/externalLinks.js
Labels: Bug

#1387 MBS-7473: Allow specifying a release MBID when attaching a CD TOC
  lib/MusicBrainz/Server/Controller/CDTOC.pm
  root/cdtoc/attach_filter_release.tt
  root/cdtoc/attach_list.tt
  root/cdtoc/lookup.tt
Labels: New feature

#1668 Autocomplete2 improvements
  lib/MusicBrainz/Server/Controller/WS/js/Work.pm
  root/static/scripts/common/MB/Control/Autocomplete.js
  root/static/scripts/common/components/Autocomplete2.js
  root/static/scripts/common/components/Autocomplete2/actions.js
  root/static/scripts/common/components/Autocomplete2/constants.js
  root/static/scripts/common/components/Autocomplete2/formatters.js
  root/static/scripts/common/components/Autocomplete2/reducer.js
  root/static/scripts/common/components/Autocomplete2/types.js
  root/static/scripts/common/constants.js
  root/static/scripts/common/hooks/useOutsideClickEffect.js
  root/static/scripts/tests/autocomplete2.js
  root/static/styles/autocomplete2.less
  root/types.js
Labels: Refactoring

#1581 MBS-10921: Drop wrongly listed edits from history
  admin/sql/updates/20200921-mbs-10921-unlist-unrelated-edits.sql
Labels: Regression/Beta

#1707 MBS-11033: Update the Apple Music logo
  root/static/images/favicons/applemusic-32.png
Labels: New feature

#1713 MBS-3116: Warn when merging works with different ISWCs
  lib/MusicBrainz/Server/Controller/Recording.pm
  lib/MusicBrainz/Server/Controller/Role/Merge.pm
  lib/MusicBrainz/Server/Controller/Work.pm
  root/work/WorkMerge.js
  t/lib/t/MusicBrainz/Server/Data/ISWC.pm
Labels: QoL

#1716 MBS-6322: Add report for releases with same barcodes in diff RGs
  lib/MusicBrainz/Server/Report/ReleasesSameBarcode.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/ReleasesSameBarcode.js
  root/report/ReportsIndex.js
  root/server/components.js
Labels: New feature

#1714 MBS-4118: Add full-icu to Node for locale strings
  package.json
  script/start_renderer.pl
  yarn.lock
Labels: Bug

#1710 MBS-11121: Normalize Apple Music beta links
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#1596 MBS-10956: Load ratings everywhere we also load user ratings
  lib/MusicBrainz/Server/Controller/Area.pm
  lib/MusicBrainz/Server/Controller/Artist.pm
  lib/MusicBrainz/Server/Controller/Collection.pm
  lib/MusicBrainz/Server/Controller/Series.pm
Labels: Bug

#1711 MBS-8650: Lower how long an IPI must be to 5
  lib/MusicBrainz/Server/Validation.pm
  t/lib/t/MusicBrainz/Server/Validation.pm
Labels: QoL

#1617 MBS-10991: Convert user/subscriptions pages to React
  lib/MusicBrainz/Server/Controller/User/Subscriptions.pm
  lib/MusicBrainz/Server/Controller/User/SubscriptionsRole.pm
  root/server/components.js
  root/user/UserSubscriptions.js
  root/user/subscriptions/artist.tt
  root/user/subscriptions/collection.tt
  root/user/subscriptions/editor.tt
  root/user/subscriptions/label.tt
  root/user/subscriptions/layout.tt
  root/user/subscriptions/menu.tt
  root/user/subscriptions/series.tt
  root/user/subscriptions/subscriptions.tt
  root/user/subscriptions/table.tt
Labels: React

#1712 MBS-11114: Allow track times to be unset
  root/static/scripts/release-editor/fields.js
  t/selenium.js
  t/selenium/release-editor/MBS-11114.html
Labels: Bug, Regression/Beta

#1705 MBS-11094: Don't block editing on pre-existing too early format
  root/release/edit/tracklist.tt
  root/static/scripts/release-editor/fields.js
Labels: Bug

#1696 Enforce ESLint rules followed so far
  .circleci/config.yml
  .eslintrc.unfixed.yaml
  .eslintrc.yaml
  script/check_unfixed_eslint_rules
  script/xgettext.js
Labels: Refactoring

#1703 MBS-11104: Always show credits in RelationshipsTable
  root/area/AreaRecordings.js
  root/area/AreaReleases.js
  root/area/AreaWorks.js
  root/artist/ArtistRelationships.js
  root/components/RelationshipsTable.js
Labels: QoL

#1720 MBS-11137: Show info on hover on frontpage's new releases
  root/components/Artwork.js
  root/main/index.js
Labels: QoL

#1719 MBS-11136: Support HTML in admin/attribute descriptions
  root/admin/attributes/Attribute.js
Labels: QoL

#1704 MBS-11036: Don't show Add release button when moving CD TOC
  lib/MusicBrainz/Server/Controller/CDTOC.pm
  root/cdtoc/attach_filter_release.tt
Labels: Bug

#1715 MBS-11127: Use cardinality for work-level-rels in WS/2
  lib/MusicBrainz/Server/ControllerBase/WS/2.pm
  lib/MusicBrainz/Server/Data/Relationship.pm
Labels: QoL

#1702 MBS-11107: Support nameVariation for other entity types
  root/static/scripts/common/components/EntityLink.js
Labels: QoL
