Repository metabrainz/musicbrainz-server, pull requests merged in 2020-04, with the labels that each got.

#1408 MBS-10679 / MBS-10680: WS detail tab improvements
  root/entity/Details.js
Labels: New feature

#1157 MBS-5641: Show language/script in relevant reports
  lib/MusicBrainz/Server/Report/NoLanguage.pm
  lib/MusicBrainz/Server/Report/NoScript.pm
  lib/MusicBrainz/Server/Report/ReleasesWithUnlikelyLanguageScript.pm
  root/report/NoLanguage.js
  root/report/NoScript.js
  root/report/ReleasesWithUnlikelyLanguageScript.js
  root/report/components/ReleaseList.js
Labels: QoL

#1450 MBS-9894: Fix timeline month off by 1
  root/static/scripts/timeline.js
Labels: Bug

#1452 MBS-10747: Fix misleading open edit message
  root/utility/edit.js
Labels: QoL

#1446 MBS-10735: Stop highlighting CD Baby links
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/CDBaby.pm
  root/static/images/favicons/cdbaby-16.png
  root/static/scripts/common/constants.js
  root/static/styles/favicons.less
  t/lib/t/TemplateMacros.pm
Labels: QoL

#1159 MBS-10753: Use artist sort names for artist collection ordering
  lib/MusicBrainz/Server/Data/Artist.pm
Labels: QoL

#1454 MBS-10640: Fix donation check
  lib/MusicBrainz/Server/Controller/Account.pm
  lib/MusicBrainz/Server/Data/Editor.pm
Labels: Bug

#1458 MBS-10756: Remove link_order from rels sort
  lib/MusicBrainz/Server/Data/Relationship.pm
Labels: Bug

#1449 MBS-10742: Show right number of hidden events
  root/static/scripts/common/components/ReleaseEvents.js
  root/static/scripts/common/components/WorkArtists.js
Labels: Bug

#1457 MBS-10755: Validate Musik-Sammler.de URL rels
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#1451 MBS-10740: Convert /relationship static pages to React
  lib/MusicBrainz/Server/Controller/Relationship/LinkAttributeType.pm
  lib/MusicBrainz/Server/Controller/Relationship/LinkType.pm
  lib/MusicBrainz/Server/Entity/LinkAttributeType.pm
  lib/MusicBrainz/Server/Entity/LinkType.pm
  lib/MusicBrainz/Server/Form/Utils.pm
  root/components/UserAccountTabs.js
  root/components/common-macros.tt
  root/relationship/RelationshipsHeader.js
  root/relationship/header.tt
  root/relationship/linkattributetype/RelationshipAttributeTypeInUse.js
  root/relationship/linkattributetype/RelationshipAttributeTypesIndex.js
  root/relationship/linkattributetype/common.tt
  root/relationship/linkattributetype/in_use.tt
  root/relationship/linkattributetype/index.tt
  root/relationship/linktype/RelationshipTypeInUse.js
  root/relationship/linktype/RelationshipTypePairTree.js
  root/relationship/linktype/RelationshipTypesIndex.js
  root/relationship/linktype/in_use.tt
  root/relationship/linktype/index.tt
  root/relationship/linktype/tree.tt
  root/relationship/utility/compareChildren.js
  root/server/components.js
  root/static/scripts/common/components/Cardinality.js
  root/types.js
  root/utility/buildTab.js
Labels: React

#1456 MBS-10719 / MBS-10751: Convert Remove PUID edit to React and fix some of them not loading
  lib/MusicBrainz/Server/Edit/PUID/Delete.pm
  root/edit/details/historic/RemovePuid.js
  root/edit/details/historic/remove_puid.tt
  root/server/components.js
Labels: Bug, React

#1415 MBS-10677: Return entity types for WS entities in rels and ACs
  lib/MusicBrainz/Server/Controller/WS/2/Recording.pm
  lib/MusicBrainz/Server/Controller/WS/2/Release.pm
  lib/MusicBrainz/Server/Controller/WS/2/ReleaseGroup.pm
  lib/MusicBrainz/Server/ControllerBase/WS/2.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Utils.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseReleaseGroup.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseLabels.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseReleaseGroups.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseReleases.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/Collection.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupArtist.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupLabel.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupPlace.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRecording.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupReleaseGroup.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupSeries.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupURL.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupArtist.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupNonCore.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRecording.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelationship.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupReleaseGroup.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupURL.pm
  t/script/DumpJSON.t
Labels: Bug

#1423 MBS-10391 Convert Add Release Group edit to React
  lib/MusicBrainz/Server/Edit/ReleaseGroup/Create.pm
  root/edit/details/AddReleaseGroup.js
  root/edit/details/add_release_group.tt
  root/server/components.js
Labels: React

#1115 MBS-1921: Display edit link under annotations
  root/static/scripts/common/components/Annotation.js
Labels: QoL

#1472 Fix a warning from /release-group/ overview page in server logs
  root/release_group/ReleaseGroupIndex.js
Labels: Bug

#1466 MBS-9086: Move most relationships away from area overview
  entities.json
  lib/MusicBrainz/Server/Controller/Area.pm
  root/area/AreaRecordings.js
  root/area/AreaReleases.js
  root/area/AreaWorks.js
  root/components/RelationshipsTable.js
  root/server/components.js
  root/utility/generateRelationshipAppearancesList.js
Labels: New feature

#1468 MBS-10772: Show top 5 genres and other tags on sidebar
  lib/MusicBrainz/Server/Data/EntityTag.pm
Labels: Bug

#1473 Upgrade a bunch of JavaScript packages
  package.json
  webpack.client.config.js
  yarn.lock
Labels: Refactoring

#1477 MBS-10783: Beta: Links in edit listings go to /
  cpanfile
  cpanfile.snapshot
Labels: Regression/Beta

#1424 MBS-10400 Convert Edit Release Group edit to React
  lib/MusicBrainz/Server/Edit/ReleaseGroup/Edit.pm
  root/edit/details/EditReleaseGroup.js
  root/edit/details/edit_release_group.tt
  root/server/components.js
Labels: React

#1455 MBS-10748: Convert relationship type page to React
  lib/MusicBrainz/Server/Controller/Doc.pm
  lib/MusicBrainz/Server/Controller/Relationship/LinkType.pm
  lib/MusicBrainz/Server/Edit/Historic/Relationship.pm
  lib/MusicBrainz/Server/Entity/LinkType.pm
  root/components/common-macros.tt
  root/doc/relationship_type.tt
  root/entity/NotFound.js
  root/relationship/RelationshipsHeader.js
  root/relationship/linktype/RelationshipTypeIndex.js
  root/relationship/linktype/RelationshipTypesList.js
  root/server/components.js
  root/static/scripts/common/components/OrderableDirection.js
  root/static/scripts/common/components/Relationship.js
  root/static/scripts/edit/utility/linkPhrase.js
  root/types.js
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
Labels: React

#1460 MBS-10761: Disallow YouTube links at wrong levels
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#1486 MBS-10641: Fix link to open edits for subcriptions
  lib/MusicBrainz/Server/Email/Subscriptions.pm
Labels: QoL

#1461 MBS-9910: Convert WikiDoc transclusion admin pages to React
  lib/MusicBrainz/Server/Controller/Admin/WikiDoc.pm
  lib/MusicBrainz/Server/Data/WikiDocIndex.pm
  root/admin/wikidoc/CreateWikiDoc.js
  root/admin/wikidoc/DeleteWikiDoc.js
  root/admin/wikidoc/EditWikiDoc.js
  root/admin/wikidoc/WikiDocIndex.js
  root/admin/wikidoc/edit.tt
  root/admin/wikidoc/index.tt
  root/admin/wikidoc/types.js
  root/components/FormSubmit.js
  root/server/components.js
  root/static/wikidocs/.gitignore
Labels: React

#1459 MBS-10760: Convert Remove track edit to React
  lib/MusicBrainz/Server/Edit/Historic/RemoveTrack.pm
  root/edit/components/HistoricReleaseList.js
  root/edit/details/historic/RemoveTrack.js
  root/edit/details/historic/remove_track.tt
  root/server/components.js
Labels: React

#1462 MBS-10762: Convert historic Remove Release/Releases edits to React
  lib/MusicBrainz/Server/Edit/Historic/RemoveRelease.pm
  lib/MusicBrainz/Server/Edit/Historic/RemoveReleases.pm
  root/edit/details/historic/RemoveRelease.js
  root/edit/details/historic/RemoveReleases.js
  root/edit/details/historic/remove_release.tt
  root/edit/details/historic/remove_releases.tt
  root/server/components.js
Labels: React
