Repository metabrainz/musicbrainz-server, pull requests merged in 2021-08, with the labels that each got.

#2189 Autocomplete2 editor fixes
  root/static/scripts/common/components/Autocomplete2.js
  root/static/scripts/common/components/Autocomplete2/reducer.js
  root/static/scripts/tests/autocomplete2.js
Labels: Bug

#2188 MBS-11808: Don't show tags in lists where vote count < 1
  lib/MusicBrainz/Server/Data/EntityTag.pm
Labels: QoL

#2176 MBS-11796: Add Internet Archive logo for sidebar
  root/static/images/external-favicons/archive-32.png
  root/static/scripts/common/constants.js
  root/static/styles/favicons.less
Labels: QoL

#2186 MBS-11806: Don't group relationships for different track sets
  root/utility/groupRelationships.js
Labels: Bug

#2178 MBS-11793: Don't fetch Wikipedia abstract when URL is ended
  lib/MusicBrainz/Server/Controller/Role/WikipediaExtract.pm
Labels: Bug

#2181 MBS-11802: Add mock LinkType for examples
  lib/MusicBrainz/Server/Edit/Relationship/EditLinkType.pm
Labels: Bug

#2182 MBS-11805 (I): Flow types and refactoring for guess case code (first half)
  root/static/scripts/edit/components/GuessCaseOptions.js
  root/static/scripts/edit/components/GuessCaseOptionsPopover.js
  root/static/scripts/guess-case/MB/Control/GuessCase.js
  root/static/scripts/guess-case/MB/GuessCase/Handler/Area.js
  root/static/scripts/guess-case/MB/GuessCase/Handler/Artist.js
  root/static/scripts/guess-case/MB/GuessCase/Handler/Base.js
  root/static/scripts/guess-case/MB/GuessCase/Handler/Label.js
  root/static/scripts/guess-case/MB/GuessCase/Handler/Place.js
  root/static/scripts/guess-case/MB/GuessCase/Handler/Release.js
  root/static/scripts/guess-case/MB/GuessCase/Handler/Track.js
  root/static/scripts/guess-case/MB/GuessCase/Handler/Work.js
  root/static/scripts/guess-case/MB/GuessCase/Input.js
  root/static/scripts/guess-case/MB/GuessCase/Main.js
  root/static/scripts/guess-case/MB/GuessCase/Output.js
  root/static/scripts/guess-case/flags.js
  root/static/scripts/guess-case/modes.js
  root/static/scripts/guess-case/types.js
  root/static/scripts/guess-case/utils.js
  root/static/scripts/tests/GuessCase.js
Labels: Refactoring

#2179 MBS-11798: Disallow Instagram internal links
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2152 MBS-11732 / MBS-11733: Remove LYRICSnMUSIC / WikiaParoles from lyrics whitelist
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/LyricsNMusic.pm
  lib/MusicBrainz/Server/Entity/URL/WikiaParoles.pm
  root/static/images/external-favicons/lyricsnmusic-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
  t/sql/the-beatles.sql
Labels: QoL

#1821 MBS-11267: Always show artwork info when adding/reordering
  lib/MusicBrainz/Server/Controller/Release.pm
  root/release/add_cover_art.tt
  root/release/reorder_cover_art.tt
Labels: QoL

#2205 MBS-11861: improve loopParity classes for tablesorter
  root/static/scripts/statistics.js
Labels: Bug

#2204 MBS-2221: Add date docs to relationship editor
  root/components/relationship-editor.tt
  root/static/scripts/relationship-editor/common/dialog.js
Labels: QoL

#2208 Remove reporter id from report message-id
  lib/MusicBrainz/Server/Email.pm
Labels: Bug

#2203 MBS-11825: Use same order for art types when editing vs adding
  lib/MusicBrainz/Server/Entity/CoverArtType.pm
Labels: QoL

#2175 MBS-11788 / MBS-11797: Guess case: Lowercase more words in ETI
  root/static/scripts/guess-case/utils.js
  root/static/scripts/tests/GuessCase.js
Labels: QoL

#2206 MBS-11862: Do not show deprecated relationship types with 0 uses
  lib/MusicBrainz/Server/Controller/Edit.pm
  lib/MusicBrainz/Server/Controller/Relationship/LinkType.pm
  lib/MusicBrainz/Server/Data/LinkType.pm
Labels: QoL

#2202 MBS-11856: Remove reports for releases with cover art relationships
  lib/MusicBrainz/Server/Report/CoverArtRelationships.pm
  lib/MusicBrainz/Server/Report/ReleasesInCAAWithCoverArtRelationships.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/CoverArtRelationships.js
  root/report/ReleasesInCaaWithCoverArtRelationships.js
  root/report/ReportsIndex.js
  root/server/components.js
Labels: QoL

#2196 MBS-11850: Make footer links more visible
  root/layout.tt
  root/layout/components/Footer.js
  root/static/styles/layout.less
Labels: QoL

#2211 Fix deprecated link type tests
  lib/MusicBrainz/Server/Data/LinkType.pm
  t/selenium/External_Links_Editor.json5
  t/sql/selenium.sql
Labels: Regression/Beta

#2194 MBS-7859: Hide irrelevant recording rels from release view
  root/components/GroupedTrackRelationships.js
  root/static/scripts/release/components/TracklistAndCredits.js
Labels: QoL

#2197 MBS-11848: Add report for releases with Amazon cover art without CAA cover
  lib/MusicBrainz/Server/Report/ReleasesWithAmazonCoverArt.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/ReleasesWithAmazonCoverArt.js
  root/report/ReportsIndex.js
  root/server/components.js
Labels: New feature

#2126 MBS-11693: Give useful message when rejecting Musixmatch /album links
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2191 MBS-11832: Add missing NotFound params for artist_credit
  root/entity/NotFound.js
Labels: Bug

#2185 MBS-11810 / MBS-11812: Small changes to release merge page
  root/release/merge.tt
Labels: QoL, Bug

#2207 MBS-11864 / MBS-11863: Fix overstrict DNB cleanup / Allow DNB links for works
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug, New feature

#2187 MBS-11811: Do not batch-change track data for collapsed media
  root/release/edit/tracklist.tt
  root/static/scripts/release-editor/actions.js
  root/static/scripts/release-editor/bindingHandlers.js
Labels: QoL

#2174 MBS-11689: Report for pseudo-releases marked as the original tracklist
  lib/MusicBrainz/Server/Report/MislinkedPseudoReleases.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/MislinkedPseudoReleases.js
  root/report/ReportsIndex.js
  root/server/components.js
Labels: New feature

#2192 MBS-11824 / MBS-11833: Featured reports regex improvements
  lib/MusicBrainz/Server/Report/FeaturingRecordings.pm
  lib/MusicBrainz/Server/Report/FeaturingReleaseGroups.pm
  lib/MusicBrainz/Server/Report/FeaturingReleases.pm
Labels: QoL

#2145 MBS-11722: Don't preselect basic as language proficiency
  lib/MusicBrainz/Server/Form/Role/UserProfile.pm
  root/static/scripts/account/components/EditProfileForm.js
Labels: QoL

#2190 MBS-11828 / MBS-9426: UI to find and unlock locked usernames
  lib/MusicBrainz/Server/Controller/Admin.pm
  lib/MusicBrainz/Server/Data/Editor.pm
  lib/MusicBrainz/Server/Form/Admin/LockedUsernameSearch.pm
  root/admin/LockedUsernameSearch.js
  root/admin/LockedUsernameUnlock.js
  root/layout/components/TopMenu.js
  root/server/components.js
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
Labels: New feature

#2209 MBS-11836: Convert Edit Barcodes edit to React
  lib/MusicBrainz/Server/Edit/Release/EditBarcodes.pm
  root/edit/details/EditBarcodes.js
  root/edit/details/edit_barcodes.tt
  root/server/components.js
Labels: React

#2212 MBS-11837: Convert Edit Release Label edit to React
  lib/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm
  root/edit/details/EditReleaseLabel.js
  root/edit/details/edit_release_label.tt
  root/server/components.js
  t/lib/t/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm
Labels: React

#2214 MBS-11823: Don't break tags and genres mid-word
  root/static/styles/layout.less
Labels: QoL

#2221 MBS-11839: Convert Remove Relationship Attribute edit to React
  lib/MusicBrainz/Server/Edit/Relationship/RemoveLinkAttribute.pm
  root/edit/details/AddRelationshipType.js
  root/edit/details/RemoveRelationshipAttribute.js
  root/edit/details/RemoveRelationshipType.js
  root/edit/details/remove_relationship_attribute.tt
  root/server/components.js
Labels: React

#2201 MBS-11846: Display release artist on release group view
  lib/MusicBrainz/Server/Controller/ReleaseGroup.pm
  root/release_group/ReleaseGroupIndex.js
Labels: QoL

#2224 MBS-11875: Don't consider Braille an unlikely script
  lib/MusicBrainz/Server/Report/ReleasesWithUnlikelyLanguageScript.pm
Labels: QoL

#2086 MBS-11622: Clean up Apple Music label URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2096 MBS-11650: Add tag and rating statistics to profile page
  lib/MusicBrainz/Server/Controller/User.pm
  lib/MusicBrainz/Server/Data/Editor.pm
  root/user/UserProfile.js
Labels: New feature

#2225 MBS-11834: Convert Add Release edit to React
  lib/MusicBrainz/Server/Edit/Release/Create.pm
  root/edit/details/AddRelease.js
  root/edit/details/AddReleaseGroup.js
  root/edit/details/EditReleaseGroup.js
  root/edit/details/add_release.tt
  root/server/components.js
Labels: React

#2222 MBS-11835: Convert Change Wikidoc edit to React
  lib/MusicBrainz/Server/Edit/WikiDoc/Change.pm
  root/edit/details/ChangeWikiDoc.js
  root/edit/details/change_wikidoc.tt
  root/server/components.js
Labels: React

#1613 MBS-10910: Display renamed from/into on label overview
  lib/MusicBrainz/Server/Constants.pm
  lib/MusicBrainz/Server/Controller/Label.pm
  root/artist/ArtistIndex.js
  root/components/RelatedEntitiesDisplay.js
  root/label/LabelIndex.js
Labels: New feature

#1832 MBS-2421: Show entity icon on relationship links
  root/components/GroupedTrackRelationships.js
  root/components/RelatedSeries.js
  root/components/RelatedWorks.js
  root/components/RelationshipTargetLinks.js
  root/components/RelationshipsTable.js
  root/static/images/entity/area-inverted.png
  root/static/images/entity/area-inverted.svg
  root/static/images/entity/artist-inverted.png
  root/static/images/entity/artist-inverted.svg
  root/static/images/entity/character-inverted.png
  root/static/images/entity/character-inverted.svg
  root/static/images/entity/choir-inverted.png
  root/static/images/entity/choir-inverted.svg
  root/static/images/entity/event-inverted.png
  root/static/images/entity/event-inverted.svg
  root/static/images/entity/group-inverted.png
  root/static/images/entity/group-inverted.svg
  root/static/images/entity/instrument-inverted.png
  root/static/images/entity/instrument-inverted.svg
  root/static/images/entity/label-inverted.png
  root/static/images/entity/label-inverted.svg
  root/static/images/entity/orchestra-inverted.png
  root/static/images/entity/orchestra-inverted.svg
  root/static/images/entity/person-inverted.png
  root/static/images/entity/person-inverted.svg
  root/static/images/entity/place-inverted.png
  root/static/images/entity/place-inverted.svg
  root/static/images/entity/recording-inverted.png
  root/static/images/entity/recording-inverted.svg
  root/static/images/entity/release-inverted.png
  root/static/images/entity/release-inverted.svg
  root/static/images/entity/release_group-inverted.png
  root/static/images/entity/release_group-inverted.svg
  root/static/images/entity/series-inverted.png
  root/static/images/entity/series-inverted.svg
  root/static/images/entity/work-inverted.png
  root/static/images/entity/work-inverted.svg
  root/static/scripts/common/components/AreaWithContainmentLink.js
  root/static/scripts/common/components/DescriptiveLink.js
  root/static/scripts/common/components/EntityLink.js
  root/static/styles/entity-icons.less
Labels: QoL

#2219 MBS-3774: Add URL with begin and end dates
  root/static/scripts/alias/AliasEditForm.js
  root/static/scripts/edit/MB/edit.js
  root/static/scripts/edit/components/DateRangeFieldset.js
  root/static/scripts/edit/components/ExternalLinkAttributeDialog.js
  root/static/scripts/edit/externalLinks.js
  root/static/scripts/edit/utility/copyFieldData.js
  root/static/styles/forms.less
  t/selenium/External_Links_Editor.json5
Labels: New feature

#2226 MBS-11840: Convert Reorder Mediums edit to React
  lib/MusicBrainz/Server/Edit/Release/ReorderMediums.pm
  root/edit/details/ReorderMediums.js
  root/edit/details/reorder_mediums.tt
  root/server/components.js
Labels: React

#2240 Remove useless arrows on add_cover_art images
  root/release/add_cover_art.tt
Labels: Regression/Beta

#2241 Improvements to Edit Release Label edits
  lib/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm
  root/edit/details/EditReleaseLabel.js
Labels: Regression/Beta

#2242 MBS-11924: Hide useless tabs / subscribers section from deleted profiles
  root/components/UserAccountTabs.js
  root/user/UserProfile.js
Labels: QoL

#2243 MBS-11922: Show historical (now secondary) types for old Add Release edits
  lib/MusicBrainz/Server/Edit/Historic/AddRelease.pm
  root/edit/details/historic/AddRelease.js
Labels: QoL, Bug
