Repository metabrainz/musicbrainz-server, pull requests merged in 2021-03, with the labels that each got.

#1936 MBS-11408: Clarify Edit Note Author edit search options
  root/edit/search_macros.tt
Labels: QoL

#1933 MBS-11405: Don't show ended URL rels in DeprecatedRelationship reports
  lib/MusicBrainz/Server/Report/DeprecatedRelationshipReport.pm
Labels: QoL

#1931 MBS-10076 / MBS-11403: Friendlier error when deleting attribute that has children
  lib/MusicBrainz/Server/Controller/Admin/Attributes.pm
  lib/MusicBrainz/Server/Data/Role/Attribute.pm
  root/admin/attributes/CannotRemoveAttribute.js
  root/admin/attributes/in_use.tt
  root/server/components.js
Labels: QoL

#1928 MBS-11402: Block smart links: many.link
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#1938 MBS-9987: JSON-LD: Use "Concept URI" for Wikidata
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Role/SameAs.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Show.pm
Labels: QoL

#1942 MBS-9866: Add bubbles explaining what IPI and ISNI are on add forms
  root/artist/edit_form.tt
  root/components/forms.tt
  root/label/edit_form.tt
Labels: QoL

#1954 MBS-8232: Support more Unicode quotation marks in guess case
  root/static/scripts/guess-case/MB/GuessCase/Handler/Base.js
  root/static/scripts/guess-case/MB/GuessCase/Input.js
  root/static/scripts/tests/GuessCase.js
Labels: Bug

#1939 MBS-9884: Use "Created" for character-type artist begin dates
  root/artist/utils.js
Labels: QoL

#1934 MBS-11407: Make Controller->error use React errors
  lib/MusicBrainz/Server/Controller.pm
Labels: Bug

#1951 MBS-9836: Guess Case: stop uppercasing "the" in artist names
  root/static/scripts/guess-case/MB/GuessCase/Handler/Artist.js
  root/static/scripts/tests/GuessCase.js
Labels: QoL

#1935 MBS-10012: Treat http and https version of link as same for adding
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#1962 MBS-11426: Use medium's position, not array position, to load it
  lib/MusicBrainz/Server/Controller/Release.pm
Labels: Bug

#1957 MBS-11422: Block smart links: gate.fm
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#1950 MBS-11419: Show YouTube Music links on the sidebar
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/YouTubeMusic.pm
  root/static/images/external-favicons/youtubemusic-32.png
  root/static/scripts/common/constants.js
  root/static/styles/favicons.less
Labels: New feature

#1941 MBS-9871: Display all useful series relationships in RelatedSeries
  root/components/RelatedSeries.js
  root/components/Relationships.js
Labels: QoL

#1960 MBS-11420: "Paste Credits" doesn't apply credited name
  root/static/scripts/common/components/Autocomplete.js
Labels: Bug

#1959 MBS-11424: Unbreak seeding multiple RG types
  root/components/PostParameters.js
Labels: Bug, Regression/Beta

#1972 MBS-11435: Don't modify data in build_display_data for EditReleaseLabel
  lib/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm
  root/edit/details/edit_release_label.tt
Labels: Regression/Beta

#1973 MBS-11436: Don't try to call method public on unblessed JSON
  lib/MusicBrainz/Server/Controller/User/Subscriptions.pm
  lib/MusicBrainz/Server/Controller/User/SubscriptionsRole.pm
Labels: Regression/Beta

#1974 MBS-11437: Beta: work-level rels not shown on release pages
  lib/MusicBrainz/Server/Entity/Role/Linkable.pm
Labels: Regression/Beta

#1911 MBS-11384 / MBS-11385: Ensure all country context names are translated
  lib/MusicBrainz/Server/Entity/Area.pm
  root/static/scripts/common/entity.js
  root/static/scripts/common/i18n/localizeAreaName.js
Labels: Bug

#1978 MBS-11441: Beta: ISE on /account/applications
  lib/MusicBrainz/Server/Entity/EditorOAuthToken.pm
Labels: Regression/Beta

#1979 MBS-11444: Beta: Pass Label->new() call through to_json_object
  lib/MusicBrainz/Server/Edit/Label/Create.pm
Labels: Regression/Beta

#1986 MBS-11448: Pass Place->new() call through to_json_object
  lib/MusicBrainz/Server/Edit/Area/Create.pm
  lib/MusicBrainz/Server/Edit/Artist/Create.pm
  lib/MusicBrainz/Server/Edit/Event/Create.pm
  lib/MusicBrainz/Server/Edit/Instrument/Create.pm
  lib/MusicBrainz/Server/Edit/Place/Create.pm
  lib/MusicBrainz/Server/Edit/Recording/Create.pm
  lib/MusicBrainz/Server/Edit/Series/Create.pm
  lib/MusicBrainz/Server/Edit/Work/Create.pm
Labels: Regression/Beta

#1985 MBS-11447: Use to_json_object on language in Work::Create
  lib/MusicBrainz/Server/Edit/Work/Create.pm
Labels: Regression/Beta

#1982 MBS-11445: Fix 502 on auto-editor election pages
  lib/MusicBrainz/Server/Entity/AutoEditorElection.pm
Labels: Bug, Regression/Beta

#1987 MBS-11461: Add TO_JSON to ExampleRelationships
  lib/MusicBrainz/Server/Entity/ExampleRelationship.pm
  lib/MusicBrainz/Server/Entity/LinkType.pm
Labels: Regression/Beta

#1990 MBS-11470: Ensure to_json_object(type) does run in Area::Edit
  lib/MusicBrainz/Server/Edit/Area/Edit.pm
Labels: Regression/Beta

#1989 MBS-11468: ISE on "Edit cover art" edits
  lib/MusicBrainz/Server/Edit/Release/EditCoverArt.pm
Labels: Bug, Regression/Beta

#1999 MBS-11486: Load release info in NoLanguage before JSON conversion
  lib/MusicBrainz/Server/Report/NoLanguage.pm
Labels: Regression/Beta

#1997 MBS-11472: Do partition_by before converting attribute to JSON
  lib/MusicBrainz/Server/Edit/Work.pm
Labels: Regression/Beta

#2007 MBS-11508: Move Qobuz favicon to external-favicons
  root/static/images/external-favicons/qobuz-32.png
Labels: Bug

#2009 MBS-11503: Block smart links: trac.co
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#1998 MBS-11485: Allow irc(s):// links on expand2react
  root/static/scripts/common/i18n/expand2react.js
Labels: QoL

#1992 MBS-11454: Don't consider hasTooEarlyFormat a blocking error
  root/static/scripts/release-editor/fields.js
Labels: Bug

#1968 MBS-11432: Allow also linking places and works to Operabase
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#2010 MBS-10726: Use "medium", not "disc", as a generic term in RE buttons
  root/release/edit/layout.tt
  root/release/edit/tracklist.tt
  root/static/scripts/release-editor/actions.js
  root/static/scripts/release-editor/dialogs.js
  root/static/scripts/release-editor/init.js
  root/static/scripts/tests/release-editor/dialogs.js
  root/static/styles/release-editor.less
  t/selenium/Artist_Credit_Editor.json5
  t/selenium/release-editor/Duplicate_Selection.json5
  t/selenium/release-editor/MBS-11156.json5
  t/selenium/release-editor/The_Downward_Spiral.json5
Labels: QoL

#1971 MBS-11429: Don't error on existing but now blocked links
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#1112 MBS-1870 / MBS-8477 / MBS-10690 / MBS-10691: User tag page improvements
  lib/MusicBrainz/Server/Controller/User.pm
  lib/MusicBrainz/Server/Data/Editor.pm
  lib/MusicBrainz/Server/Data/EntityTag.pm
  root/components/TagEntitiesList.js
  root/components/tags.tt
  root/server/components.js
  root/static/scripts/common/components/TagLink.js
  root/static/styles/widgets.less
  root/tag/EntityList.js
  root/tag/TagIndex.js
  root/user/UserTag.js
  root/user/UserTagEntity.js
  root/user/UserTagList.js
  root/user/components/UserTagVoteSelection.js
  root/user/tag.tt
  root/user/tags.tt
  t/lib/t/MusicBrainz/Server/Controller/Tag.pm
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
  t/lib/t/MusicBrainz/Server/Controller/User/Tags.pm
Labels: React

#2011 MBS-11510: Stop overwriting titles in disableBecauseDiscIDs
  root/static/scripts/release-editor/bindingHandlers.js
Labels: Bug

#2013 MBS-9349: Add Pinterest links to the sidebar
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/Pinterest.pm
  root/static/images/external-favicons/pinterest-32.png
  root/static/scripts/common/constants.js
  root/static/styles/favicons.less
Labels: QoL

#1988 MBS-11452 / MBS-11462: Fixes to user tabs display
  lib/MusicBrainz/Server/Controller/User.pm
  root/components/UserAccountTabs.js
Labels: Bug

#1981 MBS-9543: Avoid false negative for string '0'
  lib/MusicBrainz/Server/Controller/ReleaseEditor.pm
  root/static/scripts/tests/release-editor/seeds/title_is_0.html
  t/selenium/release-editor/Seeding.json5
Labels: Bug

#2014 MBS-9310: Link to relationship type in Add Relationship Type edits
  entities.json
  lib/MusicBrainz/Server/Edit/Relationship/AddLinkType.pm
  root/edit/details/AddRelationshipType.js
  root/relationship/linktype/RelationshipTypeIndex.js
  root/relationship/linktype/RelationshipTypePairTree.js
  root/static/scripts/common/components/EntityLink.js
  root/static/scripts/common/utility/entityHref.js
Labels: QoL

#1991 MBS-11467: Use sort name to order lists of artists for tags
  lib/MusicBrainz/Server/Data/CoreEntity.pm
  lib/MusicBrainz/Server/Data/EntityTag.pm
Labels: QoL

#2000 MBS-11367: Disable browser autocomplete for tags when non-empty
  root/static/scripts/common/components/TagEditor.js
Labels: Bug

#1790 MBS-11222: Add a report for releases with media without a tracklist
  lib/MusicBrainz/Server/Report/ReleasesWithEmptyMediums.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/ReleasesWithEmptyMediums.js
  root/report/ReportsIndex.js
  root/server/components.js
Labels: New feature

#1983 MBS-11442: Adding tags on add-cover-art page disables submit
  root/release/add_cover_art.tt
  root/release/reorder_cover_art.tt
  root/static/scripts/edit.js
  root/static/scripts/relationship-editor/generic.js
  root/static/scripts/release/coverart.js
  webpack.client.config.js
Labels: Bug

#1994 MBS-11473: Don't try to filter open edits for user if logged out
  lib/MusicBrainz/Server/Controller/Edit.pm
  lib/MusicBrainz/Server/Data/Edit.pm
Labels: Bug

#1909 MBS-11386: Load area containment for indexed search
  lib/MusicBrainz/Server/Data/Area.pm
  lib/MusicBrainz/Server/Data/Search.pm
Labels: Bug

#1903 MBS-11373: Overwrite empty dates in relationship merges
  root/static/scripts/common/utility/isDateEmpty.js
  root/static/scripts/relationship-editor/common/fields.js
  root/static/scripts/tests/relationship-editor.js
Labels: Regression/Beta

#1995 MBS-11476: Don't show own open edits in /edit/open
  lib/MusicBrainz/Server/Data/Edit.pm
  t/lib/t/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Edit/Open.pm
Labels: QoL

#2019 MBS-11530: Avoid common/MB/release code running on these
  root/release/edit/tracklist.tt
  root/release/index.tt
  root/static/scripts/common.js
  root/static/scripts/release/index.js
  root/static/styles/release-editor.less
  webpack.client.config.js
Labels: Regression/Beta

#2017 MBS-11525: Link to downvoted per-entity list when seeing downvotes
  root/components/TagEntitiesList.js
Labels: Regression/Beta

#2012 MBS-9851: Allow finding edits w/ edit notes by not original editor
  lib/MusicBrainz/Server/EditSearch/Predicate/Role/User.pm
  root/edit/search_macros.tt
Labels: New feature

#2021 MBS-11531: Pass $c to _load in load_filtered
  lib/MusicBrainz/Server/Report/FilterForEditor.pm
Labels: Regression/Beta

#1857 MBS-11320 / MBS-11321: Don't add new medium if empty medium existed
  root/static/scripts/release-editor/dialogs.js
  root/static/scripts/release-editor/fields.js
  root/static/scripts/release-editor/init.js
Labels: Bug

#1993 MBS-11455: Hide view links on stats when logged out
  root/user/UserProfile.js
Labels: QoL
