Repository metabrainz/musicbrainz-server, pull requests merged in 2021-02, with the labels that each got.

#1883 MBS-11353: Allow empty row in multiple select
  root/components/SelectField.js
Labels: Regression/Beta

#1884 Simplify bottom links to avoid translation parameters
  root/artist/ArtistIndex.js
Labels: Regression/Beta

#1887 MBS-11357: Allow linking RateYourMusic to release groups
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Regression/Beta

#1888 MBS-11358: Allow alias sort name to be blank
  root/static/scripts/alias/AliasEditForm.js
  root/static/scripts/edit/components/FormRowSortNameWithGuessCase.js
Labels: Regression/Beta

#1890 MBS-11360: Work around unconsistent name for RG type
  lib/MusicBrainz/Server/Controller/Role/Alias.pm
Labels: Regression/Beta

#1891 MBS-11362: Avoid autovivification leading to broken edit data
  lib/MusicBrainz/Server/Edit/Medium/Edit.pm
Labels: Regression/Beta

#1892 MBS-11363: Fix broken returnto in merge-helper.tt
  root/layout/merge-helper.tt
Labels: Bug, Regression/Beta

#1886 Link directly to the IA for CAA thumbnails
  lib/DBDefs/Default.pm
  lib/MusicBrainz/Server/Entity/Artwork.pm
  lib/MusicBrainz/Server/Entity/Artwork/ReleaseGroup.pm
  root/components/Artwork.js
  root/components/common-macros.tt
  root/types.js
Labels: Refactoring

#1893 MBS-11365: Allow Resident Advisor /podcast URLs for releases
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#1885 MBS-11354: Don't show arrows unless we want ordering
  root/forms/relationship-editor.tt
Labels: Bug

#1902 MBS-11368: Set nameVariation in EditMedium if rec name != track name
  root/edit/details/EditMedium.js
Labels: Regression/Beta

#1894 MBS-11352 / MBS-11366: Malware blocking improvements
  root/static/scripts/common/components/EntityLink.js
  root/static/scripts/edit/externalLinks.js
  root/url/utility/isGreyedOut.js
Labels: Bug, New feature

#1889 MBS-11359: Add GeoNames to the sidebar
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/GeoNames.pm
  root/static/images/favicons/geonames-16.png
  root/static/scripts/common/constants.js
  root/static/styles/favicons.less
Labels: New feature

#1863 MBS-11329: Return privileges as a number in internal editor JSON
  lib/MusicBrainz/Server/Entity/Editor.pm
  root/admin/wikidoc/WikiDocIndex.js
  root/components/Aliases/index.js
  root/components/EntityTabs.js
  root/components/UserAccountLayout.js
  root/components/UserAccountTabs.js
  root/constants.js
  root/elections/ElectionVoting.js
  root/layout/components/TopMenu.js
  root/layout/components/sidebar/AreaSidebar.js
  root/layout/components/sidebar/GenreSidebar.js
  root/layout/components/sidebar/InstrumentSidebar.js
  root/layout/index.js
  root/relationship/linkattributetype/RelationshipAttributeTypesIndex.js
  root/relationship/linktype/RelationshipTypeIndex.js
  root/relationship/linktype/RelationshipTypePairTree.js
  root/report/LimitedEditors.js
  root/report/ReportsIndex.js
  root/search/components/AreaResults.js
  root/search/components/ArtistResults.js
  root/search/components/EventResults.js
  root/search/components/InstrumentResults.js
  root/search/components/LabelResults.js
  root/search/components/PlaceResults.js
  root/search/components/RecordingResults.js
  root/search/components/ReleaseGroupResults.js
  root/search/components/ReleaseResults.js
  root/search/components/SeriesResults.js
  root/search/components/WorkResults.js
  root/static/scripts/common/utility/privileges.js
  root/types.js
  root/user/UserProfile.js
  root/utility/activeSanitizedEditor.js
  root/utility/edit.js
  root/utility/hydrate.js
  root/utility/sanitizedEditor.js
  root/utility/voting.js
Labels: Refactoring

#1899 MBS-11370: display track lengths of 0 ms or -1 ms as unknown
  lib/MusicBrainz/Server/Edit/Historic/AddTrackKV.pm
  lib/MusicBrainz/Server/Edit/Historic/EditTrackLength.pm
  root/edit/details/historic/AddTrackKV.js
Labels: QoL

#1905 MBS-11375: Use top-align for release event tables in Edit release
  root/static/scripts/edit/components/edit/ReleaseEventsDiff.js
  root/static/styles/edit.less
Labels: QoL

#1921 MBS-10195: Block Google AMP links
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#1926 MBS-10470: Rename "IRC" link in footer to "Chat (IRC)"
  root/layout/components/Footer.js
Labels: QoL

#1912 MBS-11390: Sum, don't overwrite, added entity counts
  lib/MusicBrainz/Server/Data/Editor.pm
Labels: Bug

#1919 MBS-11397: Show place-series rels on series page
  lib/MusicBrainz/Server/Controller/Series.pm
Labels: Bug

#1914 MBS-10343 / MBS-11394: Deal with darkened cover art
  lib/MusicBrainz/Server/Controller/Release.pm
  root/components/EntityTabs.js
  root/layout/components/sidebar/ReleaseSidebar.js
  root/release/CoverArt.js
  root/release/CoverArtDarkened.js
Labels: QoL

#1924 MBS-10117: Fix broken maxlength password message on register page
  lib/MusicBrainz/Server/Form/User/Register.pm
Labels: Bug

#1918 MBS-11395: Update the sidebar matching for muziekweb
  lib/MusicBrainz/Server/Data/URL.pm
  root/static/images/favicons/muziekweb-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug

#1917 MBS-11389: Top-align edit medium Tracklist tables
  root/edit/details/EditMedium.js
  root/static/styles/edit.less
Labels: QoL

#1907 MBS-10744 / MBS-11378: Use lp_attributes for gender
  root/layout/components/sidebar/ArtistSidebar.js
  root/user/UserProfile.js
Labels: Bug

#1910 MBS-11387: Use l_relationships for "instrument" attribute name
  root/static/scripts/common/i18n/localizeLinkAttributeTypeName.js
Labels: Bug

#1925 MBS-9095 / MBS-10557: Add Recochoku and mora links to the sidebar and normalize Recochoku to HTTPS
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/Mora.pm
  lib/MusicBrainz/Server/Entity/URL/Recochoku.pm
  root/static/images/favicons/mora-32.png
  root/static/images/favicons/recochoku-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature

#1916 MBS-10227: Display entity count on collection page
  lib/MusicBrainz/Server/Controller/Collection.pm
  root/layout/components/sidebar/CollectionSidebar.js
Labels: QoL

#1920 MBS-11396: Show item_entity_type on Series/CollectionType admin tables
  lib/MusicBrainz/Server/Entity/CollectionType.pm
  root/admin/attributes/Attribute.js
Labels: Bug

#1906 MBS-9706: Normalize OCRemix URLs (including HTTPS)
  lib/MusicBrainz/Server/Entity/URL/OCReMix.pm
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#1927 MBS-10452: Implement tagger links for releases on recording pages
  root/recording/RecordingIndex.js
Labels: QoL

#1937 MBS-10004: JSON-LD MBID URIs should be HTTP
  lib/DBDefs/Default.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Role/GID.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Role/SameAs.pm
  t/lib/t/MusicBrainz/Server/Controller/Area/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Area/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Recordings.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Relationships.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Place/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Place/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Release/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Release/CoverArt.pm
  t/lib/t/MusicBrainz/Server/Controller/Release/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Work/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Work/Show.pm
Labels: Bug
