Repository metabrainz/musicbrainz-server, pull requests merged in 2021-01, with the labels that each got.

#1807 MBS-11248: Block smart links: li.sten.to
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#1806 MBS-11240 / MBS-11246: Small Amazon changes
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/AmazonMusic.pm
  lib/MusicBrainz/Server/Report/BadAmazonURLs.pm
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug, New feature

#1812 MBS-11263: Allow % (for encoded stuff) on beatport URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug

#1796 MBS-11228: Convert Change Release Quality edit to React
  lib/MusicBrainz/Server/Edit/Release/ChangeQuality.pm
  root/edit/details/ChangeReleaseQuality.js
  root/edit/details/add_track_kv.tt
  root/edit/details/change_release_data_quality.tt
  root/server/components.js
Labels: React

#1817 MBS-11264: Guess case apostrophe fixes
  root/static/scripts/guess-case/modes.js
  root/static/scripts/guess-case/utils.js
  root/static/scripts/tests/GuessCase.js
Labels: Bug

#1799 MBS-11233 / MBS-11237: Fixes to relationship editor seeding
  root/static/scripts/relationship-editor/common/viewModel.js
Labels: Bug

#1800 MBS-11239: Convert historic Edit Release Events edit to React
  lib/MusicBrainz/Server/Edit/Historic/EditReleaseEventsOld.pm
  root/edit/details/edit_release_events.tt
  root/edit/details/historic/EditReleaseEvents.js
  root/server/components.js
Labels: React

#1097 MBS-6048: Allow edit notes when submitting ISRCs
  lib/MusicBrainz/Server/Controller/WS/2/Recording.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/SubmitRecording.pm
Labels: New feature

#1833 MBS-11291: Fix wrong bootleg check in ReleasesSameBarcode
  lib/MusicBrainz/Server/Report/ReleasesSameBarcode.pm
Labels: Bug

#1826 MBS-8169 / MBS-11274: Add a link to the timeline for individual statistics
  root/static/images/attribution.txt
  root/static/images/icons/timeline.png
  root/static/scripts/timeline.js
  root/static/styles/layout.less
  root/static/styles/relationship-editor.less
  root/statistics/Countries.js
  root/statistics/CoverArt.js
  root/statistics/Edits.js
  root/statistics/Formats.js
  root/statistics/Index.js
  root/statistics/LanguagesScripts.js
  root/statistics/Relationships.js
  root/statistics/utilities.js
Labels: New feature, QoL

#1842 MBS-10913: Show removed standalone recordings as such
  root/edit/details/AddStandaloneRecording.js
Labels: Bug

#1798 MBS-11235: Convert Edit Instrument edit to React
  lib/MusicBrainz/Server/Edit/Instrument/Edit.pm
  root/edit/details/EditEvent.js
  root/edit/details/EditInstrument.js
  root/edit/details/edit_instrument.tt
  root/server/components.js
Labels: React

#1828 MBS-11275: Load recordings for cdtoc move
  lib/MusicBrainz/Server/Controller/CDTOC.pm
Labels: Bug

#1829 MBS-11278: Also show rating info when there's only private ratings
  root/entity/Ratings.js
Labels: Bug

#1783 MBS-11126: display track lengths of 0 ms or -1 ms as unknown
  root/edit/details/historic/AddTrackKV.js
Labels: QoL

#1805 MBS-11247: Stop highlighting BBC Music links
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/BBCMusic.pm
  root/static/images/favicons/bbcmusic-32.png
  root/static/scripts/common/constants.js
  root/static/styles/favicons.less
Labels: QoL

#1839 MBS-11285: Always load user ratings for collections
  lib/MusicBrainz/Server/Controller/Collection.pm
Labels: Bug

#1831 MBS-11183: Always preserve merged entity name as alias
  lib/MusicBrainz/Server/Data/Alias.pm
Labels: Bug

#1840 MBS-8141 / MBS-10954: Small improvements to Remove DiscId page
  lib/MusicBrainz/Server/Controller/CDTOC.pm
  root/cdtoc/remove.tt
Labels: Bug, QoL

#1811 MBS-11262: Fix l_attributes translation calls
  root/layout/components/sidebar/ReleaseSidebar.js
  root/layout/components/sidebar/SeriesSidebar.js
  root/statistics/stats.js
Labels: Bug

#1816 MBS-11265: Load ACs for Reorder medium edits
  lib/MusicBrainz/Server/Edit/Release/ReorderMediums.pm
Labels: Bug

#1830 MBS-11181 / MBS-11281: Improvements to date merging in the relationship editor
  root/static/scripts/relationship-editor/common/fields.js
  root/static/scripts/tests/relationship-editor.js
Labels: Bug

#1808 MBS-11250 / MBS-11253: Properly support JSON user-rating / user-tags lookups
  lib/MusicBrainz/Server/Controller/WS/2/Rating.pm
  lib/MusicBrainz/Server/Controller/WS/2/Tag.pm
  lib/MusicBrainz/Server/WebService/JSONSerializer.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/Authenticated.pm
Labels: Bug

#1846 MBS-11306: Update CDJapan normalization and add autoselect
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/CDJapan.pm
  root/static/images/favicons/cdjapan-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature

#1845 MBS-11309: Block ToneDen smart links
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#1847 MBS-11304: Add recordings’ first release date to release lookup
  lib/MusicBrainz/Server/Controller/WS/2/Release.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Recording.pm
  lib/MusicBrainz/Server/WebService/XMLSerializer.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupISRC.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelationship.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm
Labels: New feature

#1853 MBS-11319: Fix adding cover art in beta
  root/components/SelectField.js
  root/release/CoverArtFields.js
Labels: Regression/Beta

#1841 MBS-10915: Show "Remove track" button for data tracks even with discid
  root/release/edit/tracklist.tt
Labels: QoL

#1843 MBS-10830: Only show Remove link if entity can be removed
  lib/MusicBrainz/Server.pm
  lib/MusicBrainz/Server/Controller/Role/Delete.pm
  root/layout/components/sidebar/LabelSidebar.js
  root/layout/components/sidebar/RemoveLink.js
  root/types.js
Labels: QoL

#1818 MBS-4548: Allow seeing all uses of an artist credit
  lib/MusicBrainz/Server/Controller/ArtistCredit.pm
  lib/MusicBrainz/Server/Data/Recording.pm
  lib/MusicBrainz/Server/Data/Release.pm
  lib/MusicBrainz/Server/Data/ReleaseGroup.pm
  lib/MusicBrainz/Server/Data/Track.pm
  lib/MusicBrainz/Server/Edit/Artist/EditArtistCredit.pm
  root/artist_credit/ArtistCreditIndex.js
  root/artist_credit/ArtistCreditLayout.js
  root/artist_credit/EntityList.js
  root/components/Aliases/ArtistCreditList.js
  root/edit/details/EditArtistCredit.js
  root/server/components.js
  root/tag/EntityList.js
  root/tag/TagIndex.js
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
Labels: New feature

#1825 MBS-8028: Allow editing series type to any with same entity type
  lib/MusicBrainz/Server/Data/Series.pm
  root/static/scripts/series.js
Labels: New feature

#1852 MBS-11317: Avoid breaking annotation formatting in RE
  root/static/scripts/edit/MB/edit.js
  root/static/scripts/tests/release-editor/edits.js
Labels: Bug

#1836 MBS-11292: Do not use UN flag for [Worldwide]
  root/static/images/attribution.txt
  root/static/images/flags/xw.png
Labels: QoL

#1810 MBS-9840: Add Overture by Doremus to the otherdbs whitelist
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/Overture.pm
  root/static/images/favicons/overture-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature

#1822 MBS-11268: Show "Set track durations" on release/discids
  lib/MusicBrainz/Server/Controller/Release.pm
  root/release/discids.tt
Labels: QoL

#1814 MBS-9674: Support internationalized domains in URL forms
  lib/MusicBrainz/Server/Form/Field/OAuthRedirectURI.pm
  lib/MusicBrainz/Server/Form/Field/URL.pm
  package.json
  root/static/scripts/edit/externalLinks.js
  root/static/scripts/url.js
  yarn.lock
Labels: Bug

#1855 MBS-11324: Trim input in the barcode otherlookups field
  lib/MusicBrainz/Server/Form/OtherLookup.pm
Labels: QoL

#1767 Eslint fixes (few more rules for CI)
  .eslintignore
  .eslintrc.unfixed.yaml
  .eslintrc.yaml
  root/artist/ArtistRecordings.js
  root/layout/components/sidebar/SidebarDataQuality.js
  root/static/manifest.js
  root/static/scripts/common.js
  root/static/scripts/common/i18n/attributes.js
  root/static/scripts/common/i18n/countries.js
  root/static/scripts/edit/ExampleRelationships.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/edit/components/forms.js
  root/static/scripts/guess-case/MB/Control/GuessCase.js
  root/static/scripts/guess-case/MB/GuessCase/Output.js
  root/static/scripts/jed-data.js
  root/static/scripts/jquery.flot.musicbrainz_events.js
  root/static/scripts/relationship-editor/common/dialog.js
  root/static/scripts/relationship-editor/common/fields.js
  root/static/scripts/release-editor/fields.js
  root/static/scripts/release-editor/init.js
  root/static/scripts/release-editor/recordingAssociation.js
  root/static/scripts/tests/relationship-editor.js
  root/static/scripts/tests/release-editor/dialogs.js
  root/static/scripts/timeline.js
  root/vars.js
  root/work/WorkIndex.js
  script/xgettext.js
  t/selenium.js
  t/web.js
  webpack.client.config.js
  webpack.server.config.js
  webpack/browserConfig.js
Labels: Refactoring

#1815 MBS-11256: Make adding tracklist to empty medium an autoedit
  lib/MusicBrainz/Server/Edit/Medium/Edit.pm
  t/lib/t/MusicBrainz/Server/Edit/Medium/Edit.pm
Labels: QoL

#1774 MBS-11111: Set edit_pendings on recordings merged with release
  lib/MusicBrainz/Server/Edit/Release/Merge.pm
  t/lib/t/MusicBrainz/Server/Edit/Release/Merge.pm
Labels: QoL

#1838 MBS-11296 / MBS-11297: More blocks for Wikipedia/Wikidata at release level
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#1835 MBS-11289: Stop autocleaning YouTube Music -> YouTube
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug

#1861 MBS-11328: Regression: Approving an edit redirects to home page
  lib/MusicBrainz/Server.pm
Labels: Regression/Beta

#1624 MBS-10999: Make adding first IPI/ISNI an auto-edit
  lib/MusicBrainz/Server/Data/Release.pm
  lib/MusicBrainz/Server/Data/Role/IPI.pm
  lib/MusicBrainz/Server/Data/Role/ISNI.pm
  lib/MusicBrainz/Server/Data/Utils.pm
  lib/MusicBrainz/Server/Edit/Artist/Edit.pm
  lib/MusicBrainz/Server/Edit/Label/Edit.pm
  lib/MusicBrainz/Server/Edit/Relationship/Delete.pm
  lib/MusicBrainz/Server/Edit/Release/Merge.pm
  lib/MusicBrainz/Server/Edit/Role/IPI.pm
  lib/MusicBrainz/Server/Edit/Role/ISNI.pm
  lib/MusicBrainz/Server/Entity/EditNote.pm
  t/lib/t/MusicBrainz/Server/Edit/Medium/SetTrackLengths.pm
Labels: QoL

#1870 MBS-11336: Don't show ended rels in DeprecatedRelationshipURL
  lib/MusicBrainz/Server/Report/DeprecatedRelationshipReport.pm
Labels: QoL

#1867 MBS-4782 / MBS-11333: Pass original MBID to AddCoverArt if no release
  lib/MusicBrainz/Server/Edit/Release/AddCoverArt.pm
Labels: Bug, Regression/Beta

#1866 MBS-11327: Show CAA icons on release search results
  lib/MusicBrainz/Server/Controller/Search.pm
  lib/MusicBrainz/Server/Data/Release.pm
  lib/MusicBrainz/Server/Data/Search.pm
  root/search/components/ReleaseResults.js
Labels: QoL

#1864 MBS-11332: Don't double-bracket ended in track rels view
  root/components/GroupedTrackRelationships.js
Labels: Bug

#1856 MBS-11322: Update Resident Advisor URL cleanup and add validation
  lib/MusicBrainz/Server/Data/URL.pm
  root/static/images/favicons/residentadvisor-16.png
  root/static/images/favicons/residentadvisor-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: Bug, New feature

#1844 MBS-11310: Clarify when discid would cause subsecond changes
  root/cdtoc/set_durations.tt
Labels: QoL

#1619 MBS-10995 / MBS-10996 / MBS-11277 / MBS-11279: Convert Other Lookups pages and search index to React
  lib/MusicBrainz/Server/Controller/OtherLookup.pm
  lib/MusicBrainz/Server/Controller/Search.pm
  lib/MusicBrainz/Server/Form/OtherLookup.pm
  root/components/ReleaseLanguageScript.js
  root/components/list/ReleaseList.js
  root/components/results-generic.tt
  root/otherlookup/OtherLookupForm.js
  root/otherlookup/OtherLookupIndex.js
  root/otherlookup/OtherLookupReleaseResults.js
  root/otherlookup/form.tt
  root/otherlookup/index.tt
  root/otherlookup/results-release.tt
  root/otherlookup/results-work.tt
  root/otherlookup/results.tt
  root/otherlookup/types.js
  root/report/components/ReleaseList.js
  root/search/SearchIndex.js
  root/search/components/ReleaseResults.js
  root/search/index.tt
  root/server/components.js
  root/taglookup/form.tt
  root/utility/tableColumns.js
Labels: React

#1858 MBS-10964: Prevent and handle empty artist credit name submissions in the release editor
  lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
  root/static/scripts/common.js
  root/static/scripts/common/focusin-focusout-polyfill.js
  root/static/scripts/edit/MB/edit.js
  t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
Labels: Bug

#1779 MBS-1459: Only display links at bottom of artist overview when relevant
  lib/MusicBrainz/Server/Controller/Artist.pm
  lib/MusicBrainz/Server/Data/ReleaseGroup.pm
  root/artist/ArtistIndex.js
Labels: New feature

#1873 MBS-11340: Allow more characters on Spotify user URLs
  lib/MusicBrainz/Server/Entity/URL/Spotify.pm
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug

#1660 MBS-11045 / MBS-10872: Convert Edit medium edit to React
  lib/MusicBrainz/Server/Edit/Medium/Edit.pm
  root/artist/ArtistIndex.js
  root/artist/ArtistRecordings.js
  root/collection/CollectionIndex.js
  root/components/list/RecordingList.js
  root/edit/details/EditMedium.js
  root/edit/details/MergeRecordings.js
  root/edit/details/edit_medium.tt
  root/edit/details/macros.tt
  root/instrument/InstrumentRecordings.js
  root/isrc/Index.js
  root/layout/components/sidebar/RecordingSidebar.js
  root/recording/RecordingFingerprints.js
  root/recording/RecordingHeader.js
  root/recording/RecordingIndex.js
  root/recording/RecordingLayout.js
  root/recording/RecordingMerge.js
  root/report/types.js
  root/search/components/RecordingResults.js
  root/series/SeriesIndex.js
  root/server/components.js
  root/static/scripts/common/components/Autocomplete2/formatters.js
  root/static/scripts/common/components/DescriptiveLink.js
  root/static/scripts/edit/utility/diffArtistCredits.js
  root/taglookup/RecordingResults.js
  root/types.js
  t/lib/t/MusicBrainz/Server/Edit/Medium/Edit.pm
Labels: React

#1837 MBS-11288: Drop decoda.com from lyrics whitelist
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/Decoda.pm
  root/static/images/favicons/decoda-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/edit/externalLinks.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
  t/sql/snoop-lion-slash-dogg.sql
  t/sql/the-beatles.sql
Labels: QoL

#1880 MBS-11351: Sort instrument reports by name before type
  lib/MusicBrainz/Server/Report/InstrumentsWithoutAnImage.pm
  lib/MusicBrainz/Server/Report/InstrumentsWithoutWikidata.pm
Labels: QoL

#1859 MBS-10187: "Merge artists" edit is stuck
  lib/MusicBrainz/Server/Data/Artist.pm
  lib/MusicBrainz/Server/Data/Utils.pm
  lib/MusicBrainz/Server/Edit/Artist/Merge.pm
  t/lib/t/MusicBrainz/Server/Controller/Relationship/LinkAttributeType/Edit.pm
  t/lib/t/MusicBrainz/Server/Data/Editor.pm
  t/lib/t/MusicBrainz/Server/Data/ISWC.pm
  t/lib/t/MusicBrainz/Server/Data/LinkAttributeType.pm
  t/lib/t/MusicBrainz/Server/Edit/Artist/Merge.pm
  t/lib/t/MusicBrainz/Server/Edit/Medium/MoveDiscID.pm
  t/lib/t/MusicBrainz/Server/Edit/Release/EditReleaseLabel.pm
  t/sql/edit_artist_merge.sql
Labels: Bug

#1877 MBS-11344: Use HTTPS for rateyourmusic URLs and add validation
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#1658 MBS-11168: Convert Alias edit forms to React
  lib/MusicBrainz/Server/Controller.pm
  lib/MusicBrainz/Server/Controller/Role/Alias.pm
  lib/MusicBrainz/Server/Form/Alias.pm
  lib/MusicBrainz/Server/Form/Field/DatePeriod.pm
  lib/MusicBrainz/Server/Form/Role/ToJSON.pm
  root/artist/ArtistMerge.js
  root/components/EnterEdit.js
  root/components/FieldErrors.js
  root/components/FormRowCheckbox.js
  root/components/FormRowPartialDate.js
  root/components/FormRowSelect.js
  root/components/FormRowText.js
  root/components/PartialDateInput.js
  root/components/forms.tt
  root/entity/alias/AddOrEditAlias.js
  root/entity/alias/DeleteAlias.js
  root/entity/alias/add.tt
  root/entity/alias/delete.tt
  root/entity/alias/edit.tt
  root/entity/alias/edit_form.tt
  root/entity/alias/types.js
  root/recording/edit_form.tt
  root/server/components.js
  root/static/scripts/account/components/EditProfileForm.js
  root/static/scripts/account/components/PreferencesForm.js
  root/static/scripts/alias.js
  root/static/scripts/alias/AliasEditForm.js
  root/static/scripts/collection/components/CollectionEditForm.js
  root/static/scripts/edit/components/DateRangeFieldset.js
  root/static/scripts/edit/components/FormRowNameWithGuessCase.js
  root/static/scripts/edit/components/FormRowSortNameWithGuessCase.js
  root/static/scripts/edit/utility/copyFieldData.js
  root/static/scripts/edit/utility/createField.js
  root/static/scripts/edit/utility/dates.js
  root/static/scripts/recording/RecordingName.js
  root/types.js
  root/user/Login.js
  root/user/ReportUser.js
  root/utility/chooseLayoutComponent.js
  root/utility/iterSubfields.js
  root/utility/iterSubfields.js.flow
  root/utility/subfieldErrors.js
  t/lib/t/MusicBrainz/Server/Controller/Label/EditAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/EditAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Series/EditAlias.pm
  webpack.client.config.js
Labels: React

#1699 MBS-11112: Convert /main error pages to React
  lib/MusicBrainz/Server.pm
  lib/MusicBrainz/Server/Controller/Root.pm
  lib/MusicBrainz/Server/Edit.pm
  root/context.js
  root/main/400.tt
  root/main/401.tt
  root/main/403.tt
  root/main/404.js
  root/main/500.tt
  root/main/503.tt
  root/main/error/Error400.js
  root/main/error/Error401.js
  root/main/error/Error403.js
  root/main/error/Error404.js
  root/main/error/Error500.js
  root/main/error/Error503.js
  root/main/error/ErrorLayout.js
  root/main/error/MirrorError403.js
  root/main/error/MirrorError404.js
  root/main/error/TimeoutError.js
  root/main/error/components/ErrorEnvironment.js
  root/main/error/components/ErrorInfo.js
  root/main/info/environment.tt
  root/main/info/error.tt
  root/main/mirror.tt
  root/main/mirror_404.tt
  root/main/timeout.tt
  root/server/components.js
  root/server/response.js
  root/static/scripts/common/utility/bugTrackerURL.js
  root/types.js
Labels: React
