Repository metabrainz/musicbrainz-server, pull requests merged in 2021-09, with the labels that each got.

#2254 MBS-11944: Fix label on button for place merges
  root/area/AreaPlaces.js
Labels: Bug

#2180 MBS-11799: Display "credited as" field in sidebar external links
  root/layout/components/ExternalLinks.js
Labels: QoL

#2245 MBS-11932: Also exclude work licenses from LinksWithMultipleEntities
  lib/MusicBrainz/Server/Report/LinksWithMultipleEntities.pm
Labels: Bug

#2235 MBS-9454: Autoremove unused urls with daily.sh
  admin/cron/daily.sh
  entities.json
  lib/MusicBrainz/Script/RemoveEmpty.pm
  lib/MusicBrainz/Server/Data/URL.pm
  t/lib/t/MusicBrainz/Script/RemoveEmptyURLs.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/EditExternalLinks.pm
  t/sql/url.sql
  t/tests.t
Labels: Bug

#2193 MBS-11843: Add report for "Events with annotations"
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/AnnotationsEvents.js
  root/report/ReportsIndex.js
  root/report/components/EventList.js
  root/report/types.js
  root/server/components.js
Labels: New feature

#2258 MBS-11940: Properly error for invalid XML sent to /ws/2/tag
  lib/MusicBrainz/Server/Controller/WS/2/Tag.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/Authenticated.pm
Labels: Bug

#2173 MBS-6140: Allow (recording|work)-level-rels for release browse
  lib/MusicBrainz/Server/Controller/WS/2/Release.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/BrowseRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/BrowseReleases.pm
  t/sql/webservice.sql
Labels: New feature

#2213 MBS-8098: Allow release-group-level-rels in release lookup
  lib/MusicBrainz/Server/Controller/WS/2/Release.pm
  lib/MusicBrainz/Server/WebService/WebServiceInc.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRelease.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRelease.pm
  t/sql/webservice.sql
Labels: New feature

#2146 MBS-11717: Also show edits pending in ArtistCreditUsageLink
  root/artist_credit/ArtistCreditLayout.js
  root/report/components/ArtistCreditList.js
  root/static/scripts/common/components/ArtistCreditLink.js
  root/static/scripts/common/components/ArtistCreditUsageLink.js
  root/static/styles/tooltip.less
Labels: Bug

#1977 MBS-8820: Show explanation if relationships tab shows no rels
  root/artist/ArtistRelationships.js
  root/components/Relationships.js
  root/label/LabelRelationships.js
Labels: Bug

#2250 MBS-11819: Show to admins whether account has oAuth uses
  lib/MusicBrainz/Server/Controller/User.pm
  root/user/UserProfile.js
Labels: New feature

#2234 MBS-11841: Convert Set Track Lengths edit to React
  lib/MusicBrainz/Server/Edit/Historic/SetTrackLengthsFromCDTOC.pm
  lib/MusicBrainz/Server/Edit/Medium/SetTrackLengths.pm
  root/components/common-macros.tt
  root/edit/components/HistoricReleaseList.js
  root/edit/components/TrackDurationChanges.js
  root/edit/details/SetTrackLengths.js
  root/edit/details/set_track_lengths.tt
  root/server/components.js
Labels: React

#1754 MBS-11130: Clarify it's not possible to subscribe to VA / [no label]
  root/entity/Subscribers.js
  root/static/scripts/common/utility/isSpecialPurpose.js
Labels: QoL

#2269 MBS-11960: Also assign seeded URL to rawURL
  root/static/scripts/edit/externalLinks.js
Labels: Bug

#2246 MBS-11852: Only call TO_JSON on editor if it exists
  lib/MusicBrainz/Server/Entity/EditNote.pm
  root/edit/components/EditorTypeInfo.js
  root/types/edit.js
Labels: Bug

#2236 MBS-10639: Convert release merge edit to React
  lib/MusicBrainz/Server/Controller/Release.pm
  lib/MusicBrainz/Server/Edit/Generic/Merge.pm
  lib/MusicBrainz/Server/Edit/Release/Merge.pm
  root/edit/details/MergeReleases.js
  root/edit/details/merge_releases.tt
  root/server/components.js
Labels: React

#2264 MBS-11961: Rename "random" in edit search since it's not random
  root/edit/search_macros.tt
Labels: QoL

#2255 MBS-10902: Stop changing zxx language name at the Perl level
  lib/MusicBrainz/Server/Data/Language.pm
  lib/MusicBrainz/Server/Edit/Work/Create.pm
  lib/MusicBrainz/Server/Edit/Work/Edit.pm
  root/edit/details/AddWork.js
  root/edit/details/EditWork.js
  root/static/scripts/common/MB/Control/Autocomplete.js
  root/static/scripts/common/components/Autocomplete2/formatters.js
  root/static/scripts/common/components/WorkListEntry.js
  root/static/scripts/common/i18n/localizeLanguageName.js
  root/utility/tableColumns.js
Labels: Bug

#2278 MBS-11973: Also load edits_pending for appears_on
  lib/MusicBrainz/Server/Data/Recording.pm
Labels: Bug

#2286 MBS-11989: Also correct rg to release_group for delete_alias
  lib/MusicBrainz/Server/Controller/Role/Alias.pm
Labels: Bug

#2257 MBS-11941: Normalize Worldcat identities URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2268 MBS-11968: Allow VIAF, DNB, LoC links for series
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2260 MBS-11957: Clean up twitch.com to twitch.tv
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2261 MBS-11959: Allow RYM links for music video recordings
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#2285 MBS-11975: Clean up CDJapan detailview URLs
  lib/MusicBrainz/Server/Entity/URL/CDJapan.pm
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2198 MBS-11830: Add more collection statistics
  lib/MusicBrainz/Server/Data/Statistics.pm
  root/statistics/Index.js
  root/statistics/stats.js
Labels: New feature

#2262 MBS-11952: Autoselect Vimeo On Demand URLs correctly
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/VimeoOnDemand.pm
  root/static/images/external-favicons/vimeoondemand-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: Bug

#2291 MBS-11998: Also include places on rating stats sum
  lib/MusicBrainz/Server/Data/Statistics.pm
Labels: Bug
