Repository metabrainz/musicbrainz-server, pull requests merged in 2021-06, with the labels that each got.

#1453 MBS-10107: Add overview page for rel attributes
  lib/MusicBrainz/Server/Controller/Relationship/LinkAttributeType.pm
  lib/MusicBrainz/Server/Data/LinkAttributeType.pm
  lib/MusicBrainz/Server/Data/LinkType.pm
  lib/MusicBrainz/Server/Data/Role/OptionsTree.pm
  lib/MusicBrainz/Server/Entity/LinkAttributeType.pm
  root/relationship/linkattributetype/RelationshipAttributeTypeIndex.js
  root/relationship/linkattributetype/RelationshipAttributeTypesList.js
  root/server/components.js
  t/lib/t/MusicBrainz/Server/Controller/Relationship/LinkAttributeType/Create.pm
  t/lib/t/MusicBrainz/Server/Controller/Relationship/LinkAttributeType/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
Labels: New feature

#2101 MBS-10205: Readd link to the Data Removal Policy to the menu
  root/layout/components/BottomMenu.js
Labels: QoL

#2078 MBS-11627: Don’t show "delete" link in UserList for deleted editors
  root/admin/components/UserList.js
Labels: QoL

#1872 MBS-11330: Split root/types.js into smaller files
  .flowconfig
  root/main/index.js
  root/release_group/ReleaseGroupIndex.js
  root/search/components/PaginatedSearchResults.js
  root/search/types.js
  root/static/scripts/common/components/CritiqueBrainzReview.js
  root/static/scripts/common/i18n/wrapGettext.js
  root/taglookup/types.js
  root/types.js
  root/types/alias.js
  root/types/annotation.js
  root/types/area.js
  root/types/artist.js
  root/types/artistcredit.js
  root/types/artwork.js
  root/types/autoeditorelection.js
  root/types/catalyst.js
  root/types/cdstub.js
  root/types/codes.js
  root/types/collection.js
  root/types/edit.js
  root/types/editor.js
  root/types/entity.js
  root/types/event.js
  root/types/formcomponents.js
  root/types/forms.js
  root/types/genre.js
  root/types/i18n.js
  root/types/instrument.js
  root/types/knockout.js
  root/types/label.js
  root/types/languageandscript.js
  root/types/medium.js
  root/types/misc.js
  root/types/oauth.js
  root/types/place.js
  root/types/rating.js
  root/types/recording.js
  root/types/relationship.js
  root/types/release.js
  root/types/releasegroup.js
  root/types/series.js
  root/types/tag.js
  root/types/track.js
  root/types/url.js
  root/types/vote.js
  root/types/work.js
  root/types/workattribute.js
Labels: Refactoring

#1860 MBS-11326: Convert edit/notes.tt to React
  lib/MusicBrainz/Server/Controller/User.pm
  lib/MusicBrainz/Server/Edit.pm
  lib/MusicBrainz/Server/Entity/EditNote.pm
  lib/MusicBrainz/Server/Entity/Editor.pm
  lib/MusicBrainz/Server/Entity/Vote.pm
  root/components/UserAccountLayout.js
  root/components/common-macros.tt
  root/edit/components/EditNote.js
  root/edit/components/EditNotes.js
  root/edit/components/EditorTypeInfo.js
  root/edit/index.tt
  root/edit/list.tt
  root/edit/notes-received.tt
  root/edit/notes.tt
  root/server/components.js
  root/static/scripts/edit/utility/getVoteName.js
  root/types/edit.js
  root/types/editor.js
  root/utility/hydrate.js
  root/utility/sanitizedEditor.js
Labels: React

#2088 MBS-11609: Show genre disambiguation on autocomplete dropdown
  root/static/scripts/common/components/TagEditor.js
Labels: QoL

#2129 MBS-11371: Group members in JSON-LD by date, do not squash
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Artist.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Show.pm
Labels: Bug

#1966 MBS-11430: Convert format_setlist to Javascript
  babel.config.js
  lib/MusicBrainz/Server/Entity/Event.pm
  lib/MusicBrainz/Server/Filters.pm
  root/event/EventIndex.js
  root/static/scripts/common/utility/formatSetlist.js
  root/static/scripts/tests/utility.js
Labels: Refactoring

#1620 MBS-10997: Convert /search/error files to React
  lib/MusicBrainz/Server/Controller/Search.pm
  lib/MusicBrainz/Server/Controller/TagLookup.pm
  root/search/SearchIndex.js
  root/search/components/SearchError.js
  root/search/error/General.js
  root/search/error/InternalError.js
  root/search/error/Invalid.js
  root/search/error/NoInfo.js
  root/search/error/NoResults.js
  root/search/error/RateLimited.js
  root/search/error/UriTooLarge.js
  root/search/error/general.tt
  root/search/error/internal-error.tt
  root/search/error/invalid.tt
  root/search/error/no-info.tt
  root/search/error/no-results.tt
  root/search/error/rate-limit.tt
  root/search/error/uri-too-large.tt
  root/search/error/wrapper.tt
  root/search/form.tt
  root/server/components.js
  root/taglookup/Form.js
  root/taglookup/types.js
  root/types/formcomponents.js
  root/types/forms.js
Labels: React

#1901 MBS-9098: Add "memberOf" relationships to JSON-LD
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Artist.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Show.pm
Labels: New feature

#1834 MBS-11290: Report of works of type X part of another work of type X
  lib/MusicBrainz/Server/Report/WorkReport.pm
  lib/MusicBrainz/Server/Report/WorkSameTypeAsParent.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/ReportsIndex.js
  root/report/WorkSameTypeAsParent.js
  root/report/components/WorkList.js
  root/server/components.js
Labels: New feature

#1186 MBS-4826: Show RGs for recordings in artist list
  lib/MusicBrainz/Server/Controller/Artist.pm
  lib/MusicBrainz/Server/Controller/WS/js/Recording.pm
  lib/MusicBrainz/Server/Data/Recording.pm
  root/artist/ArtistRecordings.js
  root/components/list/RecordingList.js
  root/static/scripts/common/components/ReleaseGroupAppearances.js
  root/types/recording.js
  t/lib/t/MusicBrainz/Server/Data/Recording.pm
Labels: QoL

#2135 MBS-11700: Do not assume cdtoc_id exists
  lib/MusicBrainz/Server/Edit/Historic/RemoveDiscID.pm
  root/edit/components/EditNote.js
  root/types/edit.js
Labels: Regression/Beta

#2132 MBS-11696: Disallow Twitter documentation links
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2134 MBS-11702: Group results also for release/recording/RG search
  lib/MusicBrainz/Server/Data/Search.pm
Labels: Bug

#2090 MBS-11638 / MBS-11639 / MBS-11640: Fixes for the work attribute form
  lib/MusicBrainz/Server/Form/Work.pm
  root/static/scripts/work.js
  root/types/knockout.js
  root/work/edit_form.tt
Labels: Bug

#2139 MBS-11709: Beta: Edit notes with { show raw HTML
  root/edit/components/EditNote.js
Labels: Bug, Regression/Beta

#2140 MBS-11710: Beta: Position the "Add a new entity" dialog on top
  root/static/styles/forms.less
Labels: Bug, Regression/Beta

#2142 Fix getDirection -> isBackward to match other direction changes
  root/static/scripts/relationship-editor/common/entity.js
Labels: Regression/Beta

#2147 MBS-11724: Fix typo
  root/report/CDTocNotApplied.js
Labels: Bug

#1948 MBS-9695: Allow editing LinkAttributeType creditable/free_text via UI
  lib/MusicBrainz/Server/Controller/Relationship/LinkAttributeType.pm
  lib/MusicBrainz/Server/Data/LinkAttributeType.pm
  lib/MusicBrainz/Server/Edit/Relationship/AddLinkAttribute.pm
  lib/MusicBrainz/Server/Edit/Relationship/EditLinkAttribute.pm
  lib/MusicBrainz/Server/Form/Admin/LinkAttributeType.pm
  lib/MusicBrainz/Server/Plugin/FormRenderer.pm
  root/edit/details/AddRelationshipAttribute.js
  root/edit/details/EditRelationshipAttribute.js
  root/relationship/linkattributetype/form.tt
Labels: New feature

#2148 MBS-11342: Add message about track durations and recording reusing
  root/release/edit/recordings.tt
Labels: QoL

#2095 MBS-11644: Allow specifying a release MBID when moving a CD TOC
  lib/MusicBrainz/Server/Controller/CDTOC.pm
  root/cdtoc/move_search.tt
Labels: QoL

#2136 MBS-6811: Make edit note permalink link to edit page
  root/edit/components/EditNote.js
  root/edit/components/EditNotes.js
  root/edit/index.tt
Labels: QoL

#2138 MBS-11697: Show historical primary types on old RG edits
  lib/MusicBrainz/Server/Constants.pm
  lib/MusicBrainz/Server/Edit/Historic/EditReleaseAttrs.pm
  lib/MusicBrainz/Server/Edit/Historic/Utils.pm
  lib/MusicBrainz/Server/Edit/ReleaseGroup/Create.pm
  lib/MusicBrainz/Server/Edit/ReleaseGroup/Edit.pm
  lib/MusicBrainz/Server/Entity/ReleaseGroupType.pm
  root/edit/details/AddReleaseGroup.js
  root/edit/details/EditReleaseGroup.js
  root/edit/details/historic/EditReleaseAttributes.js
  root/types/releasegroup.js
Labels: Bug

#2018 MBS-11520: Convert Remove Relationship Type edit to React
  lib/MusicBrainz/Server/Edit/Relationship/RemoveLinkType.pm
  root/edit/details/AddRelationshipType.js
  root/edit/details/RemoveRelationshipType.js
  root/edit/details/remove_relationship_type.tt
  root/server/components.js
Labels: React

#2015 MBS-5632 / MBS-11522 / MBS-11523: Convert Set Cover Art edit to React
  lib/MusicBrainz/Server/Edit/ReleaseGroup/SetCoverArt.pm
  root/edit/details/SetCoverArt.js
  root/edit/details/set_cover_art.tt
  root/server/components.js
Labels: Bug, React, Regression/Beta

#1945 MBS-9826: Show more realistic edit closing time overviews
  root/components/VotingPeriod.js
Labels: QoL

#1976 MBS-8070: Show Events in contained places in area events tab
  lib/MusicBrainz/Server/Data/Event.pm
Labels: New feature

#1874 MBS-8700: List genres in JSON-LD
  lib/MusicBrainz/Server/Controller/Area.pm
  lib/MusicBrainz/Server/Controller/Artist.pm
  lib/MusicBrainz/Server/Controller/Label.pm
  lib/MusicBrainz/Server/Controller/Place.pm
  lib/MusicBrainz/Server/Controller/Recording.pm
  lib/MusicBrainz/Server/Controller/Release.pm
  lib/MusicBrainz/Server/Controller/ReleaseGroup.pm
  lib/MusicBrainz/Server/Controller/Work.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Area.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Artist.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Label.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Place.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Recording.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Release.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/ReleaseGroup.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Role/Genre.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Work.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Show.pm
Labels: New feature

#1955 MBS-8678 / MBS-8866 / MBS-11421: Split artist improvements
  lib/MusicBrainz/Server/Controller/Artist.pm
  lib/MusicBrainz/Server/Data/Artist.pm
  root/artist/CannotSplit.js
  root/artist/split.tt
  t/lib/t/MusicBrainz/Server/Controller/Artist/Split.pm
Labels: Bug, QoL

#1922 MBS-5680: Allow inc=artist-credits in combination with rels incs that have ACs
  lib/MusicBrainz/Server/WebService/Validator.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupRecording.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupRecording.pm
Labels: New feature

#2154 MBS-11744: Make it easier to mouse-select release dates in tables
  root/static/styles/entity.less
Labels: QoL

#2155 MBS-11753: Fix selectors for RangeSelect in ArtistEdit
  root/static/scripts/edit/MB/Control/ArtistEdit.js
Labels: Bug
