Repository metabrainz/musicbrainz-server, pull requests merged in 2021-04, with the labels that each got.

#2027 MBS-11531 (II): Pass $c to load_filtered call
  lib/MusicBrainz/Server/Controller/Report.pm
Labels: Regression/Beta

#2045 MBS-11566: Ensure consistent ordering of appearances sections
  root/components/RelationshipsTable.js
Labels: QoL

#2050 MBS-11524: Disallow https://*.bandcamp.com/ URLs at release and recording level
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#2057 Fix Catalyst warning: id is missing in edit previews
  lib/MusicBrainz/Server/Edit.pm
  root/edit/CannotApproveEdit.js
  root/edit/CannotCancelEdit.js
  root/edit/NoteIsRequired.js
  root/edit/components/EditSidebar.js
  root/edit/components/EditSummary.js
  root/main/error/Error500.js
  root/static/scripts/common/utility/entityHref.js
  root/types.js
Labels: Refactoring

#2061 Fix Catalyst warning: don't pass undef review text to markdown
  lib/MusicBrainz/Server/Data/CritiqueBrainz.pm
Labels: Refactoring

#2058 MBS-11581: Don't try to display / offer darkened art as RG cover art
  lib/MusicBrainz/Server/Controller/ReleaseGroup.pm
  lib/MusicBrainz/Server/Data/Artwork.pm
Labels: Bug

#2035 MBS-11500: Do not pass GID of removed release to avoid linking
  lib/MusicBrainz/Server/Edit/Release/AddCoverArt.pm
  root/edit/details/AddCoverArt.js
Labels: Bug

#2044 MBS-11564: Don't block Niconi Commons links with Nicovideo cleanup
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug

#2060 Fix Catalyst warning: ensure parent format id is not undef
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Release.pm
Labels: Refactoring

#2059 Fix Catalyst warning: don't try using undef to access hash
  lib/MusicBrainz/Server/Edit/Relationship/Create.pm
Labels: Refactoring

#2063 Add keys to EditReleaseEvents to stop warning
  root/edit/details/historic/EditReleaseEvents.js
Labels: Refactoring

#2023 MBS-11533: Block smart links: snd.click
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#2016 MBS-11527: Block smart links: music.indiefy.net
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#2062 Fix Catalyst warning: don't try undef linktype id to access $loaded
  lib/MusicBrainz/Server/Edit/Relationship/Delete.pm
Labels: Refactoring

#2065 MBS-11582: Add a sortname method for instrument guess case
  root/static/scripts/guess-case/MB/GuessCase/Main.js
Labels: Bug

#2054 MBS-9631: Add 1200px to available image sizes
  lib/MusicBrainz/Server/Entity/Artwork.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Utils.pm
  root/components/Artwork.js
  root/release/CoverArt.js
  root/types.js
  t/lib/t/MusicBrainz/Server/Controller/Release/CoverArt.pm
Labels: New feature

#2048 MBS-11569: Limit entity types when creating collection from sidebar
  lib/MusicBrainz/Server/Controller/Collection.pm
  lib/MusicBrainz/Server/Form/Collection.pm
Labels: Bug

#2066 MBS-11583: Use sanitized context in hydrated component
  root/components/list/RecordingList.js
Labels: Regression/Beta

#2033 MBS-11542 / MBS-11552: Allow and cleanup new Classical Archives links + add validation
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#2070 MBS-11603: Finetune DNB validation
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Regression/Beta

#2042 Pass public editor privs when converting editor to JSON
  lib/MusicBrainz/Server/Constants.pm
  lib/MusicBrainz/Server/Entity/Editor.pm
  root/utility/sanitizedEditor.js
Labels: Refactoring

#2025 MBS-11546: Allow Resident Advisor /exchange URLs for releases
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2028 Remove now unneeded old RA checks
  lib/MusicBrainz/Server/Data/URL.pm
  root/static/scripts/common/constants.js
Labels: QoL

#2051 MBS-9251: Display ended places differently on the map
  root/static/images/leaflet/ended-marker-icon-2x.png
  root/static/images/leaflet/ended-marker-icon.png
  root/static/scripts/area/places-map.js
  root/static/scripts/common/leaflet.js
Labels: New feature

#2056 MBS-1588: Better errors for invalid CD TOC
  lib/MusicBrainz/Server/Controller/CDTOC.pm
Labels: QoL

#2052 MBS-11573: Load collections for ratings sidebars
  lib/MusicBrainz/Server/Controller/Artist.pm
  lib/MusicBrainz/Server/Controller/Event.pm
  lib/MusicBrainz/Server/Controller/Label.pm
  lib/MusicBrainz/Server/Controller/Recording.pm
  lib/MusicBrainz/Server/Controller/ReleaseGroup.pm
  lib/MusicBrainz/Server/Controller/Work.pm
Labels: Bug

#2049 MBS-11571: Warn about e-mail as a username
  root/account/register.tt
  root/static/scripts/register.js
  root/static/styles/forms.less
  webpack.client.config.js
Labels: QoL

#2032 MBS-11550: Move PostParameters to static/scripts for translation
  root/main/ConfirmSeed.js
  root/static/scripts/common/components/PostParameters.js
  root/static/scripts/confirm-seed.js
  root/static/scripts/user/login.js
  root/static/styles/forms.less
  root/user/Login.js
Labels: Bug

#2037 MBS-11559: Specify tracklist is empty in Remove medium edits
  root/edit/details/AddMedium.js
  root/edit/details/RemoveMedium.js
Labels: QoL

#2046 MBS-9259: Add help section for the track parser
  root/release/edit/tracklist.tt
  root/static/scripts/release-editor/trackParser.js
Labels: QoL

#2067 MBS-10899: Report for releases with catnos that look like ISRCs
  lib/MusicBrainz/Server/Report/CatNoLooksLikeISRC.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/CatNoLooksLikeIsrc.js
  root/report/ReportsIndex.js
  root/server/components.js
Labels: New feature

#2072 MBS-11611: Do not keep/add trailing slash in OC ReMix URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2071 MBS-11604: Add genre name to genre index title
  root/genre/GenreLayout.js
Labels: QoL

#2073 MBS-11612: Restore link to genre/delete to genre sidebar
  lib/MusicBrainz/Server/Controller/Genre.pm
  lib/MusicBrainz/Server/Data/Genre.pm
Labels: Bug

#2077 MBS-11587: Block smart links: hypel.ink
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#2076 MBS-11590: Standardize display of empty fields in cover art edits
  root/edit/details/AddCoverArt.js
  root/edit/details/RemoveCoverArt.js
Labels: QoL

#2064 Fix catalyst warning: don't try to trim/sanitize undef "strings"
  lib/MusicBrainz/Server/Controller/ReleaseEditor.pm
  lib/MusicBrainz/Server/Data/ArtistCredit.pm
  lib/MusicBrainz/Server/Data/Utils.pm
  lib/MusicBrainz/Server/Edit/Generic/Edit.pm
Labels: Refactoring

#2074 MBS-11619: Ignore periods and +tags in e-mail admin searches
  lib/MusicBrainz/Server/Data/Editor.pm
  root/admin/EmailSearch.js
Labels: QoL

#2041 MBS-9376: Indicate that edit searches can be bookmarked + link docs
  root/edit/search.tt
  root/edit/search_macros.tt
  root/edit/search_results.tt
Labels: QoL

#2069 MBS-11598: Do not generate image link if we don't have a suffix
  lib/MusicBrainz/Server/Entity/Artwork.pm
  root/types.js
Labels: Bug
