Repository metabrainz/musicbrainz-server, pull requests merged in 2021-12, with the labels that each got.

#2356 MBS-12112: Remove unneeded escape for $
  lib/MusicBrainz/Server/Report/CatNoLooksLikeASIN.pm
  lib/MusicBrainz/Server/Report/CatNoLooksLikeISRC.pm
  lib/MusicBrainz/Server/Report/CatNoLooksLikeLabelCode.pm
  lib/MusicBrainz/Server/Report/DuplicateReleaseGroups.pm
Labels: Regression/Beta

#2342 MBS-12097: Show total edit count on user pages
  root/user/UserProfile.js
Labels: QoL

#2355 MBS-12115: Don't show deleted users' Subscription tab to admins
  root/components/UserAccountTabs.js
Labels: Regression/Beta

#2341 Replace && with if/ternary
  root/entity/Details.js
  root/layout/components/MergeHelper.js
  root/layout/index.js
  root/static/scripts/common/artworkViewer.js
  root/static/scripts/common/utility/request.js
  root/static/scripts/edit/components/HelpIcon.js
  root/static/scripts/edit/components/URLInputPopover.js
  root/static/scripts/edit/externalLinks.js
Labels: Refactoring

#2354 MBS-12114: Account for the "Disk" alternative spelling to "Disc"
  lib/MusicBrainz/Server/Report/MediumsWithOrderInTitle.pm
  root/static/scripts/release-editor/fields.js
Labels: QoL

#2253 MBS-11942: Deleted users can still use pending verification links
  lib/MusicBrainz/Server/Controller/Account.pm
Labels: Bug

#2346 MBS-12083: Add caching to get_types_for_timeline
  lib/MusicBrainz/Server/Data/Relationship.pm
Labels: Regression/Beta

#2358 MBS-12117: Use CSS specificity to fix error highlighting in RE tabs
  root/static/styles/layout.less
Labels: Regression/Beta

#2339 MBS-11980: Test relationship types restriction in external links editor
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#2313 More eslint fixes
  .eslintrc.unfixed.yaml
  .eslintrc.yaml
  root/server.js
  root/server/createServer.js
  root/server/gettext.js
  root/server/gettext/poFile.js
  root/server/response.js
  root/static/scripts/common.js
  root/static/scripts/common/MB/Control/Autocomplete.js
  root/static/scripts/common/artworkViewer.js
  root/static/scripts/common/components/CollapsibleList.js
  root/static/scripts/common/components/sidebar/AcousticBrainz.js
  root/static/scripts/common/i18n/expand2text.js
  root/static/scripts/common/utility/formatTrackLength.js
  root/static/scripts/edit/MB/CoverArt.js
  root/static/scripts/edit/MB/edit.js
  root/static/scripts/edit/check-duplicates.js
  root/static/scripts/edit/components/ExternalLinkAttributeDialog.js
  root/static/scripts/edit/components/URLInputPopover.js
  root/static/scripts/edit/externalLinks.js
  root/static/scripts/edit/utility/linkPhrase.js
  root/static/scripts/edit/validation.js
  root/static/scripts/jed-data.js
  root/static/scripts/relationship-editor/common/fields.js
  root/static/scripts/relationship-editor/generic.js
  root/static/scripts/release-editor/fields.js
  root/static/scripts/release-editor/init.js
  root/static/scripts/tests/release-editor/edits.js
  root/static/scripts/tests/release-editor/validation.js
  root/static/scripts/timeline.js
  root/static/scripts/voting.js
  t/selenium.js
  t/web.js
  webpack/browserConfig.js
  webpack/client.config.js
  webpack/server.config.js
  webpack/tests.config.js
Labels: Refactoring

#2316 MBS-12056: Convert the edit data page to React
  lib/MusicBrainz/Server/Controller/Edit.pm
  lib/MusicBrainz/Server/Entity/Util/JSON.pm
  root/components/common-macros.tt
  root/edit/EditData.js
  root/edit/data.tt
  root/server/components.js
Labels: React

#2347 MBS-9375: Restrict Apple Music to paid streaming and/or purchase
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2359 Use text versions of functions
  root/account/applications/Index.js
  root/artist_credit/ArtistCreditIndex.js
  root/components/FormRowSelectList.js
  root/components/RelationshipsTable.js
  root/edit/components/EditHeader.js
  root/edit/details/AddAnnotation.js
  root/edit/details/AddArea.js
  root/edit/details/AddCoverArt.js
  root/edit/details/AddEvent.js
  root/edit/details/AddRelationshipType.js
  root/edit/details/EditAlias.js
  root/edit/details/EditRelationshipType.js
  root/edit/details/EditRelease.js
  root/edit/details/RemoveCoverArt.js
  root/edit/details/RemoveMedium.js
  root/edit/details/RemoveRelationshipType.js
  root/edit/details/historic/AddReleaseAnnotation.js
  root/layout/components/Footer.js
  root/relationship/linkattributetype/RelationshipAttributeTypeInUse.js
  root/relationship/linktype/RelationshipTypeInUse.js
  root/relationship/linktype/RelationshipTypePairTree.js
  root/relationship/linktype/RelationshipTypesList.js
  root/search/components/ResultsLayout.js
  root/static/scripts/area/places-map.js
  root/static/scripts/common/MB/Control/Autocomplete.js
  root/static/scripts/common/components/ArtistRoles.js
  root/static/scripts/common/components/EntityLink.js
  root/static/scripts/common/components/Warning.js
  root/static/scripts/common/entity.js
  root/static/scripts/release-editor/dialogs.js
  root/static/scripts/release-editor/fields.js
  root/statistics/Edits.js
  root/statistics/Index.js
  root/user/UserCollections.js
  root/user/UserProfile.js
Labels: Refactoring

#2321 MBS-7727: Restrict Soundcloud to only "get the music" rels
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#2290 MBS-11995: Test error messages in external links editor
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Refactoring

#2370 MBS-12133: Allow % in jazzmusicarchives URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug

#1630 MBS-10715 / MBS-10716: Block Amazon and Apple redirect links
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2363 Use a valid SPDX License expression
  package.json
Labels: Bug
