Repository metabrainz/musicbrainz-server, pull requests merged in 2022-07, with the labels that each got.

#2581 MBS-12484: Fix genre alias edit links display
  root/components/Aliases/index.js
Labels: Regression/Beta

#2580 MBS-12477: Hide "Log in to edit" for privileged editor-only entities
  root/layout/components/sidebar/AreaSidebar.js
  root/layout/components/sidebar/EditLinks.js
  root/layout/components/sidebar/GenreSidebar.js
  root/layout/components/sidebar/InstrumentSidebar.js
Labels: QoL

#2579 MBS-12480 / MBS-12481: Support area-genre relationships
  lib/MusicBrainz/Server/Controller/Area.pm
  root/static/scripts/common/entity.js
  root/static/scripts/relationship-editor/common/viewModel.js
Labels: New feature

#2565 MBS-12457: Wrap overly long words in annotations
  root/edit/details/AddAnnotation.js
  root/static/styles/layout.less
Labels: QoL

#2555 MBS-12418: Also format artists in setlists if there's no MBID link
  root/static/scripts/common/utility/formatSetlist.js
  root/static/scripts/tests/utility.js
Labels: QoL

#2584 MBS-12490 / MBS-12491 / MBS-12492: More genre autoselects
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2592 MBS-12512: Dump genre_alias_type for sample DB
  lib/MusicBrainz/Script/SampleDataDump.pm
Labels: Bug

#2594 MBS-12515: Check _gid_redirect table exists before trying to use it
  lib/MusicBrainz/Script/EntityDump.pm
Labels: Bug

#2570 MBS-12403: Generate diagrams for the database schema documentation
  docs/database_schema_diagrams/Makefile
  docs/database_schema_diagrams/README.md
  docs/database_schema_diagrams/graphs/area_entity_details.dot
  docs/database_schema_diagrams/graphs/artist_entity_details.dot
  docs/database_schema_diagrams/graphs/cdstub_details.dot
  docs/database_schema_diagrams/graphs/cover_art_details.dot
  docs/database_schema_diagrams/graphs/entity_network_details.dot
  docs/database_schema_diagrams/graphs/entity_network_overview.dot
  docs/database_schema_diagrams/graphs/event_entity_details.dot
  docs/database_schema_diagrams/graphs/genre_entity_details.dot
  docs/database_schema_diagrams/graphs/instrument_entity_details.dot
  docs/database_schema_diagrams/graphs/label_entity_details.dot
  docs/database_schema_diagrams/graphs/place_entity_details.dot
  docs/database_schema_diagrams/graphs/recording_entity_details.dot
  docs/database_schema_diagrams/graphs/relationship_details.dot
  docs/database_schema_diagrams/graphs/relationship_overview.dot
  docs/database_schema_diagrams/graphs/release_entity_details.dot
  docs/database_schema_diagrams/graphs/release_group_entity_details.dot
  docs/database_schema_diagrams/graphs/series_entity_details.dot
  docs/database_schema_diagrams/graphs/url_entity_details.dot
  docs/database_schema_diagrams/graphs/work_entity_details.dot
  docs/database_schema_diagrams/images/area_entity_details.svg
  docs/database_schema_diagrams/images/artist_entity_details.svg
  docs/database_schema_diagrams/images/cdstub_details.svg
  docs/database_schema_diagrams/images/cover_art_details.svg
  docs/database_schema_diagrams/images/entity_network_details.svg
  docs/database_schema_diagrams/images/entity_network_overview.svg
  docs/database_schema_diagrams/images/event_entity_details.svg
  docs/database_schema_diagrams/images/genre_entity_details.svg
  docs/database_schema_diagrams/images/instrument_entity_details.svg
  docs/database_schema_diagrams/images/label_entity_details.svg
  docs/database_schema_diagrams/images/place_entity_details.svg
  docs/database_schema_diagrams/images/recording_entity_details.svg
  docs/database_schema_diagrams/images/relationship_details.svg
  docs/database_schema_diagrams/images/relationship_overview.svg
  docs/database_schema_diagrams/images/release_entity_details.svg
  docs/database_schema_diagrams/images/release_group_entity_details.svg
  docs/database_schema_diagrams/images/series_entity_details.svg
  docs/database_schema_diagrams/images/url_entity_details.svg
  docs/database_schema_diagrams/images/work_entity_details.svg
  docs/database_schema_diagrams/source/area_entity_details.json
  docs/database_schema_diagrams/source/artist_entity_details.json
  docs/database_schema_diagrams/source/cdstub_details.json
  docs/database_schema_diagrams/source/cover_art_details.json
  docs/database_schema_diagrams/source/entity_network_details.json
  docs/database_schema_diagrams/source/entity_network_overview.json
  docs/database_schema_diagrams/source/event_entity_details.json
  docs/database_schema_diagrams/source/genre_entity_details.json
  docs/database_schema_diagrams/source/instrument_entity_details.json
  docs/database_schema_diagrams/source/label_entity_details.json
  docs/database_schema_diagrams/source/place_entity_details.json
  docs/database_schema_diagrams/source/recording_entity_details.json
  docs/database_schema_diagrams/source/relationship_details.json
  docs/database_schema_diagrams/source/relationship_overview.json
  docs/database_schema_diagrams/source/release_entity_details.json
  docs/database_schema_diagrams/source/release_group_entity_details.json
  docs/database_schema_diagrams/source/series_entity_details.json
  docs/database_schema_diagrams/source/url_entity_details.json
  docs/database_schema_diagrams/source/work_entity_details.json
  docs/database_schema_diagrams/write_graphs.pl
Labels: Documentation
