Repository metabrainz/musicbrainz-server, pull requests merged in 2022-05, with the labels that each got.

#2427 MBS-12208: Withdrawn releases should count as official for overview
  admin/sql/CreateFunctions.sql
  admin/sql/updates/20220218-mbs-12208.sql
  admin/sql/updates/schema-change/27.mirror.sql
  lib/MusicBrainz/Server/Data/ReleaseGroup.pm
  upgrade.json
Labels: QoL

#2476 MBS-12256: Keep meta rating columns up-to-date with triggers
  admin/GenerateSQLScripts.pl
  admin/InitDb.pl
  admin/sql/CreateFunctions.sql
  admin/sql/CreateTables.sql
  admin/sql/CreateTriggers.sql
  admin/sql/CreateTypes.sql
  admin/sql/DropAll.sql
  admin/sql/DropTypes.sql
  admin/sql/updates/20220322-mbs-12256-mirror.sql
  admin/sql/updates/20220322-mbs-12256-standalone.sql
  admin/sql/updates/schema-change/27.mirror.sql
  admin/sql/updates/schema-change/27.standalone.sql
  lib/MusicBrainz/Server/Data/Rating.pm
  script/create_test_db.sh
  t/lib/t/MusicBrainz/Server/Controller/Artist/Ratings.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Show.pm
  t/lib/t/MusicBrainz/Server/Data/Rating.pm
  t/pgtap/aggregate_ratings.sql
  t/sql/controller_artist.sql
  upgrade.json
Labels: New feature

#2248 dbmirror2 support
  .circleci/config.yml
  admin/ExportAllTables
  admin/GenerateSQLScripts.pl
  admin/InitDb.pl
  admin/RunExport
  admin/replication/ImportReplicationChanges
  admin/replication/LoadReplicationChanges
  admin/replication/ProcessReplicationChanges
  admin/sql/CreateReplicationTriggers2.sql
  admin/sql/DropFunctions.sql
  admin/sql/DropReplicationTriggers2.sql
  admin/sql/DropTriggers.sql
  admin/sql/DropTypes.sql
  admin/sql/caa/CreateReplicationTriggers2.sql
  admin/sql/dbmirror2/MasterSetup.sql
  admin/sql/dbmirror2/README
  admin/sql/dbmirror2/RefreshColumnInfo.sql
  admin/sql/dbmirror2/ReplicationSetup.sql
  admin/sql/documentation/CreateReplicationTriggers2.sql
  admin/sql/eaa/CreateReplicationTriggers2.sql
  admin/sql/statistics/CreateReplicationTriggers2.sql
  admin/sql/updates/20220328-mbs-12250-master.sql
  admin/sql/updates/20220328-mbs-12250-mirror.sql
  admin/sql/updates/schema-change/27.master_only.sql
  admin/sql/updates/schema-change/27.mirror.sql
  admin/sql/wikidocs/CreateReplicationTriggers2.sql
  docker/musicbrainz-tests/DBDefs.pm
  lib/DBDefs/Default.pm
  lib/MusicBrainz/Script/DatabaseDump.pm
  lib/MusicBrainz/Script/JSONDump/Incremental.pm
  lib/MusicBrainz/Script/MBDump.pm
  lib/MusicBrainz/Server/Data/CDTOC.pm
  script/database_exists
  t/script/ExportAllTables.t
  t/script/dbmirror2.t
  upgrade.json
  upgrade.sh
Labels: New feature

#2529 MBS-12380: Warn user about possible slow deletion
  root/admin/delete_user.tt
Labels: QoL

#2521 MBS-12212: Add filtering to artists' events tab
  lib/MusicBrainz/Server/Controller/Ajax.pm
  lib/MusicBrainz/Server/Controller/Artist.pm
  lib/MusicBrainz/Server/Data/Event.pm
  lib/MusicBrainz/Server/FilterUtils.pm
  lib/MusicBrainz/Server/Form/Filter/Event.pm
  root/artist/ArtistEvents.js
  root/static/scripts/common/components/FilterForm.js
  t/lib/t/MusicBrainz/Server/Controller/Artist/Filtering.pm
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
  t/sql/filtering.sql
Labels: New feature

#2535 MBS-12385: Add report for digital releases with mail order rels
  lib/MusicBrainz/Server/Report/ReleasesWithMailOrderRelationships.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/ReleasesWithMailOrderRelationships.js
  root/report/ReportsIndex.js
  root/server/components.js
Labels: New feature

#2517 MBS-12347: Also show RG artist in autocomplete if type is null
  root/static/scripts/common/MB/Control/Autocomplete.js
Labels: Bug

#2520 MBS-8875: Improve CatNoLooksLikeASIN regexp
  lib/MusicBrainz/Server/Report/CatNoLooksLikeASIN.pm
  root/static/scripts/release-editor/bubbles.js
Labels: Bug

#2519 MBS-11694: Cleanup /intent/user Twitter URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2513 MBS-4960 / MBS-12361: Allow navigation from donation check page and improve error handling
  lib/MusicBrainz/Server/Controller/Account.pm
  root/account/Donation.js
Labels: QoL

#2516 MBS-8193 / MBS-12332: Wrap absurdly long lines
  root/static/styles/layout.less
Labels: Bug

#2543 MBS-12398: Update release_meta.amazon_asin
  lib/MusicBrainz/Server/Constants.pm
  lib/MusicBrainz/Server/Data/Release.pm
  lib/MusicBrainz/Server/Edit/Relationship/Create.pm
  lib/MusicBrainz/Server/Edit/Relationship/Delete.pm
  lib/MusicBrainz/Server/Edit/Relationship/Edit.pm
  lib/MusicBrainz/Server/Edit/URL/Edit.pm
  t/lib/t/MusicBrainz/Server/Edit/Relationship/Create.pm
  t/lib/t/MusicBrainz/Server/Edit/Relationship/Delete.pm
  t/lib/t/MusicBrainz/Server/Edit/Relationship/Edit.pm
  t/lib/t/MusicBrainz/Server/Edit/URL/Edit.pm
  t/sql/edit_relationship_delete.sql
  t/sql/edit_relationship_edit.sql
Labels: Regression/Beta

#2548 MBS-12413: Use uri_escape_utf8 on Data::Wikidoc
  lib/MusicBrainz/Server/Data/WikiDoc.pm
Labels: Bug

#2546 MBS-12280 (II): Add target _blank to more edit form links
  root/event/edit_form.tt
  root/label/edit_form.tt
  root/place/edit_form.tt
  root/work/edit_form.tt
Labels: Bug

#2545 MBS-12407: Add tobarandualchais.co.uk to the other dbs whitelist (and as free streaming for recordings)
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/TobaranDualchais.pm
  root/static/images/external-favicons/tobar-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature

#2550 MBS-12387: Add titles to URL editor edit buttons
  root/static/scripts/edit/components/ExternalLinkAttributeDialog.js
  root/static/scripts/edit/components/URLInputPopover.js
Labels: QoL

#2547 MBS-12412: Fail gracefully if requesting an invalid ID in edit-cover-art
  lib/MusicBrainz/Server/Controller/Release.pm
Labels: Bug

#2501 MBS-12333: Block smart links: share.amuse.io
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#2509 MBS-12336: Validate that Predicate::Set is being passed integers
  lib/MusicBrainz/Server/EditSearch/Predicate/Set.pm
  t/lib/t/MusicBrainz/Server/EditSearch/Predicate/Set.pm
Labels: Bug

#2502 MBS-12328: Add #content to entity/Edits for artwork display
  root/entity/Edits.js
  root/static/scripts/common/artworkViewer.js
Labels: Bug
