Repository metabrainz/musicbrainz-server, pull requests merged in 2022-06, with the labels that each got.

#2556 MBS-12420: Support comma-separated IDs for edit search types again
  lib/MusicBrainz/Server/EditSearch/Predicate/EditIDSet.pm
  lib/MusicBrainz/Server/EditSearch/Predicate/Set.pm
  lib/MusicBrainz/Server/EditSearch/Query.pm
  root/edit/search_macros.tt
  t/lib/t/MusicBrainz/Server/EditSearch/Predicate/EditIDSet.pm
Labels: Regression/Beta

#2559 Use flushSync to avoid render lag (fixes MBS-12424)
  root/static/scripts/common/MB/Control/Autocomplete.js
  root/static/scripts/edit/check-duplicates.js
  root/static/scripts/edit/components/ArtistCreditEditor.js
  root/static/scripts/edit/components/forms.js
  root/static/scripts/edit/externalLinks.js
  root/static/scripts/release-editor/bindingHandlers.js
  root/static/scripts/work/edit.js
  root/utility/hydrate.js
Labels: Regression/Beta

#2561 MBS-12437 / MBS-12438: Limit overflow-wrap even more
  root/components/EntityHeader.js
  root/edit/details/EditUrl.js
  root/static/scripts/common/components/EntityLink.js
  root/static/styles/layout.less
Labels: Regression/Beta

#2558 MBS-12393: Change TOWER RECORDS to all-caps as per store Japanese usage
  lib/MusicBrainz/Server/Entity/URL/Tower.pm
Labels: QoL

#2563 MBS-12447: Also show area-series rels on series page
  lib/MusicBrainz/Server/Controller/Series.pm
Labels: Bug

#2552 MBS-12417: Update Soundcloud cleanup to remove ? parameters
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2560 MBS-12419: Block Genius.com links at release level
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2553 MBS-9188: Improve LinkedIn URL cleanup
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2562 MBS-12395: Report for videos in mediums that shouldn't support video
  lib/MusicBrainz/Server/Report/VideosInNonVideoMediums.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/ReportsIndex.js
  root/report/VideosInNonVideoMediums.js
  root/server/components.js
Labels: New feature

#2514 MBS-12350 / MBS-12352 / MBS-12383 / MBS-12396 / MBS-12401: Block more "smart" links
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#2441 Improve test documentation (VII): Shared tests (Aliases)
  admin/sql/InsertTestData.sql
  t/lib/t/MusicBrainz/Server/Controller/Area/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/AddAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/DeleteAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/EditAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/AddAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/DeleteAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/EditAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Place/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/AddAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/DeleteAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/EditAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Release/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Series/AddAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Series/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Series/DeleteAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Series/EditAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Work/Aliases.pm
  t/sql/area.sql
  t/sql/controller_artist.sql
  t/sql/controller_work.sql
  t/sql/place.sql
  t/sql/recording.sql
  t/sql/series.sql
Labels: Documentation, Tests

#2492 MBS-12311: Allow adding annotations to genres
  entities.json
  lib/MusicBrainz/Server/Constants.pm
  lib/MusicBrainz/Server/Controller/Genre.pm
  lib/MusicBrainz/Server/Data/Genre.pm
  lib/MusicBrainz/Server/Edit/Genre/AddAnnotation.pm
  lib/MusicBrainz/Server/EditRegistry.pm
  lib/MusicBrainz/Server/Entity/Genre.pm
  root/edit/utility/getEditDetailsElement.js
  root/genre/GenreIndex.js
  root/layout/components/sidebar/GenreSidebar.js
  root/static/scripts/common/constants/editTypes.js
  root/static/scripts/genre/index.js
  root/types/annotation.js
  root/types/edit_type_ids.js
  root/types/edit_types.js
  root/types/genre.js
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
  webpack/client.config.js
Labels: New feature

#2564 MBS-12453 / MBS-12455 / MBS-12456: Annotation react fixes
  lib/MusicBrainz/Server/Controller/Role/Annotation.pm
  root/annotation/AnnotationComparison.js
  root/annotation/AnnotationRevision.js
  root/static/scripts/annotation/AnnotationHistoryTable.js
  root/static/scripts/common/components/Annotation.js
  root/types/annotation.js
Labels: Bug, Regression/Beta

#2490 Fix the hydrate div name for AliasEditForm
  root/static/scripts/alias/AliasEditForm.js
Labels: Refactoring

#2497 MBS-11599: Allow adding URL relationships to genre pages
  entities.json
  lib/MusicBrainz/Server/Controller/Genre.pm
  lib/MusicBrainz/Server/Controller/Role/EditRelationships.pm
  lib/MusicBrainz/Server/Data/Genre.pm
  lib/MusicBrainz/Server/Entity/Genre.pm
  lib/MusicBrainz/Server/Form/Genre.pm
  root/genre/CreateGenre.js
  root/genre/EditGenre.js
  root/genre/GenreEditForm.js
  root/genre/GenreIndex.js
  root/layout/components/sidebar/GenreSidebar.js
  root/static/scripts/edit/externalLinks.js
  root/static/scripts/genre/components/GenreEditForm.js
  root/static/scripts/relationship-editor/common/viewModel.js
  root/static/scripts/relationship-editor/generic.js
  root/types/relationship.js
  webpack/client.config.js
Labels: New feature

#2568 MBS-12458: Error if trying to load annotation for wrong entity
  lib/MusicBrainz/Server/Controller/Role/Annotation.pm
Labels: Bug

#2449 Improve test documentation (VIII): Shared tests (Tags/Ratings)
  t/lib/t/MusicBrainz/Server/Controller/Area/Tags.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Ratings.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Tags.pm
  t/lib/t/MusicBrainz/Server/Controller/Instrument/Tags.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/Ratings.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/Tags.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/Ratings.pm
  t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Ratings.pm
  t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Tags.pm
  t/lib/t/MusicBrainz/Server/Controller/Series/Tags.pm
  t/lib/t/MusicBrainz/Server/Controller/Work/Ratings.pm
  t/lib/t/MusicBrainz/Server/Controller/Work/Tags.pm
  t/sql/controller_artist.sql
  t/sql/controller_ratings.sql
Labels: Documentation, Tests

#2575 Rewrite "Test X" test names
  t/lib/t/MusicBrainz/DataStore/Redis.pm
  t/lib/t/MusicBrainz/DataStore/RedisMulti.pm
  t/lib/t/MusicBrainz/Script/RemoveEmptyURLs.pm
  t/lib/t/MusicBrainz/Server/Controller/Admin/PrivilegeSearch.pm
  t/lib/t/MusicBrainz/Server/Controller/Area/Create.pm
  t/lib/t/MusicBrainz/Server/Controller/Area/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/AnnotationRevision.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Create.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/EditExternalLinks.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/EditRelationships.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Edits.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Filtering.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Recordings.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Relationships.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Releases.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Split.pm
  t/lib/t/MusicBrainz/Server/Controller/CDStub/Browse.pm
  t/lib/t/MusicBrainz/Server/Controller/CDStub/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/CDTOC/SetDurations.pm
  t/lib/t/MusicBrainz/Server/Controller/CDTOC/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/ISRC/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/ISWC/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Instrument/Artists.pm
  t/lib/t/MusicBrainz/Server/Controller/Instrument/Create.pm
  t/lib/t/MusicBrainz/Server/Controller/Instrument/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Instrument/Recordings.pm
  t/lib/t/MusicBrainz/Server/Controller/Instrument/Releases.pm
  t/lib/t/MusicBrainz/Server/Controller/Release/EditCoverArt.pm
  t/lib/t/MusicBrainz/Server/Controller/Release/ReorderCoverArt.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/GenreList.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/GenreList.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/TXT/GenreList.pm
  t/lib/t/MusicBrainz/Server/Edit/Relationship/Delete.pm
Labels: Tests

#2576 MBS-12474: Display Wikipedia extracts for genres
  lib/MusicBrainz/Server/Controller/Genre.pm
  root/genre/GenreIndex.js
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
Labels: New feature

#2577 MBS-12475: Add autoselect for Wikidata and RYM genre URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2573 MBS-12464: Also display event-work rels in Related Works
  root/components/RelatedWorks.js
Labels: Bug

#2578 Fix warning when displaying blank annotation text
  lib/MusicBrainz/Server/Edit/Annotation/Edit.pm
Labels: Bug

#2572 MBS-12470: Fix broken unknown language statistics
  lib/MusicBrainz/Server/Controller/Statistics.pm
  lib/MusicBrainz/Server/Data/Statistics.pm
  root/statistics/stats.js
Labels: Bug

#2498 MBS-12479: Add aliases for genres
  entities.json
  lib/MusicBrainz/Server/Constants.pm
  lib/MusicBrainz/Server/Controller/Genre.pm
  lib/MusicBrainz/Server/Controller/Search.pm
  lib/MusicBrainz/Server/Data/Genre.pm
  lib/MusicBrainz/Server/Data/GenreAliasType.pm
  lib/MusicBrainz/Server/Edit/Genre/AddAlias.pm
  lib/MusicBrainz/Server/Edit/Genre/DeleteAlias.pm
  lib/MusicBrainz/Server/Edit/Genre/EditAlias.pm
  lib/MusicBrainz/Server/EditRegistry.pm
  lib/MusicBrainz/Server/Entity/GenreAlias.pm
  lib/MusicBrainz/Server/Entity/Types.pm
  root/edit/utility/getEditDetailsElement.js
  root/static/scripts/common/constants/editTypes.js
  root/static/scripts/guess-case/MB/GuessCase/Main.js
  root/types/edit_type_ids.js
  root/types/edit_types.js
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
Labels: New feature

#2574 MBS-12472: Show genre edit history links for all users
  root/layout/components/sidebar/GenreSidebar.js
Labels: Bug
