Repository metabrainz/musicbrainz-server, pull requests merged in 2022-01, with the labels that each got.

#2380 MBS-12159: Add support for Amazon.pl
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/AmazonMusic.pm
  lib/MusicBrainz/Server/Report/BadAmazonURLs.pm
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2383 MBS-12167: Use returnToCurrentPage in UserSubscriptions action
  root/user/UserSubscriptions.js
Labels: QoL

#2315 MBS-12049: Convert the edit index page to React
  lib/MusicBrainz/Server/Controller/Edit.pm
  lib/MusicBrainz/Server/Entity/Vote.pm
  root/components/RequestLogin.js
  root/edit/EditIndex.js
  root/edit/details/diff_table.tt
  root/edit/details/macros.tt
  root/edit/index.tt
  root/edit/utility/getEditDetailsElement.js
  root/server/components.js
  root/types/vote.js
  t/lib/t/MusicBrainz/Server/Controller/Edit/Open.pm
  t/lib/t/MusicBrainz/Server/Controller/Edit/Show.pm
  t/sql/vote.sql
Labels: React

#2360 MBS-12121: Actually show parent changes in EditRelationshipType
  root/edit/details/EditRelationshipType.js
  root/types/edit_types.js
Labels: Bug

#2382 MBS-12142 / MBS-12164: Use formatCount in more places
  lib/MusicBrainz/Server/Controller/Tag.pm
  root/components/PaginatedResults.js
  root/tag/TagCloud.js
Labels: Bug

#2369 Respond with Bad Request for "invalid session ID"
  lib/MusicBrainz/Server/Controller/Root.pm
  t/lib/t/MusicBrainz/Server/Controller/Errors.pm
Labels: QoL

#2390 Delete CODE_OF_CONDUCT.md and use org default
  docs/CODE_OF_CONDUCT.md
Labels: Documentation

#2364 MBS-12127: Allow batch-changing all blank artist credits
  root/static/scripts/edit/components/ArtistCreditBubble.js
Labels: New feature

#2384 MBS-12161: Expand, not replace, FormHandler Text's validate
  lib/MusicBrainz/Server/Form/Field/Text.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/AddAnnotation.pm
Labels: Bug

#2385 MBS-12155: Filter out downvoted tags from JSON WS user-tags/genres
  lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Utils.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupTagsRatings.pm
  t/sql/webservice.sql
Labels: Bug

#2396 Fix regression in medium track count comparison
  root/static/scripts/release/components/TracklistAndCredits.js
Labels: Regression/Beta

#2293 MBS-11986 / MBS-12128: New account flag: Spammer
  lib/MusicBrainz/Server/Constants.pm
  lib/MusicBrainz/Server/Controller/Admin.pm
  lib/MusicBrainz/Server/Controller/User.pm
  lib/MusicBrainz/Server/Data/Editor.pm
  lib/MusicBrainz/Server/Entity/Editor.pm
  lib/MusicBrainz/Server/Form/Admin/EditUser.pm
  root/admin/edit_user.tt
  root/constants.js
  root/static/scripts/common/utility/privileges.js
  root/user/Login.js
  root/user/UserProfile.js
  t/lib/t/MusicBrainz/Server/Controller/User/Login.pm
Labels: New feature
