Repository metabrainz/musicbrainz-server, pull requests merged in 2022-08, with the labels that each got.

#2595 MBS-12520: Don't fail on removed annotations
  lib/MusicBrainz/Server/Edit/Annotation/Edit.pm
Labels: Bug

#2525 MBS-12042: Allow providing an edit note when editing annotation
  root/annotation/EditAnnotation.js
Labels: New feature

#2500 MBS-12334: Collapse ISRCs and ISWCs when there are too many
  root/components/list/RecordingList.js
  root/components/list/WorkList.js
  root/layout/components/sidebar/RecordingSidebar.js
  root/layout/components/sidebar/WorkSidebar.js
  root/search/components/RecordingResults.js
  root/static/scripts/common/components/IsrcList.js
  root/static/scripts/common/components/IswcList.js
  root/static/scripts/common/components/WorkListEntry.js
  root/utility/tableColumns.js
  webpack/client.config.mjs
Labels: QoL

#1930 MBS-10478: Show useful message if too large search result page requested
  root/search/components/PaginatedSearchResults.js
Labels: QoL

#2599 MBS-12527: Update DateTime::Locale to 1.35
  .circleci/config.yml
  cpanfile
  cpanfile.snapshot
  docker/musicbrainz-test-database/cpanfile.snapshot
  root/static/scripts/common/constants/locales.json
  script/dump_locales.pl
Labels: QoL

#2608 MBS-12544: Support Egypt and Saudi Arabia ASINs
  lib/MusicBrainz/Server/Report/BadAmazonURLs.pm
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#2609 MBS-12543: Add a TikTok exception for guess case
  root/static/scripts/guess-case/modes.js
  root/static/scripts/tests/GuessCase.js
Labels: QoL

#2610 MBS-12516: Block smart links: mez.ink
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#2611 MBS-12435: Block smart links: linkfly.to
  root/static/scripts/edit/externalLinks.js
Labels: QoL

#2593 MBS-12497: Drop AC redirects when last use is removed
  admin/cleanup/RemoveUnreferencedRows
  admin/cron/daily.sh
  admin/sql/CreateFunctions.sql
  admin/sql/CreateIndexes.sql
  admin/sql/CreateTables.sql
  admin/sql/updates/20220802-mbs-12497.sql
  admin/sql/updates/schema-change/28.mirror.sql
  lib/MusicBrainz/Script/RemoveUnreferencedRows.pm
  t/lib/t/MusicBrainz/Script/RemoveUnreferencedRows.pm
  t/lib/t/MusicBrainz/Server/Data/ArtistCredit.pm
  t/tests.t
  upgrade.json
Labels: Bug

#2614 MBS-12558: Block linking to Wikipedia User: pages
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#2613 MBS-12556: Don't enter annotation edits unless text changes
  lib/MusicBrainz/Server/Edit/Annotation/Edit.pm
  t/lib/t/MusicBrainz/Server/Edit/Artist/AddAnnotation.pm
Labels: Bug
