Repository metabrainz/musicbrainz-server, pull requests merged in 2022-10, with the labels that each got.

#2669 MBS-12647 / MBS-12648: Fix RG collection artist credit sort
  lib/MusicBrainz/Server/Data/ReleaseGroup.pm
  root/components/list/ReleaseGroupList.js
Labels: Bug

#2668 MBS-12645: Add guess case to genre edit form
  root/genre/types.js
  root/static/scripts/alias/AliasEditForm.js
  root/static/scripts/genre/components/GenreEditForm.js
Labels: QoL

#2666 MBS-12639: Also update countries.pot from the DB
  po/Makefile
  po/countries.pot
  po/instrument_descriptions.it.po
  po/instruments.it.po
  po/relationships.it.po
Labels: Bug

#2674 Some more eslint fixes
  .eslintrc.unfixed.yaml
  root/server.mjs
  root/server/components.mjs
  root/static/scripts/public-path.js
  root/vars.js
  script/xgettext.js
  t/selenium.mjs
  t/web.js
  webpack/cacheConfig.mjs
  webpack/client.config.mjs
  webpack/moduleConfig.mjs
  webpack/providePluginConfig.mjs
  webpack/run.mjs
  webpack/server.config.mjs
Labels: Refactoring

#2678 Make Autocomplete2 flow strict
  root/static/scripts/common/components/Autocomplete2.js
  root/static/scripts/edit/components/Multiselect.js
  root/static/scripts/relationship-editor/components/DialogAttribute/BooleanAttribute.js
  root/static/scripts/relationship-editor/components/DialogAttribute/MultiselectAttribute.js
  root/static/scripts/relationship-editor/components/DialogAttribute/TextAttribute.js
  root/static/scripts/relationship-editor/components/DialogAttributes.js
  root/static/scripts/relationship-editor/components/DialogDatePeriod.js
  root/static/scripts/relationship-editor/components/DialogEntityCredit.js
  root/static/scripts/relationship-editor/components/DialogLinkOrder.js
  root/static/scripts/relationship-editor/components/DialogLinkType.js
  root/static/scripts/relationship-editor/components/DialogPreview.js
  root/static/scripts/relationship-editor/components/DialogTargetEntity.js
  root/static/scripts/relationship-editor/components/DialogTargetType.js
  root/static/scripts/relationship-editor/hooks/useEntityNameFromField.js
  root/static/scripts/relationship-editor/types/actions.js
Labels: Refactoring

#2696 MBS-12674: Don't assume offset data exists
  lib/MusicBrainz/Server/Entity/CDStub.pm
  root/static/scripts/common/utility/calculateFullToc.js
  root/types/cdstub.js
  t/selenium.mjs
  t/selenium/CD_Stub_Search.json5
Labels: Regression/Beta

#2697 MBS-12672: Add "Genre" to edit search like other entities
  root/edit/search_macros.tt
Labels: New feature

#2687 MBS-12666: Better edit display for stream for free external links
  root/static/scripts/edit/externalLinks.js
  t/selenium/External_Links_Editor.json5
Labels: QoL

#2701 Use Perl::Critic::Moose::ProhibitNewMethod
  .circleci/config.yml
  .perlcriticrc
  HACKING-PROD.md
  cpanfile
  cpanfile.snapshot
  docker/Dockerfile.tests
Labels: Refactoring

#2709 MBS-12681: Support YouTube Handle
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL
