Repository metabrainz/musicbrainz-server, pull requests merged in 2022-12, with the labels that each got.

#2746 MBS-12716: Output the right JSON-LD @context
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD.pm
  t/lib/t/MusicBrainz/Server/Controller/Area/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Area/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Recordings.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Relationships.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Place/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Place/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Release/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Release/CoverArt.pm
  t/lib/t/MusicBrainz/Server/Controller/Release/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Work/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Work/Show.pm
Labels: Bug

#2711 MBS-12685: Avoild ISE because of concurrent rating transactions
  lib/MusicBrainz/Server/Data/Rating.pm
  t/lib/t/MusicBrainz/Server/Controller/Rating.pm
Labels: Bug

#2722 MBS-10614: Remove edit note / vote restrictions for beginners
  lib/MusicBrainz/Server/Data/Vote.pm
  lib/MusicBrainz/Server/Edit.pm
  root/user/UserProfile.js
  root/utility/edit.js
  t/lib/t/MusicBrainz/Server/Controller/Edit/Show.pm
Labels: QoL

#2759 MBS-12735: Handle Boomplay URL for both editing and rendering
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/Boomplay.pm
  root/static/images/external-favicons/boomplay-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: QoL

#2760 Fix an ISE when displaying Audiomack link in the sidebar
  lib/MusicBrainz/Server/Entity/URL/Audiomack.pm
Labels: Regression/Beta

#2765 MBS-12778: Don't block area removal based on open edits
  lib/MusicBrainz/Server/Data/Area.pm
Labels: Bug

#2770 MBS-12780: Fix allowNew check for AddRelationship
  lib/MusicBrainz/Server/Edit/Relationship/Create.pm
  root/edit/details/AddRelationship.js
  root/types/edit_types.js
Labels: Bug

#2636 MBS-12205: Add "play on ListenBrainz" button
  root/collection/CollectionIndex.js
  root/collection/CollectionLayout.js
  root/layout/components/sidebar/CollectionSidebar.js
  root/layout/components/sidebar/PlayOnListenBrainzButton.js
  root/layout/components/sidebar/RecordingSidebar.js
  root/layout/components/sidebar/ReleaseGroupSidebar.js
  root/layout/components/sidebar/ReleaseSidebar.js
  root/release_group/ReleaseGroupIndex.js
  root/release_group/ReleaseGroupLayout.js
  root/static/images/icons/listenbrainz.png
  root/static/styles/layout.less
Labels: New feature
