Repository metabrainz/musicbrainz-server, pull requests merged in 2022-02, with the labels that each got.

#2401 MBS-11532: Don't pass undef ISO variable to localizeAreaName
  root/static/scripts/common/entity.js
Labels: Bug

#2388 MBS-12168: Avoid breaking list formatting on user bios and collections
  lib/MusicBrainz/Server/Form/Collection.pm
  lib/MusicBrainz/Server/Form/Role/UserProfile.pm
Labels: Bug

#2397 MBS-2313: Avoid pointless empty annotation edits
  root/static/scripts/release-editor/fields.js
Labels: Bug

#2381 MBS-12147: State that an email search had no results
  lib/MusicBrainz/Server/Controller/Admin.pm
  root/admin/EmailSearch.js
Labels: QoL

#2386 MBS-12160: Use 'canonical' to display sorted edit data JSON
  lib/MusicBrainz/Server/Controller/Edit.pm
Labels: QoL

#2407 MBS-12187: Load ReleaseEvents with manifest in release merges
  root/release/merge.tt
Labels: Bug

#2404 MBS-12188: Allow SNAC links for places
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#2367 MBS-12092: Serialize edit_action form after errors are added
  lib/MusicBrainz/Server/Controller.pm
  lib/MusicBrainz/Server/Controller/Role/Alias.pm
Labels: Regression/Beta

#2399 Check and improve documentation for our tests
  .circleci/config.yml
  t/author/eol.t
  t/author/notabs.t
  t/lib/t/MusicBrainz/DataStore/Redis.pm
  t/lib/t/MusicBrainz/Script/RemoveEmptyURLs.pm
  t/lib/t/MusicBrainz/Server/Authentication/WS.pm
  t/lib/t/MusicBrainz/Server/Controller/Admin/DeleteEditor.pm
  t/lib/t/MusicBrainz/Server/Controller/Admin/WikiDoc/Create.pm
  t/lib/t/MusicBrainz/Server/Controller/Admin/WikiDoc/Delete.pm
  t/lib/t/MusicBrainz/Server/Controller/Admin/WikiDoc/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Area/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Area/Create.pm
  t/lib/t/MusicBrainz/Server/Controller/Area/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Area/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Area/Tags.pm
  t/lib/t/MusicBrainz/Server/Controller/Area/Users.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/AddAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/AnnotationRevision.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Create.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/DeleteAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Details.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/EditAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/EditExternalLinks.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/EditRelationships.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Edits.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Merge.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/OpenEdits.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Ratings.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Recordings.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Relationships.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Releases.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Split.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Tags.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Works.pm
  t/lib/t/MusicBrainz/Server/Data/Gender.pm
  t/lib/t/MusicBrainz/Server/Entity/Artist.pm
  t/lib/t/MusicBrainz/Server/Entity/Label.pm
Labels: Documentation

#2406 MBS-12189: Support "names" prefix for DAHR artists
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature

#2408 MBS-12191: Allow admins to see spammer profiles
  root/user/UserProfile.js
  t/lib/t/MusicBrainz/Server/Controller/User/Show.pm
Labels: QoL

#2387 MBS-12162: Do not require auth for non-private tag WS queries
  lib/MusicBrainz/Server/WebService/Validator.pm
Labels: Bug

#2417 Eslint fixes: react/prefer-stateless-function
  .eslintrc.unfixed.yaml
  .eslintrc.yaml
  root/static/scripts/common/components/TagEditor.js
  root/static/scripts/edit/components/PossibleDuplicates.js
  root/static/scripts/edit/components/RemoveButton.js
  root/static/scripts/edit/externalLinks.js
Labels: Refactoring

#2425 MBS-12203 / MBS-12204: Changes for new non-binary gender option
  lib/MusicBrainz/Server/Data/Statistics.pm
  root/static/scripts/account/components/EditProfileForm.js
  root/statistics/Index.js
  root/statistics/stats.js
Labels: New feature

#2418 Add a HACKING-PROD file and document cpanfile updates
  HACKING-PROD.md
Labels: Documentation

#2423 MBS-12202: Allow parens on JazzMusicArchives URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug

#2421 MBS-12138: Drop parens from Amazon Music pretty name
  lib/MusicBrainz/Server/Entity/URL/AmazonMusic.pm
Labels: QoL

#2420 MBS-10668: Add autoselect + sidebar for TikTok URLs
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/TikTok.pm
  root/static/images/external-favicons/tiktok-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature

#2391 Improve URLCleanup test docs
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Documentation

#2419 MBS-11742: Also clean non-/user YouTube channels
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2410 Remove MooseX::ABC
  cpanfile
  lib/MusicBrainz/Server/CoverArt.pm
  lib/MusicBrainz/Server/CoverArt/Provider.pm
  lib/MusicBrainz/Server/CoverArt/Provider/RegularExpression.pm
  lib/MusicBrainz/Server/CoverArt/Provider/WebService/Amazon.pm
  lib/MusicBrainz/Server/Edit/Alias/Delete.pm
  lib/MusicBrainz/Server/Edit/Alias/Edit.pm
  lib/MusicBrainz/Server/Edit/Generic/Create.pm
  lib/MusicBrainz/Server/Edit/Generic/Delete.pm
  lib/MusicBrainz/Server/Edit/Generic/Edit.pm
  lib/MusicBrainz/Server/Edit/Generic/Merge.pm
  lib/MusicBrainz/Server/Edit/Historic.pm
  lib/MusicBrainz/Server/Edit/WithDifferences.pm
Labels: Refactoring

#2422 MBS-12201: Show any non-part-of rels on series page
  lib/MusicBrainz/Server/Controller/Series.pm
Labels: Bug

#2431 MBS-12215 / MBS-12216: Load annotation entity when possible on search results
  lib/MusicBrainz/Server/Data/Search.pm
Labels: Bug

#2414 MBS-12195: Drop AcousticBrainz-related code
  lib/MusicBrainz/Server.pm
  root/entity/Details.js
  root/layout/components/sidebar/RecordingSidebar.js
  root/static/scripts/common.js
  root/static/scripts/common/components/sidebar/AcousticBrainz.js
Labels: QoL

#2402 MBS-12183: Display previous value of annotation in AddAnnotation edits
  lib/MusicBrainz/Server/Edit/Annotation/Edit.pm
  root/edit/details/AddAnnotation.js
  root/types/edit_types.js
  t/lib/t/MusicBrainz/Server/Controller/Artist/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Controller/Release/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Controller/Series/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Work/AddAnnotation.pm
  t/selenium/release-editor/The_Downward_Spiral.json5
Labels: QoL

#2424 Improve test documentation (IV): Controller::Edit
  t/lib/t/MusicBrainz/Server/Controller/Edit/Cancel.pm
  t/lib/t/MusicBrainz/Server/Controller/Edit/Open.pm
  t/lib/t/MusicBrainz/Server/Controller/Edit/Show.pm
Labels: Tests

#2430 MBS-12214: Allow BBC /events links as otherDBs for events
  root/static/images/external-favicons/bbc-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature

#2345 MBS-7912: Add edit search option "edit [not] in subscriptions"
  lib/MusicBrainz/Server/EditSearch/Predicate/EditSubscription.pm
  lib/MusicBrainz/Server/EditSearch/Query.pm
  root/edit/search_macros.tt
  root/static/scripts/common/MB/edit_search.js
Labels: New feature

#2432 Implement "not in my subscriptions" predicate
  lib/MusicBrainz/Server/EditSearch/Predicate/EditSubscription.pm
Labels: Regression/Beta
