Repository metabrainz/musicbrainz-server, pull requests merged in 2022-11, with the labels that each got.

#2705 MBS-12673: Make it clearer that genres are added as tags
  root/layout/components/sidebar/SidebarTags.js
  root/static/scripts/common/components/TagEditor.js
  root/static/styles/layout.less
Labels: QoL

#2710 Fix Perl type constraint issues in Selenium tests
  lib/MusicBrainz/Server/Edit/Event/DeleteAlias.pm
  lib/MusicBrainz/Server/Edit/Genre/DeleteAlias.pm
  lib/MusicBrainz/Server/Edit/Instrument/DeleteAlias.pm
  lib/MusicBrainz/Server/Edit/Label/DeleteAlias.pm
  lib/MusicBrainz/Server/Edit/Series/DeleteAlias.pm
  lib/MusicBrainz/Server/Entity/Subscription/Artist.pm
  lib/MusicBrainz/Server/Entity/Subscription/Label.pm
  lib/MusicBrainz/Server/Entity/Subscription/Series.pm
Labels: Refactoring

#2717 MBS-12552 (III): Move Entity::Role::Linkable to Relatable
  lib/MusicBrainz/Server/Entity/CoreEntity.pm
  lib/MusicBrainz/Server/Entity/Relationship.pm
  lib/MusicBrainz/Server/Entity/Role/Relatable.pm
  lib/MusicBrainz/Server/Entity/Types.pm
Labels: Refactoring

#2721 MBS-12703: Add genre l_ tables to @CORE_TABLE_LIST
  lib/MusicBrainz/Server/Constants.pm
Labels: Bug

#2728 Generate SQL scripts for unreferenced_row_log
  admin/sql/CreatePrimaryKeys.sql
  admin/sql/DropIndexes.sql
  admin/sql/DropPrimaryKeys.sql
  admin/sql/DropTables.sql
  admin/sql/TruncateTables.sql
Labels: Bug

#2738 Fix warnings in DAOLogger
  lib/Plack/Middleware/Debug/DAOLogger.pm
Labels: Refactoring

#2713 MBS-12687: Block smart links: allmylinks.com
  root/static/scripts/edit/utility/isShortenedUrl.js
Labels: QoL

#2744 MBS-12713: Add KBR to the other databases whitelist
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/KBR.pm
  root/static/images/external-favicons/kbr-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature

#2743 MBS-12445: Handle Audiomack URLs
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/Audiomack.pm
  root/static/images/external-favicons/audiomack-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature

#2749 MBS-12722: Add IdRef to the other databases whitelist
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/IdRef.pm
  root/static/images/external-favicons/idref-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature
