Repository metabrainz/musicbrainz-server, pull requests merged in 2022-04, with the labels that each got.

#2474 MBS-12294: Also run artworkViewer on edit lists
  root/static/scripts/common/artworkViewer.js
Labels: Bug

#2444 MBS-12241: Drop the whitespace_collapsed database constraint
  admin/sql/CreateFunctions.sql
  admin/sql/DropFunctions.sql
  admin/sql/updates/20220309-mbs-12241.sql
  admin/sql/updates/schema-change/27.standalone.sql
  t/pgtap/constraints.sql
  t/pgtap/whitespace-functions.sql
  upgrade.json
Labels: Bug

#2466 MBS-11879: Fail better when trying to add deleted entity to collection
  lib/MusicBrainz/Server/Controller/Collection.pm
  t/lib/t/MusicBrainz/Server/Controller/Collection/AddAndRemove.pm
Labels: QoL, Bug

#2478 Delete new triggers if exist before creating
  admin/sql/updates/20210702-mbs-11760.sql
  admin/sql/updates/schema-change/27.standalone.sql
Labels: Bug

#2485 MBS-12305: Allow editing/translating instrument (root) rel attribute
  lib/MusicBrainz/Server/Controller/Relationship/LinkAttributeType.pm
  po/extract_pot_db
  root/relationship/linkattributetype/RelationshipAttributeTypeIndex.js
  root/relationship/linkattributetype/RelationshipAttributeTypesList.js
Labels: Bug

#2467 MBS-12279 / MBS-12283 / MBS-12284: Drop more manual deletion options and fix related issues
  lib/MusicBrainz/Server/Controller/Event.pm
  lib/MusicBrainz/Server/Controller/Label.pm
  lib/MusicBrainz/Server/Controller/ReleaseGroup.pm
  root/label/delete.tt
  root/layout/components/sidebar/LabelSidebar.js
  root/release_group/delete.tt
  t/lib/t/MusicBrainz/Server/Controller/Label/Delete.pm
Labels: QoL, Bug

#2482 MBS-12303: Display non-diff annotation data over all columns
  root/edit/details/AddAnnotation.js
Labels: Bug

#2483 MBS-12304: Only run guess feat on nonempty names
  root/static/scripts/edit/utility/guessFeat.js
Labels: Bug

#2479 MBS-12298: Update to new triplejunearthed domain
  lib/MusicBrainz/Server/Data/URL.pm
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2484 MBS-12302: Speed up large annotation diffing
  lib/MusicBrainz/Server/Sitemap/Overall.pm
  package.json
  root/edit/details/AddAnnotation.js
  root/static/scripts/edit/components/edit/DiffSide.js
  root/static/scripts/edit/utility/editDiff.js
  t/lib/t/MusicBrainz/Server/Controller/Artist/AddAnnotation.pm
  yarn.lock
Labels: Bug, Regression/Beta

#2437 MBS-12225: Change terminology from "slave" to "mirror"
  .gitignore
  INSTALL-MASTER.md
  INSTALL.md
  admin/BuildMaterializedTables
  admin/CompileSchemaScripts.pl
  admin/InitDb.pl
  admin/MBImport.pl
  admin/cron/mirror.sh
  admin/cron/slave.sh
  admin/nagios/check_last_replication_date
  admin/replication/LoadReplicationChanges
  admin/replication/ProcessReplicationChanges
  admin/sql/CreateFunctions.sql
  admin/sql/CreateSlaveOnlyFunctions.sql
  admin/sql/CreateSlaveOnlyTriggers.sql
  admin/sql/DropSlaveOnlyFunctions.sql
  admin/sql/DropSlaveOnlyTriggers.sql
  admin/sql/updates/20210311-mbs-1424-11438-mirror_only.sql
  admin/sql/updates/20210606-mbs-11682.sql
  admin/sql/updates/20220302-mbs-12225-mirror_only.sql
  admin/sql/updates/schema-change/20.mirror.sql
  admin/sql/updates/schema-change/21.mirror.sql
  admin/sql/updates/schema-change/22.mirror.sql
  admin/sql/updates/schema-change/22.mirror_only.sql
  admin/sql/updates/schema-change/23.mirror.sql
  admin/sql/updates/schema-change/23.mirror_only.sql
  admin/sql/updates/schema-change/24.mirror.sql
  admin/sql/updates/schema-change/25.mirror.sql
  admin/sql/updates/schema-change/26.mirror.sql
  admin/sql/updates/schema-change/26.mirror_only.sql
  admin/sql/updates/schema-change/27.mirror.sql
  admin/sql/updates/schema-change/27.mirror_only.sql
  admin/sql/updates/schema-change/27.standalone.sql
  lib/DBDefs.pm.sample
  lib/DBDefs/Default.pm
  lib/MusicBrainz/Server.pm
  lib/MusicBrainz/Server/Context.pm
  lib/MusicBrainz/Server/Controller/Role/ETags.pm
  lib/MusicBrainz/Server/Controller/Root.pm
  lib/MusicBrainz/Server/Controller/User.pm
  lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
  lib/MusicBrainz/Server/Data/Statistics.pm
  lib/MusicBrainz/Server/Replication.pm
  lib/MusicBrainz/Server/View/WS.pm
  root/layout.tt
  root/layout/index.js
  root/static/scripts/common/constants.js
  t/pgtap/materialized_artist_releases.sql
  upgrade.json
  upgrade.sh
Labels: Refactoring
