Repository metabrainz/musicbrainz-server, pull requests merged in 2023-03, with the labels that each got.

#2878 MBS-12958: Block voting without a confirmed email
  lib/MusicBrainz/Server/Edit.pm
  root/edit/components/EditHeader.js
  root/utility/edit.js
  t/lib/t/MusicBrainz/Server/Controller/Edit/Show.pm
  t/sql/vote.sql
Labels: Bug

#2872 MBS-11565: Use less hopeful image not available message
  root/components/Artwork.js
  root/components/common-macros.tt
Labels: QoL, Frontend-only

#2882 MBS-12962: Don't ISE on undef track_offset
  lib/MusicBrainz/Server/Entity/CDTOC.pm
Labels: Bug

#2877 MBS-12848: Reject inc=various-artists without inc=releases
  lib/MusicBrainz/Server/Controller/WS/2/Artist.pm
  lib/MusicBrainz/Server/WebService/Validator.pm
Labels: API

#2700 Refactor: Fix role’s name for pending edits
  lib/MusicBrainz/Server/Data/Alias.pm
  lib/MusicBrainz/Server/Data/Area.pm
  lib/MusicBrainz/Server/Data/Artist.pm
  lib/MusicBrainz/Server/Data/ArtistCredit.pm
  lib/MusicBrainz/Server/Data/Artwork.pm
  lib/MusicBrainz/Server/Data/Event.pm
  lib/MusicBrainz/Server/Data/Genre.pm
  lib/MusicBrainz/Server/Data/ISRC.pm
  lib/MusicBrainz/Server/Data/ISWC.pm
  lib/MusicBrainz/Server/Data/Instrument.pm
  lib/MusicBrainz/Server/Data/Label.pm
  lib/MusicBrainz/Server/Data/Medium.pm
  lib/MusicBrainz/Server/Data/MediumCDTOC.pm
  lib/MusicBrainz/Server/Data/Place.pm
  lib/MusicBrainz/Server/Data/Recording.pm
  lib/MusicBrainz/Server/Data/Release.pm
  lib/MusicBrainz/Server/Data/ReleaseGroup.pm
  lib/MusicBrainz/Server/Data/Role/Alias.pm
  lib/MusicBrainz/Server/Data/Role/PendingEdits.pm
  lib/MusicBrainz/Server/Data/Role/ValueSet.pm
  lib/MusicBrainz/Server/Data/Series.pm
  lib/MusicBrainz/Server/Data/Track.pm
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Data/Work.pm
  lib/MusicBrainz/Server/Edit.pm
  lib/MusicBrainz/Server/Edit/Generic/Create.pm
  lib/MusicBrainz/Server/Edit/Generic/Delete.pm
  lib/MusicBrainz/Server/Edit/Generic/Edit.pm
  lib/MusicBrainz/Server/Entity/Alias.pm
  lib/MusicBrainz/Server/Entity/Annotation.pm
  lib/MusicBrainz/Server/Entity/ArtistCredit.pm
  lib/MusicBrainz/Server/Entity/Artwork.pm
  lib/MusicBrainz/Server/Entity/CoreEntity.pm
  lib/MusicBrainz/Server/Entity/IPI.pm
  lib/MusicBrainz/Server/Entity/ISNI.pm
  lib/MusicBrainz/Server/Entity/ISRC.pm
  lib/MusicBrainz/Server/Entity/ISWC.pm
  lib/MusicBrainz/Server/Entity/Medium.pm
  lib/MusicBrainz/Server/Entity/MediumCDTOC.pm
  lib/MusicBrainz/Server/Entity/Relationship.pm
  lib/MusicBrainz/Server/Entity/Role/PendingEdits.pm
  lib/MusicBrainz/Server/Entity/Track.pm
  root/types/alias.js
  root/types/artwork.js
  root/types/codes.js
  root/types/entity.js
  root/types/relationship.js
  root/types/url.js
  t/lib/t/MusicBrainz/Server/Data/Alias.pm
  t/lib/t/MusicBrainz/Server/Data/Artist.pm
  t/lib/t/MusicBrainz/Server/Data/Instrument.pm
  t/lib/t/MusicBrainz/Server/Data/Place.pm
Labels: Refactoring

#2886 Allow for JSX in .mjs files
  .eslintrc.yaml
Labels: Refactoring

#2888 MBS-12978 / MBS-12980: Even more changes for DNB links
  lib/MusicBrainz/Server/Entity/URL/DNB.pm
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL, Bug, URL handling

#2895 MBS-12994: Treat email as case-insensitive for admin email search
  lib/MusicBrainz/Server/Data/Editor.pm
  t/lib/t/MusicBrainz/Server/Data/Editor.pm
Labels: QoL

#2880 MBS-12959: Only hide My vote in header for non-voting editors
  lib/MusicBrainz/Server/Data/Vote.pm
  lib/MusicBrainz/Server/Edit.pm
  lib/MusicBrainz/Server/Entity/Editor.pm
  root/edit/EditIndex.js
  root/edit/components/EditHeader.js
  root/edit/components/Vote.js
  root/utility/edit.js
Labels: Regression/Beta

#2862 MBS-12902: Add pagination to admin email/IP search
  lib/MusicBrainz/Server/Controller/Admin.pm
  lib/MusicBrainz/Server/Data/Editor.pm
  root/admin/EmailSearch.js
  root/admin/IpLookup.js
  t/lib/t/MusicBrainz/Server/Data/Editor.pm
Labels: QoL

#2900 MBS-13001: Actually set source_type and target_type for historic rels
  lib/MusicBrainz/Server/Edit/Historic/Relationship.pm
Labels: Regression/Beta

#1969 MBS-11393: Show SetTrackLengths edit in recording edit history
  lib/MusicBrainz/Server/Edit/Medium/SetTrackLengths.pm
  t/lib/t/MusicBrainz/Server/Controller/CDTOC/SetDurations.pm
  t/sql/controller_cdtoc.sql
Labels: QoL

#2641 MBS-12614: Better placement for Add collaborator button
  lib/MusicBrainz/Server/WebService/JSONSerializer.pm
  root/collection/types.js
  root/static/scripts/collection/components/CollectionEditForm.js
  root/static/scripts/common/components/Autocomplete2.js
  root/static/styles/forms.less
  t/lib/t/MusicBrainz/Server/Data/Collection.pm
Labels: QoL

#2170 MBS-11786: Add a text view of statistics events
  lib/MusicBrainz/Server/Controller/Statistics.pm
  root/admin/statistics-events/CreateStatisticsEvent.js
  root/admin/statistics-events/DeleteStatisticsEvent.js
  root/admin/statistics-events/EditStatisticsEvent.js
  root/admin/statistics-events/StatisticsEventEditForm.js
  root/admin/statistics-events/StatisticsEventIndex.js
  root/layout/components/BottomMenu.js
  root/server/components.mjs
  root/statistics/MusicBrainzHistory.js
  root/types/statisticsevents.js
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
Labels: New feature

#2903 MBS-12990: Don't pad the legend relationship editor fieldset
  root/static/scripts/relationship-editor/components/RelationshipEditor.js
  root/static/styles/relationship-editor.less
Labels: Regression/Beta, Frontend-only
