Repository metabrainz/musicbrainz-server, pull requests merged in 2023-07, with the labels that each got.

#2970 MBS-13130: Use new pencil icon
  root/static/images/attribution.txt
  root/static/images/icons/edit.png
  root/static/images/src/icons/edit.svg
Labels: Frontend-only

#2683 MBS-12660: Convert user contact form to React
  lib/MusicBrainz/Server/Controller/User.pm
  lib/MusicBrainz/Server/Form/User/Contact.pm
  root/server/components.mjs
  root/user/ContactUser.js
  root/user/contact.tt
Labels: React

#2974 MBS-13149 / MBS-13153 / MBS-13156 / MBS-13157: More guess case changes
  root/static/scripts/guess-case/modes.js
  root/static/scripts/guess-case/utils.js
  root/static/scripts/tests/GuessCase.js
Labels: QoL, Bug

#2976 MBS-13115: Move annotation preview button to the left of Enter
  root/annotation/EditAnnotation.js
  root/static/scripts/edit/components/EnterEdit.js
Labels: QoL, Frontend-only

#2979 MBS-13160: Rename "legal name" on artist page to "performance name of"
  lib/MusicBrainz/Server/Controller/Artist.pm
  root/artist/ArtistIndex.js
Labels: QoL

#2980 MBS-13168: Add autoselect for BookBrainz series
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL, URL handling

#2981 MBS-13162: Handle Threads links
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/Threads.pm
  root/static/images/external-favicons/threads-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: QoL, URL handling

#2959 MBS-13111 / MBS-13116: Hide list of autoeditor election voters during vote
  root/elections/ElectionDetails.js
  root/elections/ElectionVoting.js
  root/elections/Show.js
Labels: QoL, Bug, Frontend-only

#2986 MBS-13173: Also allow daily.bandcamp.com interviews
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug, URL handling

#2983 MBS-13167: Show last granted token date for auth applications
  lib/MusicBrainz/Server/Data/EditorOAuthToken.pm
  root/account/applications/Index.js
Labels: QoL

#2975 MBS-13092: Support Apple Music song links
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature, URL handling

#2958 MBS-13105 / MBS-13106: Fix ISEs on attribute deletion pages
  lib/MusicBrainz/Server/Controller/Admin/Attributes.pm
  lib/MusicBrainz/Server/Data/Language.pm
  lib/MusicBrainz/Server/Data/Script.pm
  t/lib/t/MusicBrainz/Server/Controller/Admin/Attributes/Delete.pm
  t/sql/attributes.sql
Labels: Bug, Tests

#2957 MBS-13113: Show in attribute page if it supports free text
  root/relationship/linkattributetype/RelationshipAttributeTypeIndex.js
Labels: QoL, Frontend-only

#2685 MBS-12663: Convert Reset password page to React
  lib/MusicBrainz/Server/Controller/Account.pm
  lib/MusicBrainz/Server/Form/User/ResetPassword.pm
  root/account/ResetPassword.js
  root/account/reset_password.tt
  root/server/components.mjs
  root/static/scripts/edit/components/FormRowText.js
Labels: React

#2695 MBS-12670: Convert the Delete user page to React
  lib/MusicBrainz/Server/Controller/Admin.pm
  root/admin/DeleteUser.js
  root/admin/delete_user.tt
  root/server/components.mjs
  root/static/scripts/edit/components/FormRow.js
  root/static/scripts/edit/components/FormRowCheckbox.js
  root/static/scripts/edit/components/FormSubmit.js
Labels: React

#2989 MBS-13177: Show label events on label rels page
  lib/MusicBrainz/Server/Controller/Label.pm
  root/components/RelationshipsTable.js
Labels: Bug

#2934 MBS-13057 / MBS-13058: Improve the application/revoke-access page
  lib/MusicBrainz/Server/Controller/Account.pm
  root/account/applications/ApplicationList.js
  root/account/applications/EditApplication.js
  root/account/applications/RegisterApplication.js
  root/account/applications/RemoveApplication.js
  root/account/applications/RevokeAccess.js
  root/account/applications/RevokeApplicationAccess.js
  root/server/components.mjs
Labels: QoL

#2971 MBS-13094: Allow admins to browse edit note changes
  lib/MusicBrainz/Server/Controller/EditNote.pm
  lib/MusicBrainz/Server/Data/EditNoteChange.pm
  lib/MusicBrainz/Server/Entity/EditNoteChange.pm
  root/edit/components/EditNote.js
  root/edit_note/EditNoteChange.js
  root/edit_note/EditNoteHistory.js
  root/server/components.mjs
  root/static/styles/entity.less
  root/types/edit.js
  t/lib/t/MusicBrainz/Server/Controller/EditNote/ChangeNote.pm
  t/lib/t/MusicBrainz/Server/Controller/EditNote/NoteHistory.pm
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
  t/sql/edit_note_history.sql
Labels: New feature

#2707 MBS-12671: Convert Edit user page to React
  lib/MusicBrainz/Server/Controller/Admin.pm
  root/admin/EditUser.js
  root/admin/edit_user.tt
  root/server/components.mjs
  root/static/scripts/edit/components/FormLabel.js
  root/static/scripts/edit/components/FormRowCheckbox.js
  root/static/scripts/edit/components/FormRowNameWithGuessCase.js
  root/static/scripts/edit/components/FormRowPartialDate.js
  root/static/scripts/edit/components/FormRowRadio.js
  root/static/scripts/edit/components/FormRowSelect.js
  root/static/scripts/edit/components/FormRowSelectList.js
  root/static/scripts/edit/components/FormRowSortNameWithGuessCase.js
  root/static/scripts/edit/components/FormRowText.js
  root/static/scripts/edit/components/FormRowTextArea.js
  root/static/scripts/edit/components/FormSubmit.js
  root/static/scripts/work/edit.js
  root/user/profile/layout.tt
Labels: React

#2936 MBS-13079: Add statistics for release groups with no type set
  lib/MusicBrainz/Server/Data/Statistics.pm
  root/statistics/Index.js
  root/statistics/stats.js
Labels: QoL

#2984 MBS-13169: Use SVG over PNG for new icons
  root/static/images/attribution.txt
  root/static/images/icons/add_row.png
  root/static/images/icons/add_row.svg
  root/static/images/icons/delete_row.png
  root/static/images/icons/delete_row.svg
  root/static/images/icons/edit.png
  root/static/images/icons/edit.svg
  root/static/images/icons/open_edits_for_entity.png
  root/static/images/icons/open_edits_for_entity.svg
  root/static/images/icons/open_edits_for_rel.png
  root/static/images/icons/open_edits_for_rel.svg
  root/static/scripts/relationship-editor/components/RelationshipItem.js
  root/static/styles/forms.less
Labels: QoL, Frontend-only

#2890 MBS-12964: Allow specifying dates when batch-creating works
  root/static/scripts/relationship-editor/components/DialogDatePeriod.js
  root/static/scripts/relationship-editor/components/RelationshipDialogContent.js
  root/static/scripts/relationship-editor/types.js
  root/static/scripts/relationship-editor/types/actions.js
  root/static/scripts/release/components/BatchCreateWorksDialog.js
  root/static/scripts/release/components/ReleaseRelationshipEditor.js
Labels: Regression/Beta

#2825 MBS-12886: Restrict Bandcamp /(album|track) to "get the music" rels
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL, URL handling

#2977 MBS-13098: Process cover art params for seeding
  lib/MusicBrainz/Server/Controller/Release.pm
  root/release/add_cover_art.tt
  t/selenium/CAA.json5
Labels: New feature
