Repository metabrainz/musicbrainz-server, pull requests merged in 2023-02, with the labels that each got.

#2823 MBS-12880: Support fieldset.row legend styling again
  root/static/styles/forms.less
Labels: Regression/Beta

#2818 MBS-12859: Allow relationship credit to be the same as name
  root/static/scripts/relationship-editor/components/DialogEntityCredit.js
  root/static/scripts/relationship-editor/components/DialogPreview.js
  root/static/scripts/relationship-editor/components/RelationshipDialogContent.js
  t/selenium.mjs
  t/selenium/MBS-12859.json5
Labels: Regression/Beta

#2819 MBS-12863: Tooltips too far to the left
  root/static/styles/relationship-editor.less
  root/static/styles/tooltip.less
Labels: Regression/Beta

#2828 MBS-12888: Check ended when copying end date
  root/static/scripts/common/utility/isDateEmpty.js
  root/static/scripts/edit/components/DateRangeFieldset.js
  root/types/entity.js
Labels: QoL, Bug

#2841 MBS-12901: Show user website and bio on the admin user views
  root/admin/components/UserList.js
Labels: QoL

#2834 MBS-12890: Show disambiguation in label/genre autocompletes
  root/static/scripts/common/components/Autocomplete2/formatters.js
Labels: Regression/Beta

#2839 MBS-12891 / MBS-7971: Show more info for inline artist/label search
  lib/MusicBrainz/Server/Controller/WS/js/Artist.pm
  lib/MusicBrainz/Server/Controller/WS/js/Label.pm
  root/static/scripts/common/components/Autocomplete2/formatters.js
  t/lib/t/MusicBrainz/Server/Controller/WS/js/Autocomplete.pm
Labels: QoL

#2843 MBS-11770: Always list autocomplete additional data for all entities
  lib/MusicBrainz/Server/Controller/WS/js.pm
Labels: Bug

#2838 MBS-12899: Add TMDB to the otherdbs whitelist for artists
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/TMDB.pm
  root/static/images/external-favicons/tmdb-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature, URL handling

#2791 MBS-12814: Remove animationsong.com from the lyrics whitelist
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/Animationsong.pm
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL, URL handling

#2833 MBS-12853: Disallow IPI that is all zeros
  lib/MusicBrainz/Server/Validation.pm
  t/lib/t/MusicBrainz/Server/Validation.pm
Labels: QoL

#2686 MBS-12665: Widen DNB regex
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug, URL handling

#2845 MBS-12896: Show admins whether user is banned from profile
  root/user/UserProfile.js
Labels: QoL, Frontend-only

#2846 MBS-12908: Do not reuse "cancelled"/"time" for artist-event rels
  root/static/scripts/relationship-editor/components/RelationshipPhraseGroup.js
  t/sql/initial.sql
Labels: QoL

#2848 MBS-11770 (erratum): Load work languages for recently used works
  lib/MusicBrainz/Server/Controller/WS/js.pm
Labels: QoL

#2794 MBS-12816: Highlight doc header when linking to fragment
  root/static/styles/extra/wikidocs.less
Labels: QoL, Frontend-only

#2801 MBS-12806: Do not show "Play on LB" button for empty releases
  lib/MusicBrainz/Server/Entity/Release.pm
  root/layout/components/sidebar/ReleaseSidebar.js
  root/static/scripts/common/entity2.js
  root/types/release.js
  t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
Labels: QoL

#2852 MBS-12926: Remove indents from Autocomplete search results
  lib/MusicBrainz/Server/Data/Artist.pm
  root/static/scripts/common/components/Autocomplete2/searchItems.js
  t/lib/t/MusicBrainz/Server/Controller/Instrument/Artists.pm
Labels: Bug

#2857 MBS-12932: Always show [No lyrics] in work languages
  root/static/scripts/common/components/Autocomplete2/recentItems.js
Labels: Bug

#2856 MBS-12925: Allow submitting work dialogs with Enter
  root/static/scripts/relationship-editor/components/RelationshipDialogContent.js
  root/static/scripts/relationship-editor/hooks/useDialogEnterKeyHandler.js
  root/static/scripts/release/components/BatchCreateWorksDialog.js
  root/static/scripts/release/components/EditWorkDialog.js
Labels: QoL, Bug

#2855 MBS-12923: Stop submission when no changes made
  root/static/scripts/release/components/ReleaseRelationshipEditor.js
Labels: Bug

#2854 MBS-12930: Validate relationship fields on Perl level
  lib/MusicBrainz/Server/Form/Field/Relationship.pm
Labels: Bug

#2858 MBS-12919: Show warning icon when rel has pending edits
  root/static/scripts/relationship-editor/components/RelationshipDialogContent.js
  root/static/scripts/relationship-editor/components/RelationshipItem.js
  root/static/scripts/relationship-editor/utility/getOpenEditsLink.js
Labels: Bug

#2875 MBS-12946: Don't put Tooltip div inside span
  root/static/scripts/edit/components/HelpIcon.js
  root/static/scripts/edit/components/Tooltip.js
  root/static/styles/forms.less
  root/static/styles/tooltip.less
Labels: Regression/Beta
