Repository metabrainz/musicbrainz-server, pull requests merged in 2023-05, with the labels that each got.

#2727 MBS-12704: Remove historical "Watch artist" code
  admin/SendReleaseNotifications
  admin/sql/CreateFKConstraints.sql
  admin/sql/CreateFunctions.sql
  admin/sql/CreatePrimaryKeys.sql
  admin/sql/CreateTables.sql
  admin/sql/CreateTriggers.sql
  admin/sql/DropFKConstraints.sql
  admin/sql/DropFunctions.sql
  admin/sql/DropPrimaryKeys.sql
  admin/sql/DropTables.sql
  admin/sql/DropTriggers.sql
  admin/sql/TruncateTables.sql
  admin/sql/updates/20221114-mbs-12704.sql
  admin/sql/updates/schema-change/28.all.sql
  lib/MusicBrainz/Script/NotifyOfNewReleases.pm
  lib/MusicBrainz/Server/Constants.pm
  lib/MusicBrainz/Server/Controller/Artist.pm
  lib/MusicBrainz/Server/Controller/Watch.pm
  lib/MusicBrainz/Server/Data/Editor.pm
  lib/MusicBrainz/Server/Data/WatchArtist.pm
  lib/MusicBrainz/Server/Email/NewReleases.pm
  lib/MusicBrainz/Server/Entity/EditorWatchPreferences.pm
  lib/MusicBrainz/Server/Form/User/WatchPreferences.pm
  root/watch/list.tt
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
  t/lib/t/MusicBrainz/Server/Data/WatchArtist.pm
  t/lib/t/MusicBrainz/Server/Email/NewReleases.pm
  t/lib/t/MusicBrainz/Server/Entity/EditorWatchPreferences.pm
  t/script/NotifyOfNewReleases.t
  t/sql/watch.sql
  t/tests.t
  upgrade.json
Labels: Refactoring

#2667 MBS-12573: Drop unused degraded column from cdtoc
  admin/sql/CreateTables.sql
  admin/sql/updates/20220927-mbs-12573.sql
  admin/sql/updates/schema-change/28.all.sql
  lib/MusicBrainz/Server/Entity/CDTOC.pm
  t/sql/tracklist.sql
  t/sql/webservice.sql
  upgrade.json
Labels: Refactoring

#2923 MBS-13047: Do not assume every wiki image has /thumb
  lib/MusicBrainz/Server/Data/WikiDoc.pm
Labels: Bug

#2928 MBS-13052: Support intl-XX/ path segment in Spotify URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: URL handling

#2931 MBS-7385: Use EntityLink over release name in medium append UI
  root/static/scripts/edit/components/ReleaseMergeStrategy.js
Labels: QoL, Frontend-only

#2943 MBS-13085: Clarify "share email" report checkbox
  root/user/ReportUser.js
Labels: QoL, Frontend-only

#2932 MBS-8774: Show containment for selected area in area bubble
  root/static/scripts/common/entity.js
Labels: QoL, Frontend-only

#2922 MBS-13045: Display artist rename relationship on overview
  lib/MusicBrainz/Server/Constants.pm
  lib/MusicBrainz/Server/Controller/Artist.pm
  root/artist/ArtistIndex.js
Labels: QoL

#2764 MBS-12756: Convert Delete instrument page to React
  lib/MusicBrainz/Server/Controller/Role/Delete.pm
  root/instrument/DeleteInstrument.js
  root/instrument/delete.tt
  root/instrument/types.js
  root/server/components.mjs
Labels: React

#2357 MBS-4685 / MBS-13084: Allow modifying and removing edit notes
  lib/MusicBrainz/Server/Controller/Edit.pm
  lib/MusicBrainz/Server/Controller/EditNote.pm
  lib/MusicBrainz/Server/Data/EditNote.pm
  lib/MusicBrainz/Server/Data/EditNoteChange.pm
  lib/MusicBrainz/Server/Data/Utils.pm
  lib/MusicBrainz/Server/Entity/EditNote.pm
  lib/MusicBrainz/Server/Entity/EditNoteChange.pm
  lib/MusicBrainz/Server/Entity/Types.pm
  lib/MusicBrainz/Server/Form/EditNoteDelete.pm
  lib/MusicBrainz/Server/Form/EditNoteModify.pm
  root/constants.js
  root/edit/DeleteNote.js
  root/edit/ModifyNote.js
  root/edit/NotesReceived.js
  root/edit/components/EditNote.js
  root/edit/components/EditNoteHelp.js
  root/edit/components/EditNoteListEntry.js
  root/edit/components/EditNotes.js
  root/layout.tt
  root/layout/index.js
  root/server/components.mjs
  root/static/styles/edit.less
  root/static/styles/forms.less
  root/types/edit.js
  t/lib/t/MusicBrainz/Server/Controller/Edit/ChangeNote.pm
  t/lib/t/MusicBrainz/Server/Controller/UnconfirmedEmailAddresses.pm
  t/lib/t/MusicBrainz/Server/Data/EditNote.pm
  t/sql/change_edit_note.sql
  t/sql/edit_note.sql
Labels: New feature

#2750 MBS-12692: Also consider artist empty if used in unused AC
  lib/MusicBrainz/Server/Data/Artist.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/EligibleForCleanup.pm
  t/sql/artist_cleanup.sql
Labels: QoL

#2938 MBS-13087: Change bitwise AND to OR for combining privileges
  lib/MusicBrainz/Server/Constants.pm
  root/static/scripts/tests/index-web.js
  root/static/scripts/tests/utility/sanitizedEditor.js
  root/utility/sanitizedEditor.mjs
Labels: Bug

#2930 MBS-13060: Display attribute MBIDs on attribute tables
  root/admin/attributes/Attribute.js
Labels: QoL, Frontend-only

#2933 MBS-10759: Explain release data quality in editor
  root/release/ChangeQuality.js
Labels: QoL, Frontend-only

#2947 MBS-13089: Properly enclose $used_in_relationship in parens
  lib/MusicBrainz/Server/Data/Event.pm
  lib/MusicBrainz/Server/Data/Place.pm
  lib/MusicBrainz/Server/Data/Work.pm
Labels: Regression/Beta

#2948 Avoid area bubble crashing on missing iso_3166_1_codes
  root/static/scripts/common/entity.js
Labels: Regression/Beta

#2946 MBS-13088: Standardize series type bubble
  lib/MusicBrainz/Server/Controller/Series.pm
  root/series/edit_form.tt
  root/static/scripts/series/edit.js
Labels: Bug

#2949 MBS-12211: Avoid crash when URL has been removed
  root/report/components/ArtistUrlList.js
  root/report/components/LabelUrlList.js
  root/report/components/ReleaseGroupUrlList.js
  root/report/components/ReleaseUrlList.js
  root/report/components/RemovedUrlRow.js
Labels: Bug

#2954 MBS-12552 (pre): Nail last "core" Flow.js types
  entities.json
  entities.mjs
  root/components/EntityDeletionHelp.js
  root/static/scripts/common/entity.js
  root/types/area.js
  root/types/artist.js
  root/types/entity.js
  root/types/event.js
  root/types/genre.js
  root/types/instrument.js
  root/types/label.js
  root/types/place.js
  root/types/recording.js
  root/types/release.js
  root/types/releasegroup.js
  root/types/series.js
  root/types/url.js
  root/types/work.js
Labels: Refactoring

#2779 MBS-12746: Convert cdstub/browse to React
  lib/MusicBrainz/Server/Controller/CDStub.pm
  root/cdstub/BrowseCDStubs.js
  root/cdstub/browse.tt
  root/components/common-macros.tt
  root/layout/components/sidebar/CDStubSidebar.js
  root/server/components.mjs
  root/utility/getCDStubAge.js
  t/lib/t/MusicBrainz/Server/Controller/CDStub/Browse.pm
Labels: React

#2956 MBS-13104: Unblock and handle RYM interview links
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/RateYourMusic.pm
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: URL handling
