Repository metabrainz/musicbrainz-server, pull requests merged in 2023-11, with the labels that each got.

#3056 Normalize "pending edits" to "open edits" in UI
  root/static/scripts/common/components/ArtistCreditLink.js
  root/static/scripts/edit/components/EntityPendingEditsWarning.js
  root/static/scripts/edit/components/RelationshipPendingEditsWarning.js
  root/static/scripts/relationship-editor/components/RelationshipDialogContent.js
Labels: QoL, Frontend-only

#3057 Normalize "track duration" to "track length" in UI
  admin/cleanup/FixTrackLength.pl
  root/cdtoc/AttachCDTocConfirmation.js
  root/cdtoc/list.tt
  root/release/discids.tt
  root/release/edit/tracklist.tt
  root/report/CDTocNotApplied.js
  root/static/scripts/tests/release-editor/trackParser.js
  t/lib/t/MusicBrainz/Server/Edit/Medium/Delete.pm
Labels: QoL, Frontend-only

#3058 Capitalize URL in user-facing string
  lib/MusicBrainz/Server/Form/Field/URL.pm
Labels: QoL

#3060 Remove unneeded abbreviations
  CONTRIBUTING.md
  HACKING-PROD.md
  HACKING.md
  INSTALL.md
  admin/InitDb.pl
  lib/MusicBrainz/Server/Form/Field/URL.pm
  po/README
  root/artist/ArtistMerge.js
  root/report/DuplicateReleaseGroups.js
  root/report/InstrumentsWithoutAnImage.js
  root/report/MediumsWithSequenceIssues.js
  root/report/RecordingsWithFutureDates.js
  root/report/TracksNamedWithSequence.js
  root/report/TracksWithSequenceIssues.js
  root/static/scripts/artist/components/ArtistCreditRenamer.js
  root/user/PrivilegedUsers.js
Labels: QoL

#3066 Use "remove" consistently for non-editor cases
  lib/MusicBrainz/Server/Controller/Collection.pm
  root/edit/search_macros.tt
  root/mbid/NotFound.js
  root/relationship/linkattributetype/RelationshipAttributeTypeInUse.js
  root/relationship/linktype/RelationshipTypeInUse.js
  root/release/edit/tracklist.tt
  root/static/scripts/common/MB/Control/EditSummary.js
  root/user/UserProfile.js
Labels: QoL, Frontend-only

#2835 MBS-12852 / MBS-12893: Add events and places to country stats page
  lib/MusicBrainz/Server/Controller/Statistics.pm
  lib/MusicBrainz/Server/Data/Statistics.pm
  root/static/scripts/statistics.js
  root/statistics/Countries.js
  root/statistics/stats.js
Labels: Bug, New feature

#2757 MBS-12727: Show genre alias connections for tags
  lib/MusicBrainz/Server/Data/Search.pm
  lib/MusicBrainz/Server/Data/Tag.pm
Labels: QoL

#3071 Use exactCount for newline-after-import eslint rule
  .eslintrc.yaml
  package.json
  root/report/CatNoLooksLikeLabelCode.js
  root/report/RecordingsWithFutureDates.js
  root/static/scripts/edit/components/ArtistCreditBubble.js
  root/static/scripts/guess-case/utils.js
  root/static/scripts/release-editor/duplicates.js
  root/static/scripts/release/components/ReleaseRelationshipEditor.js
  root/static/scripts/work/edit.js
  root/user/ContactUser.js
  root/utility/hydrate.js
  yarn.lock
Labels: Refactoring

#2952 Add new tests for JS utilities in /common
  root/static/scripts/common/components/ArtistListEntry.js
  root/static/scripts/common/components/MergeCheckboxElement.js
  root/static/scripts/common/utility/areDatesEqual.js
  root/static/scripts/common/utility/calculateFullToc.js
  root/static/scripts/common/utility/formatBarcode.js
  root/static/scripts/common/utility/formatEndDate.js
  root/static/scripts/common/utility/renderMergeCheckboxElement.js
  root/static/scripts/tests/index-web.js
  root/static/scripts/tests/renderToStaticMarkup.js
  root/static/scripts/tests/utility/areDatePeriodsEqual.js
  root/static/scripts/tests/utility/arrays.js
  root/static/scripts/tests/utility/bracketed.js
  root/static/scripts/tests/utility/calculateFullToc.js
  root/static/scripts/tests/utility/clean.js
  root/static/scripts/tests/utility/constants.js
  root/static/scripts/tests/utility/entityHref.js
  root/static/scripts/tests/utility/escapeLuceneValue.js
  root/static/scripts/tests/utility/escapeRegExp.js
  root/static/scripts/tests/utility/formatBarcode.js
  root/static/scripts/tests/utility/formatEndDate.js
  root/static/scripts/tests/utility/formatSetlist.js
  root/static/scripts/tests/utility/getSortName.js
  root/static/scripts/tests/utility/isBlank.js
  root/static/scripts/tests/utility/isDatabaseRowId.js
  root/static/scripts/tests/utility/isDateEmpty.js
  root/static/scripts/tests/utility/isDisabledLink.js
  root/static/scripts/tests/utility/isFutureDate.js
  root/static/scripts/tests/utility/isGuid.js
  root/static/scripts/tests/utility/isObjectEmpty.js
  root/static/scripts/tests/utility/isolateText.js
  root/static/scripts/tests/utility/natatime.js
  root/static/scripts/tests/utility/primaryAreaCode.js
  root/static/scripts/tests/utility/relationshipDateText.js
  root/static/scripts/tests/utility/sanitizedEditor.js
  root/static/scripts/tests/utility/sortByEntityName.js
  root/static/scripts/tests/utility/strings.js
  root/utility/tableColumns.js
Labels: Tests

#3076 MBS-13350: Return all barcode matches in release editor
  root/static/scripts/release-editor/validation.js
Labels: Bug

#3077 MBS-13349: Support LibraryThing disambiguation URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: Bug, URL handling

#3085 MBS-13357: Clarify the report for low data quality
  lib/MusicBrainz/Server/Report/LowDataQualityReleases.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/LowDataQualityReleases.js
  root/report/ReportsIndex.js
  root/server/components.mjs
Labels: Bug, Reports

#3088 MBS-13362: Handle Spotify prerelease URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: URL handling

#3081 MBS-13326: Add documentation bubble for the artist sort name field
  root/artist/edit_form.tt
  root/components/forms.tt
Labels: QoL

#2929 MBS-9396: Properly parse seeded release group URLs
  root/static/scripts/edit/externalLinks.js
  t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Create.pm
  t/selenium.mjs
  t/selenium/MBS-9396.json5
Labels: Bug

#2969 Block notes on add note
  lib/MusicBrainz/Server/Data/Edit.pm
  lib/MusicBrainz/Server/Data/EditNote.pm
  t/lib/t/MusicBrainz/Server/Data/EditNote.pm
  t/sql/edit_note.sql
Labels: Refactoring

#3095 MBS-13366: Also show medium data on Edit medium preview
  root/edit/details/EditMedium.js
Labels: QoL, Frontend-only

#3047 MBS-13284: Don't require edit note for alias removals
  lib/MusicBrainz/Server/Controller/Role/Alias.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/DeleteAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/DeleteAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/DeleteAlias.pm
  t/lib/t/MusicBrainz/Server/Controller/Series/DeleteAlias.pm
Labels: QoL

#3084 MBS-11934: Add report for releases without CAA
  lib/MusicBrainz/Server/Report/ReleasesWithoutCAA.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/ReleasesWithoutCaa.js
  root/report/ReportsIndex.js
  root/server/components.mjs
Labels: New feature, Reports

#2723 Follow Perl::Critic::Policy::ClassHierarchies rules
  .perlcriticrc
  lib/MusicBrainz/Server/Replication.pm
  lib/MusicBrainz/Server/Validation.pm
  t/lib/t/MusicBrainz/Server/Controller/RelationshipEditor.pm
Labels: Refactoring

#2729 Make _hash_to_row methods more consistent
  lib/MusicBrainz/Server/Data/Area.pm
  lib/MusicBrainz/Server/Data/Artist.pm
  lib/MusicBrainz/Server/Data/Collection.pm
  lib/MusicBrainz/Server/Data/Editor.pm
  lib/MusicBrainz/Server/Data/Event.pm
  lib/MusicBrainz/Server/Data/Genre.pm
  lib/MusicBrainz/Server/Data/Instrument.pm
  lib/MusicBrainz/Server/Data/Label.pm
  lib/MusicBrainz/Server/Data/LinkAttributeType.pm
  lib/MusicBrainz/Server/Data/LinkType.pm
  lib/MusicBrainz/Server/Data/Place.pm
  lib/MusicBrainz/Server/Data/Recording.pm
  lib/MusicBrainz/Server/Data/Release.pm
  lib/MusicBrainz/Server/Data/ReleaseGroup.pm
  lib/MusicBrainz/Server/Data/Series.pm
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Data/Work.pm
Labels: Refactoring
