Repository metabrainz/musicbrainz-server, pull requests merged in 2023-12, with the labels that each got.

#2704 Avoid using multiple with in Entity:: files
  lib/MusicBrainz/Server/Entity/Alias.pm
  lib/MusicBrainz/Server/Entity/Area.pm
  lib/MusicBrainz/Server/Entity/Artist.pm
  lib/MusicBrainz/Server/Entity/ArtistCredit.pm
  lib/MusicBrainz/Server/Entity/Collection.pm
  lib/MusicBrainz/Server/Entity/Event.pm
  lib/MusicBrainz/Server/Entity/Genre.pm
  lib/MusicBrainz/Server/Entity/Instrument.pm
  lib/MusicBrainz/Server/Entity/Label.pm
  lib/MusicBrainz/Server/Entity/Link.pm
  lib/MusicBrainz/Server/Entity/LinkAttribute.pm
  lib/MusicBrainz/Server/Entity/LinkTypeAttribute.pm
  lib/MusicBrainz/Server/Entity/Medium.pm
  lib/MusicBrainz/Server/Entity/Place.pm
  lib/MusicBrainz/Server/Entity/Recording.pm
  lib/MusicBrainz/Server/Entity/Relationship.pm
  lib/MusicBrainz/Server/Entity/Release.pm
  lib/MusicBrainz/Server/Entity/ReleaseGroup.pm
  lib/MusicBrainz/Server/Entity/Series.pm
  lib/MusicBrainz/Server/Entity/Track.pm
  lib/MusicBrainz/Server/Entity/URL/IMSLP.pm
  lib/MusicBrainz/Server/Entity/URL/Wikidata.pm
  lib/MusicBrainz/Server/Entity/URL/Wikipedia.pm
  lib/MusicBrainz/Server/Entity/Work.pm
  lib/MusicBrainz/Server/Entity/WorkAttribute.pm
  lib/MusicBrainz/Server/Entity/WorkAttributeType.pm
Labels: Refactoring

#3094 MBS-13368: Properly compare series relationships if series is target
  root/static/scripts/relationship-editor/utility/compareRelationships.js
  root/static/scripts/tests/index-web.js
  root/static/scripts/tests/relationship-editor/utility/compareRelationships.js
Labels: Bug

#3112 MBS-13388: Handle vk.gy links
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/Vkgy.pm
  root/static/images/external-favicons/vkgy-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature, URL handling

#2494 MBS-11556: Standardise / clean up YouTube Music URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: New feature, URL handling

#2788 MBS-12801: Warn users about "Disc n" titles on release merge
  root/static/scripts/edit/components/ReleaseMergeStrategy.js
  root/static/scripts/edit/utility/isUselessMediumTitle.js
  root/static/scripts/release-editor/fields.js
  root/static/scripts/tests/edit/utility/isUselessMediumTitle.js
  root/static/scripts/tests/index-web.js
Labels: QoL

#2756 MBS-12725: Add "Refine this search" link on Votes by [user] page
  lib/MusicBrainz/Server/Controller/User/Edits.pm
Labels: QoL

#3117 Use React$FragmentType rather than typeof React.Fragment
  root/account/ChangePassword.js
  root/artist/ArtistIndex.js
  root/cdtoc/CDTocInfo.js
  root/collection/CollectionHeader.js
  root/components/Aliases/ArtistCreditList.js
  root/components/Artwork.js
  root/components/EntityHeader.js
  root/components/PaginatedResults.js
  root/components/ReleaseLanguageScript.js
  root/components/TagEntitiesList.js
  root/components/list/EventList.js
  root/components/list/ReleaseGroupList.js
  root/components/list/WorkList.js
  root/edit/components/EditList.js
  root/edit/components/EditSummary.js
  root/edit/components/EditorTypeInfo.js
  root/edit/components/TrackDurationChanges.js
  root/edit/details/AddRelationshipType.js
  root/edit/details/EditRelationshipType.js
  root/edit/details/EditUrl.js
  root/edit/details/MergeReleases.js
  root/edit/details/RemoveMedium.js
  root/edit/details/historic/EditRelationship.js
  root/layout/components/FaviconLinks.js
  root/layout/components/sidebar/AnnotationLinks.js
  root/layout/components/sidebar/EditLinks.js
  root/layout/components/sidebar/SidebarProperties.js
  root/layout/components/sidebar/SidebarRating.js
  root/layout/components/sidebar/SidebarTags.js
  root/layout/components/sidebar/SubscriptionLinks.js
  root/main/error/components/ErrorEnvironment.js
  root/release/CoverArt.js
  root/release/CoverArtFields.js
  root/search/components/SearchForm.js
  root/static/scripts/alias/AliasEditForm.js
  root/static/scripts/common/components/AcoustIdCell.js
  root/static/scripts/common/components/Relationships.js
  root/static/scripts/common/components/ReleaseEvent.js
  root/static/scripts/common/components/WorkListEntry.js
  root/static/scripts/edit/components/EntityPendingEditsWarning.js
  root/static/scripts/edit/components/InlineSubmitButton.js
  root/static/scripts/edit/components/RelationshipPendingEditsWarning.js
  root/static/scripts/edit/components/edit/RelationshipDiff.js
  root/static/scripts/edit/externalLinks.js
  root/tag/EntityList.js
Labels: Refactoring

#2495 MBS-12318 / MBS-12323 / MBS-12324: Improvements to ArtistsThatMayBe reports
  lib/MusicBrainz/Server/Report/ArtistsThatMayBeGroups.pm
  lib/MusicBrainz/Server/Report/ArtistsThatMayBePersons.pm
  root/report/ArtistsThatMayBePersons.js
Labels: QoL, Reports

#3118 MBS-13397: Support video pages for jazzmusic/metalmusic/progarchives
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL, URL handling

#2815 Document React state management
  HACKING.md
  root/static/scripts/tests/examples/todo-list/README
  root/static/scripts/tests/examples/todo-list/Todo.js
  root/static/scripts/tests/examples/todo-list/TodoList.js
  root/static/scripts/tests/examples/todo-list/index.html
  root/static/scripts/tests/examples/todo-list/index.js
  webpack/tests.config.mjs
Labels: Documentation

#3109 MBS-13364 / MBS-13377 / MBS-13378: Fixes / improvements for editor mailing preferences
  lib/MusicBrainz/Server/Data/EditNote.pm
  lib/MusicBrainz/Server/Data/Editor.pm
  lib/MusicBrainz/Server/Entity/Preferences.pm
  lib/MusicBrainz/Server/Form/User/Preferences.pm
  root/static/scripts/account/components/PreferencesForm.js
  root/static/scripts/tests/utility/constants.js
  root/types/editor.js
  t/lib/t/MusicBrainz/Server/Data/EditNote.pm
Labels: Bug, New feature

#3114 MBS-13392 / MBS-13393: Restore the external links editor submission upon form reload, and reduce the relationship data stored in sessionStorage
  root/static/scripts/edit/externalLinks.js
  root/static/scripts/relationship-editor/components/RelationshipEditor.js
  root/static/scripts/relationship-editor/utility/prepareHtmlFormSubmission.js
  t/selenium.mjs
  t/selenium/MBS-13392.json5
Labels: Bug

#3121 Lowercase some more forgotten strings
  root/artist_credit/ArtistCreditLayout.js
  root/entity/NotFound.js
  root/static/scripts/account/components/ApplicationForm.js
  root/tag/TagLayout.js
  root/utility/tableColumns.js
Labels: Refactoring

#3120 MBS-13117 (II): Make more admin strings untranslatable
  root/area/edit_form.tt
  root/components/common-macros.tt
  root/edit/search_macros.tt
  root/genre/CreateGenre.js
  root/genre/DeleteGenre.js
  root/genre/EditGenre.js
  root/instrument/edit_form.tt
  root/relationship/linkattributetype/create.tt
  root/relationship/linkattributetype/edit.tt
  root/relationship/linkattributetype/form.tt
  root/relationship/linktype/create.tt
  root/relationship/linktype/edit.tt
  root/relationship/linktype/form.tt
  root/static/scripts/genre/components/GenreEditForm.js
Labels: Refactoring

#2789 MBS-12802: Use localize_error for artist credit errors
  lib/MusicBrainz/Server/Form/Field/ArtistCredit.pm
  lib/MusicBrainz/Server/Form/Merge.pm
  lib/MusicBrainz/Server/Form/Role/CSRFToken.pm
  lib/MusicBrainz/Server/Form/User/Login.pm
  lib/MusicBrainz/Server/Form/User/Register.pm
  lib/MusicBrainz/Server/Form/Utils.pm
  lib/MusicBrainz/Server/Form/Work.pm
Labels: Bug

#3124 MBS-13401: Also load data quality for track releases
  lib/MusicBrainz/Server/Data/Track.pm
Labels: QoL

#2772 MBS-12775: Convert the release Disc Ids page to React
  lib/MusicBrainz/Server/Controller/Release.pm
  lib/MusicBrainz/Server/Entity/Medium.pm
  lib/MusicBrainz/Server/Entity/MediumCDTOC.pm
  root/cdtoc/AttachCDTocConfirmation.js
  root/cdtoc/SetTracklistDurations.js
  root/cdtoc/utils.js
  root/components/common-macros.tt
  root/release/DiscIds.js
  root/release/discids.tt
  root/server/components.mjs
  root/types/medium.js
Labels: React

#2753 Avoid using multiple with in misc files
  lib/MusicBrainz/Script/FixLinkDuplicates.pm
  lib/MusicBrainz/Script/JSONDump.pm
  lib/MusicBrainz/Script/JSONDump/Incremental.pm
  lib/MusicBrainz/Script/PruneCache.pm
  lib/MusicBrainz/Script/RemoveEmpty.pm
  lib/MusicBrainz/Script/RemoveExpiredSessions.pm
  lib/MusicBrainz/Script/RemoveUnreferencedRows.pm
  lib/MusicBrainz/Script/SampleDataDump.pm
  lib/MusicBrainz/Script/SubscriptionEmails.pm
  lib/MusicBrainz/Server/ControllerBase/WS/2.pm
  lib/MusicBrainz/Server/EditSearch/Predicate/EditNoteAuthor.pm
  lib/MusicBrainz/Server/EditSearch/Predicate/Editor.pm
  lib/MusicBrainz/Server/EditSearch/Predicate/Role/User.pm
  lib/MusicBrainz/Server/Form/User/Login.pm
  lib/MusicBrainz/Server/Report.pm
  lib/MusicBrainz/Server/Report/ReleasesWithEmptyMediums.pm
  lib/MusicBrainz/Server/Report/ReleasesWithNoMediums.pm
  lib/MusicBrainz/Server/Sitemap/Incremental.pm
  lib/MusicBrainz/Server/Sitemap/Overall.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Area.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Artist.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Label.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Place.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Recording.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Release.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/ReleaseGroup.pm
  lib/MusicBrainz/Server/WebService/Serializer/JSON/LD/Work.pm
Labels: Refactoring

#2790 MBS-12799 / MBS-7028: Extra options for filters
  lib/MusicBrainz/Server/Data/Event.pm
  lib/MusicBrainz/Server/Data/Recording.pm
  lib/MusicBrainz/Server/Data/Release.pm
  lib/MusicBrainz/Server/Data/ReleaseGroup.pm
  lib/MusicBrainz/Server/Data/Work.pm
  lib/MusicBrainz/Server/Form/Filter/Event.pm
  lib/MusicBrainz/Server/Form/Filter/Generic.pm
  lib/MusicBrainz/Server/Form/Filter/Recording.pm
  lib/MusicBrainz/Server/Form/Filter/Release.pm
  lib/MusicBrainz/Server/Form/Filter/ReleaseGroup.pm
  lib/MusicBrainz/Server/Form/Filter/Work.pm
  root/artist/ArtistEvents.js
  root/artist/ArtistIndex.js
  root/artist/ArtistRecordings.js
  root/artist/ArtistReleases.js
  root/artist/ArtistWorks.js
  root/static/scripts/common/components/FilterForm.js
  t/lib/t/MusicBrainz/Server/Controller/Artist/Filtering.pm
  t/sql/filtering.sql
Labels: New feature

#3135 MBS-13420: Support Bandcamp /discover tag links
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: URL handling

#3134 MBS-13414: Normalize x.com URLs to twitter.com
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL, URL handling
