Repository metabrainz/musicbrainz-server, pull requests merged in 2023-01, with the labels that each got.

#2783 MBS-12784: Mark more tracklist errors as such
  root/release/edit/tracklist.tt
Labels: Bug

#2796 MBS-12737: Properly check backwardness with isRelationshipBackward
  root/static/scripts/relationship-editor/components/RelationshipItem.js
  root/static/scripts/relationship-editor/utility/prepareHtmlFormSubmission.js
Labels: Regression/Beta

#2797 MBS-12787: Editing a relationship to add instruments causes duplication
  root/static/scripts/relationship-editor/utility/splitRelationshipByAttributes.js
  root/static/scripts/tests/relationship-editor.js
Labels: Bug, Regression/Beta

#2795 MBS-12817: Fix selector for relationship dialog warnings
  root/static/styles/relationship-editor.less
Labels: Regression/Beta

#2792 MBS-12809: Pass minimal existing data for Historic/RemoveDiscID
  lib/MusicBrainz/Server/Edit/Historic/RemoveDiscID.pm
  root/static/scripts/common/components/CDTocLink.js
  root/types/edit_types_historic.js
Labels: Regression/Beta

#2799 MBS-12820: Add default label for attribute multiselects
  root/static/scripts/relationship-editor/components/DialogAttribute/MultiselectAttribute.js
Labels: Bug

#2798 MBS-12709: Do not copy series part number with "Add another [entity]"
  root/static/scripts/relationship-editor/components/RelationshipPhraseGroup.js
Labels: QoL

#2800 MBS-12693: Select relationship type before target
  root/static/scripts/relationship-editor/components/RelationshipDialogContent.js
Labels: QoL

#2450 Improve test documentation (IX): Shared tests (Annotation/Details)
  admin/sql/InsertTestData.sql
  t/lib/t/MusicBrainz/Server/Controller/Artist/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Details.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/Details.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/Details.pm
  t/lib/t/MusicBrainz/Server/Controller/Release/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Controller/Release/Details.pm
  t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Details.pm
  t/lib/t/MusicBrainz/Server/Controller/Series/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Controller/Series/Details.pm
  t/lib/t/MusicBrainz/Server/Controller/Work/AddAnnotation.pm
  t/lib/t/MusicBrainz/Server/Controller/Work/Details.pm
  t/sql/series.sql
Labels: Documentation, Tests

#2451 Improve test documentation (X): Shared tests (Create)
  t/lib/t/MusicBrainz/Server/Controller/Area/Create.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Create.pm
  t/lib/t/MusicBrainz/Server/Controller/Instrument/Create.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/Create.pm
  t/lib/t/MusicBrainz/Server/Controller/Place/Aliases.pm
  t/lib/t/MusicBrainz/Server/Controller/Place/Create.pm
  t/lib/t/MusicBrainz/Server/Controller/Place/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Series/Create.pm
  t/lib/t/MusicBrainz/Server/Controller/Series/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/Work/Create.pm
  t/sql/place.sql
Labels: Documentation, Tests

#2456 Improve test documentation (XI): Shared tests (Edit)
  t/lib/t/MusicBrainz/Server/Controller/Area/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Artist/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Instrument/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Label/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Place/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Recording/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/ReleaseGroup/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Series/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/URL/Edit.pm
  t/lib/t/MusicBrainz/Server/Controller/Work/Edit.pm
  t/sql/mbs-8636.sql
Labels: Documentation, Tests

#2748 MBS-12721: Normalize 45cat.com/45worlds.com links to HTTPS
  lib/MusicBrainz/Server/Entity/URL/45cat.pm
  lib/MusicBrainz/Server/Entity/URL/45worlds.pm
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL

#2806 Update the ways to access $c from JavaScript
  HACKING.md
Labels: Documentation

#2805 MBS-12831: Don't hide disambiguations in relationship previews
  root/static/scripts/relationship-editor/components/DialogPreview.js
Labels: QoL, Regression/Beta

#2807 MBS-12837: Add autoselect + sidebar for Tsutaya URLs
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/Tsutaya.pm
  root/static/images/external-favicons/tsutaya-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: New feature

#2816 MBS-12857 / MBS-12858: Details for recent entities in autocompletes
  entities.json
  entities.mjs
  lib/MusicBrainz/Server/Controller/WS/js.pm
Labels: Regression/Beta
