Repository metabrainz/musicbrainz-server, pull requests merged in 2024-07, with the labels that each got.

#3317 MBS-13667: Return rating as number in JSON rating API
  lib/MusicBrainz/Server/Controller/Rating.pm
Labels: Bug

#3316 MBS-13679: RYM cleanup improvements
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL, URL handling

#3312 MBS-13675: Split statistic events into history translation component
  .eslintrc.unfixed.yaml
  .eslintrc.yaml
  lib/MusicBrainz/Server.pm
  lib/MusicBrainz/Server/Data/Statistics.pm
  lib/MusicBrainz/Server/Entity/EditNote.pm
  lib/MusicBrainz/Server/Translation/History.pm
  po/Makefile
  po/extract_pot_db
  po/history.bg.po
  po/history.bn.po
  po/history.ca.po
  po/history.cs.po
  po/history.cy.po
  po/history.da.po
  po/history.de.po
  po/history.el.po
  po/history.eo.po
  po/history.es.po
  po/history.es_419.po
  po/history.et.po
  po/history.fa.po
  po/history.fi.po
  po/history.fr.po
  po/history.gl.po
  po/history.he.po
  po/history.hr.po
  po/history.hu.po
  po/history.id.po
  po/history.it.po
  po/history.ja.po
  po/history.ko.po
  po/history.lt.po
  po/history.mr.po
  po/history.nb.po
  po/history.nl.po
  po/history.oc.po
  po/history.pa.po
  po/history.pl.po
  po/history.pot
  po/history.pt.po
  po/history.ro.po
  po/history.ru.po
  po/history.sk.po
  po/history.sl.po
  po/history.sq.po
  po/history.sr.po
  po/history.sv.po
  po/history.th.po
  po/history.tr.po
  po/history.vi.po
  po/history.zh.po
  po/history.zh_Hant.po
  root/static/scripts/common/i18n/history.js
  root/static/scripts/common/i18n/wrapGettext.js
  root/static/scripts/jed-data.mjs
  root/vars.js
  script/.check_eslint_rule_config.yaml
  webpack/constants.mjs
Labels: Refactoring

#3321 MBS-13683: Always show event dates on JSON API
  lib/MusicBrainz/Server/WebService/Serializer/JSON/2/Utils.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/JSON/LookupArtist.pm
  t/lib/t/MusicBrainz/Server/Controller/WS/2/LookupArtist.pm
  t/sql/webservice.sql
Labels: Bug, API

#3333 MBS-13692: Beta: release editor edits the same release label twice
  root/static/scripts/release-editor/edits.js
  t/selenium.mjs
  t/selenium/release-editor/MBS-13692.json5
Labels: Regression/Beta

#3327 MBS-13682: Add language filter to Works tab
  lib/MusicBrainz/Server/Data/Language.pm
  lib/MusicBrainz/Server/Data/Work.pm
  lib/MusicBrainz/Server/FilterUtils.pm
  lib/MusicBrainz/Server/Form/Filter/Work.pm
  root/static/scripts/common/components/FilterForm.js
  t/lib/t/MusicBrainz/Server/Controller/Artist/Filtering.pm
  t/sql/filtering.sql
Labels: New feature

#3315 MBS-13528 / MBS-13696: Calculate invalid edit notes in more places and with more invisible characters
  lib/MusicBrainz/Server/Controller/WS/js/Edit.pm
  lib/MusicBrainz/Server/Data/Utils.pm
  lib/MusicBrainz/Server/Validation.pm
  root/static/scripts/release-editor/init.js
  t/lib/t/MusicBrainz/Server/Controller/WS/js/Edit.pm
  t/lib/t/MusicBrainz/Server/Validation.pm
Labels: QoL, Bug

#3314 MBS-13677: Show cover art presence in indexed searches
  lib/MusicBrainz/Server/Data/Search.pm
Labels: Bug

#3325 Upgrade Flow to 0.237.0
  flow-typed/npm/knockout_v3.1.0.js
  package.json
  root/static/scripts/common/hooks/useEventTrap.js
  yarn.lock
Labels: Refactoring

#2672 MBS-11063: Convert event edit form to React
  eslint.config.mjs
  flow-typed/npm/@floating-ui/react_v0.26.x.js
  lib/MusicBrainz/Server.pm
  lib/MusicBrainz/Server/Controller/Event.pm
  lib/MusicBrainz/Server/Controller/Role/Create.pm
  lib/MusicBrainz/Server/Controller/Role/Edit.pm
  root/components/forms.tt
  root/event/CreateEvent.js
  root/event/EditEvent.js
  root/event/create.tt
  root/event/edit_form.tt
  root/event/types.js
  root/server/components.mjs
  root/static/scripts/common/components/Bubble.js
  root/static/scripts/edit/components/DateRangeFieldset.js
  root/static/scripts/edit/components/FormRow.js
  root/static/scripts/edit/components/FormRowSelect.js
  root/static/scripts/edit/components/FormRowText.js
  root/static/scripts/event/components/EventEditForm.js
  root/static/scripts/relationship-editor.js
  root/static/styles/forms.less
  webpack/client.config.mjs
Labels: React

#3180 MBS-13492: Move beginner status to a privilege flag
  admin/sql/updates/20240221-mbs-13492.sql
  lib/MusicBrainz/Server/Constants.pm
  lib/MusicBrainz/Server/Controller/Account.pm
  lib/MusicBrainz/Server/Controller/User.pm
  lib/MusicBrainz/Server/Data/Edit.pm
  lib/MusicBrainz/Server/Data/Editor.pm
  lib/MusicBrainz/Server/EditQueue.pm
  lib/MusicBrainz/Server/EditSearch/Predicate/Role/User.pm
  lib/MusicBrainz/Server/Entity/Collection.pm
  lib/MusicBrainz/Server/Entity/Editor.pm
  lib/MusicBrainz/Server/Report/LimitedEditors.pm
  root/collection/CollectionIndex.js
  root/components/UserAccountLayout.js
  root/constants.js
  root/edit/NotesReceived.js
  root/edit/components/EditorTypeInfo.js
  root/layout.tt
  root/layout/index.js
  root/static/scripts/collection/components/CollectionEditForm.js
  root/static/scripts/common/utility/privileges.js
  root/static/scripts/tests/utility/constants.js
  root/static/scripts/tests/utility/sanitizedEditor.js
  root/types/collection.js
  root/types/editor.js
  root/user/UserProfile.js
  root/utility/edit.js
  root/utility/hydrate.js
  root/utility/sanitizedEditor.mjs
  t/lib/t/MusicBrainz/Server/Controller/Collection/Show.pm
  t/lib/t/MusicBrainz/Server/Controller/User/Edit.pm
  t/lib/t/MusicBrainz/Server/Data/Edit.pm
  t/lib/t/MusicBrainz/Server/Data/Editor.pm
  t/lib/t/MusicBrainz/Server/EditQueue.pm
  t/lib/t/MusicBrainz/Server/Entity/Editor.pm
  t/sql/collection.sql
  t/sql/edit_note.sql
  t/sql/editor.sql
  t/sql/vote.sql
  t/sql/vote_and_note_selenium.sql
Labels: Refactoring

#3340 MBS-9373: Split voting and editing privilege revoking
  admin/sql/updates/20240726-mbs-9373.sql
  lib/MusicBrainz/Server/Constants.pm
  lib/MusicBrainz/Server/Controller/Admin.pm
  lib/MusicBrainz/Server/Controller/Edit.pm
  lib/MusicBrainz/Server/Data/Editor.pm
  lib/MusicBrainz/Server/Edit.pm
  lib/MusicBrainz/Server/Entity/Editor.pm
  lib/MusicBrainz/Server/Form/Admin/EditUser.pm
  lib/MusicBrainz/Server/Form/Admin/PrivilegeSearch.pm
  root/admin/EditUser.js
  root/admin/PrivilegeSearch.js
  root/admin/components/UserList.js
  root/constants.js
  root/layout.tt
  root/layout/index.js
  root/static/scripts/common/utility/privileges.js
  root/user/UserProfile.js
  root/utility/edit.js
  t/lib/t/MusicBrainz/Server/Data/Editor.pm
Labels: New feature

#3343 Update eslint-plugin-react to 7.35.0
  eslint.config.mjs
  package.json
  yarn.lock
Labels: Refactoring

#3336 Update Flow to 0.241.0
  package.json
  root/admin/attributes/Attribute.js
  root/admin/attributes/Index.js
  root/admin/attributes/Language.js
  root/admin/attributes/Script.js
  root/components/GroupedTrackRelationships.js
  root/components/ReleaseCatnoList.js
  root/components/ReleaseLabelList.js
  root/edit/components/ListHeader.js
  root/search/components/DocResults.js
  root/static/scripts/artist/components/ArtistCreditRenamer.js
  root/static/scripts/common/components/Autocomplete2.js
  root/static/scripts/common/components/Autocomplete2/formatters.js
  root/static/scripts/common/components/Autocomplete2/searchItems.js
  root/static/scripts/common/components/CritiqueBrainzReview.js
  root/static/scripts/common/components/EntityLink.js
  root/static/scripts/common/components/RelatedSeries.js
  root/static/scripts/common/components/RelatedWorks.js
  root/static/scripts/common/components/TagLink.js
  root/static/scripts/common/i18n/commaList.js
  root/static/scripts/common/i18n/commaOnlyList.js
  root/static/scripts/common/i18n/expand2.js
  root/static/scripts/common/i18n/expand2react.js
  root/static/scripts/common/utility/displayLinkAttribute.js
  root/static/scripts/common/utility/formatSetlist.js
  root/static/scripts/common/utility/groupRelationships.js
  root/static/scripts/common/utility/nonEmpty.js
  root/static/scripts/common/utility/numbers.js
  root/static/scripts/edit/components/edit/DiffSide.js
  root/static/scripts/edit/components/edit/ReleaseEventsDiff.js
  root/static/scripts/edit/utility/diffArtistCredits.js
  root/static/scripts/edit/utility/linkPhrase.js
  root/static/scripts/release-editor/duplicates.js
  root/static/scripts/tests/i18n/expand2.js
  root/static/scripts/tests/utility/bracketed.js
  root/statistics/Relationships.js
  root/types/i18n.js
  root/user/UserProfile.js
  root/utility/hydrate.js
  yarn.lock
Labels: Refactoring

#3344 Update Flow to 0.242.1
  package.json
  yarn.lock
Labels: Refactoring

#3342 MBS-13707: Calculate needed columns first in getRelationshipRows
  root/components/RelationshipsTable.js
Labels: Regression/Beta

#2808 MBS-10609: Actually check for edit notes by beginners
  lib/MusicBrainz/Server/Data/Editor.pm
  lib/MusicBrainz/Server/EditSearch/Predicate/Role/User.pm
Labels: Bug, Edit search

#2813 MBS-12847: Allow searching for edits without any notes
  lib/MusicBrainz/Server/EditSearch/Predicate/Role/User.pm
  root/edit/search_macros.tt
  root/vote/VotingIndex.js
Labels: New feature, Edit search

#2812 MBS-10610: Search for edits made by non-beginners
  lib/MusicBrainz/Server/EditSearch/Predicate/Role/User.pm
  root/edit/search_macros.tt
Labels: New feature, Edit search

#3346 MBS-13714: Clean up Genius artists links
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: QoL, URL handling
