Repository metabrainz/musicbrainz-server, pull requests merged in 2024-03, with the labels that each got.

#3188 MBS-13328: Remove medium / release edits missing from recording edit history
  lib/MusicBrainz/Server/Edit/Medium/Delete.pm
  lib/MusicBrainz/Server/Edit/Release/Delete.pm
Labels: Bug

#3181 MBS-13495: Use RG table for RG disambiguation filter
  lib/MusicBrainz/Server/Data/ReleaseGroup.pm
Labels: Bug

#3185 MBS-12441: Handle Yandex Music links
  lib/MusicBrainz/Server/Data/URL.pm
  lib/MusicBrainz/Server/Entity/URL/Yandex.pm
  root/static/images/external-favicons/yandex-32.png
  root/static/scripts/common/constants.js
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
  root/static/styles/favicons.less
Labels: QoL, URL handling

#3182 Add context to more Unknown strings
  root/report/DuplicateArtists.js
  root/report/DuplicateReleaseGroups.js
  root/report/components/ArtistList.js
  root/report/components/ReleaseGroupList.js
  root/report/components/WorkList.js
  root/static/scripts/common/components/Cardinality.js
Labels: Frontend-only

#3175 MBS-13476: Show release label disambiguations on hover
  root/layout/components/sidebar/ReleaseSidebar.js
  root/static/scripts/common/components/EntityLink.js
Labels: QoL

#3198 MBS-13507: Load areas for events in collections
  lib/MusicBrainz/Server/Controller/Collection.pm
Labels: Bug

#3199 MBS-13486 (II): Explain the report change on the report text
  root/report/ReleasesWithoutCaa.js
Labels: Frontend-only

#3184 Minor string improvements based on translation finds
  lib/MusicBrainz/Server/Form/Field/Coordinates.pm
  root/cdtoc/attach_list.tt
  root/layout/components/BottomMenu.js
  root/relationship/linktype/RelationshipTypePairTree.js
  root/release/edit/tracklist.tt
  root/report/SetInDifferentRg.js
Labels: Frontend-only

#3201 Fix more string dupes
  lib/MusicBrainz/Server/Controller/CDTOC.pm
Labels: Refactoring

#3202 MBS-13509 / MBS-13510: Logo updates
  root/static/images/external-favicons/beatport-32.png
  root/static/images/external-favicons/napster-32.png
Labels: Frontend-only

#3196 MBS-13505: Split relationships on task attributes
  root/static/scripts/common/constants.js
  root/static/scripts/relationship-editor/utility/splitRelationshipByAttributes.js
  root/static/scripts/tests/relationship-editor.js
  t/sql/initial.sql
Labels: New feature

#3203 MBS-13512: Show user restrictions in admin user views
  root/admin/components/UserList.js
Labels: QoL

#3212 Update Flow to version 0.230.0
  package.json
  root/admin/attributes/Language.js
  root/admin/attributes/Script.js
  root/components/list/ReleaseGroupList.js
  root/static/scripts/relationship-editor/components/DialogAttribute/MultiselectAttribute.js
  root/static/scripts/statistics.js
  root/static/scripts/tests/edit/utility/linkPhrase.js
  root/types/languageandscript.js
  yarn.lock
Labels: Refactoring

#3216 Make duplicated artist begin/end labels consistent
  root/static/scripts/edit/MB/Control/ArtistEdit.js
Labels: Frontend-only

#3206 MBS-13515: Support Bandsintown festival links
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: URL handling

#3217 Drop duplicate "Begin/End area:" colon strings
  root/artist/utils.js
  root/static/scripts/edit/MB/Control/ArtistEdit.js
Labels: Frontend-only

#3205 Don't translate admin-only merge pages
  root/area/AreaMerge.js
  root/instrument/InstrumentMerge.js
Labels: Frontend-only

#3221 Do not translate DeleteArea/Instrument
  root/area/DeleteArea.js
  root/instrument/DeleteInstrument.js
Labels: Frontend-only

#3220 Update Flow to 0.231.0
  package.json
  root/account/ChangePassword.js
  root/cdtoc/CDTocInfo.js
  root/collection/CollectionHeader.js
  root/components/Aliases/ArtistCreditList.js
  root/components/Artwork.js
  root/components/EntityHeader.js
  root/components/PaginatedResults.js
  root/components/ReleaseLanguageScript.js
  root/components/TagEntitiesList.js
  root/components/list/EventList.js
  root/components/list/ReleaseGroupList.js
  root/components/list/WorkList.js
  root/edit/components/EditList.js
  root/edit/components/EditSummary.js
  root/edit/components/EditorTypeInfo.js
  root/edit/components/ListHeader.js
  root/edit/components/TrackDurationChanges.js
  root/edit/details/AddRelationshipType.js
  root/edit/details/EditRelationshipType.js
  root/edit/details/EditUrl.js
  root/edit/details/MergeReleases.js
  root/edit/details/RemoveMedium.js
  root/edit/details/historic/EditRelationship.js
  root/layout/components/FaviconLinks.js
  root/layout/components/sidebar/AnnotationLinks.js
  root/layout/components/sidebar/EditLinks.js
  root/layout/components/sidebar/SidebarProperties.js
  root/layout/components/sidebar/SidebarRating.js
  root/layout/components/sidebar/SidebarTags.js
  root/layout/components/sidebar/SubscriptionLinks.js
  root/main/error/components/ErrorEnvironment.js
  root/release/CoverArt.js
  root/release/CoverArtFields.js
  root/search/components/SearchForm.js
  root/static/scripts/alias/AliasEditForm.js
  root/static/scripts/common/components/AcoustIdCell.js
  root/static/scripts/common/components/Relationships.js
  root/static/scripts/common/components/ReleaseEvent.js
  root/static/scripts/common/components/WorkListEntry.js
  root/static/scripts/edit/components/DateRangeFieldset.js
  root/static/scripts/edit/components/EntityPendingEditsWarning.js
  root/static/scripts/edit/components/InlineSubmitButton.js
  root/static/scripts/edit/components/RelationshipPendingEditsWarning.js
  root/static/scripts/edit/components/edit/RelationshipDiff.js
  root/static/scripts/edit/externalLinks.js
  root/tag/EntityList.js
  yarn.lock
Labels: Refactoring

#3224 Upgrade Flow to 0.232.0
  flow-typed/npm/redux_v4.x.x.js
  package.json
  root/admin/DeleteUser.js
  root/components/Artwork.js
  root/layout/components/sidebar/SidebarIpis.js
  root/layout/components/sidebar/SidebarIsnis.js
  root/report/LowDataQualityReleases.js
  root/user/ContactUser.js
  yarn.lock
Labels: Refactoring

#3223 Fix instrument attribute doc wording
  root/relationship/linkattributetype/RelationshipAttributeTypeIndex.js
Labels: Frontend-only

#3113 MBS-12715, MBS-13526: ArtistCreditEditor refactor
  root/static/images/attribution.txt
  root/static/images/icons/arrow_undo.png
  root/static/scripts/common/components/Autocomplete2.js
  root/static/scripts/common/components/ButtonPopover.js
  root/static/scripts/common/components/DescriptiveLink.js
  root/static/scripts/common/components/EntityLink.js
  root/static/scripts/common/utility/entityHref.js
  root/static/scripts/edit/components/ArtistCreditBubble.js
  root/static/scripts/edit/components/ArtistCreditEditor.js
  root/static/scripts/edit/components/ArtistCreditEditor/types.js
  root/static/scripts/edit/components/ArtistCreditEditor/utilities.js
  root/static/scripts/edit/components/ArtistCreditNameEditor.js
  root/static/scripts/edit/components/forms.js
  root/static/scripts/edit/utility/guessFeat.js
  root/static/scripts/release-editor/actions.js
  root/static/scripts/release-editor/bindingHandlers.js
  root/static/scripts/release-editor/fields.js
  root/static/scripts/release-editor/init.js
  root/static/scripts/release-editor/trackParser.js
  root/static/scripts/release-editor/types.js
  root/static/styles/forms.less
  root/static/styles/release-editor.less
  root/static/styles/widgets.less
  root/types/artistcredit.js
  t/selenium/Artist_Credit_Editor.json5
  t/selenium/Autocomplete2.json5
  t/selenium/MBS-11529.json5
  t/selenium/MBS-12904.json5
  t/selenium/MBS-8952.json5
  t/selenium/release-editor/Duplicate_Selection.json5
  t/selenium/release-editor/MBS-10221.json5
  t/selenium/release-editor/MBS-10359.json5
  t/selenium/release-editor/MBS-11156.json5
  t/selenium/release-editor/MBS-13273.json5
  t/selenium/release-editor/Seeding.json5
  t/selenium/release-editor/The_Downward_Spiral.json5
Labels: React, Refactoring

#3222 MBS-13524: Update Operabase handling for new artist URLs
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: URL handling

#3219 MBS-13522 / MBS-13523: ReleasesSameBarcode report improvements
  lib/MusicBrainz/Server/Report/ReleasesSameBarcode.pm
Labels: Bug, Reports
