Repository metabrainz/musicbrainz-server, pull requests merged in 2025-04, with the labels that each got.

#3512 MBS-13978: Fix cover art display in the release sidebar
  root/layout/components/sidebar/ReleaseSidebar.js
Labels: Regression/Beta

#1659 MBS-8668: Block adding duplicates to a series
  lib/MusicBrainz/Server/Constants.pm
  lib/MusicBrainz/Server/Data/Relationship.pm
  root/static/scripts/relationship-editor/utility/compareRelationships.js
  root/static/scripts/relationship-editor/utility/getRelationshipStatusName.js
  root/static/scripts/tests/relationship-editor/utility/compareRelationships.js
  t/lib/t/MusicBrainz/Server/Data/Link.pm
  t/lib/t/MusicBrainz/Server/Data/Relationship.pm
  t/sql/relationships.sql
Labels: Bug

#2804 MBS-2349: Allow merging RGs when merging releases
  lib/MusicBrainz/Server/Controller/Release.pm
  lib/MusicBrainz/Server/Controller/Role/Merge.pm
  lib/MusicBrainz/Server/Form/Merge/Release.pm
  root/release/ReleaseMerge.js
  root/types/forms.js
  t/lib/t/MusicBrainz/Server/Controller/Release/Merge.pm
Labels: New feature

#3491 MBS-13957: Add a report for duplicate items in series
  lib/MusicBrainz/Server/Data/Relationship.pm
  lib/MusicBrainz/Server/Report/SeriesContainingDuplicates.pm
  lib/MusicBrainz/Server/ReportFactory.pm
  root/report/ReportsIndex.js
  root/report/SeriesContainingDuplicates.js
  root/report/types.js
  root/server/components.mjs
  root/utility/tableColumns.js
Labels: Reports

#1717 MBS-11129: Display mediums as Medium # (Format)
  root/cdtoc/AttachCDTocConfirmation.js
  root/components/common-macros.tt
  root/static/scripts/common/components/MediumDescription.js
  root/static/scripts/common/entity.js
  root/static/scripts/common/hooks/usePagedMediumTable.js
  root/static/styles/layout.less
Labels: QoL

#3521 MBS-13985: Show inline primary alias for work authors
  lib/MusicBrainz/Server/Data/Work.pm
Labels: QoL

#3517 MBS-13982: Wrap overlong release and release group titles in tables
  root/release_group/ReleaseGroupIndex.js
  root/utility/tableColumns.js
Labels: QoL, Frontend-only

#3518 MBS-13977: Ignore country codes in yesasia.com links
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: URL handling

#3387 MBS-9253: Use type child_order rather than id to sort RGs
  admin/sql/CreateFunctions.sql
  admin/sql/CreateIndexes.sql
  admin/sql/CreateMirrorOnlyTriggers.sql
  admin/sql/CreateTables.sql
  admin/sql/CreateTriggers.sql
  admin/sql/DropFunctions.sql
  admin/sql/DropMirrorOnlyTriggers.sql
  admin/sql/DropTriggers.sql
  admin/sql/updates/20241017-mbs-9253-master_and_standalone.sql
  admin/sql/updates/20241017-mbs-9253-mirror_only.sql
  admin/sql/updates/20241017-mbs-9253.sql
  admin/sql/updates/schema-change/30.all.sql
  admin/sql/updates/schema-change/30.master_and_standalone.sql
  admin/sql/updates/schema-change/30.mirror_only.sql
  lib/MusicBrainz/Server/Data/ReleaseGroup.pm
  upgrade.json
  upgrade.sh
Labels: QoL

#3523 MBS-13989: Drop /c/ Patreon URL segment
  root/static/scripts/edit/URLCleanup.js
  root/static/scripts/tests/Control/URLCleanup.js
Labels: URL handling

#3530 MBS-13997: Check both start and end date in DuplicateEvents
  lib/MusicBrainz/Server/Report/DuplicateEvents.pm
Labels: Reports

#3420 MBS-13838: Convert class forms to component syntax
  lib/MusicBrainz/Server/Controller/Account.pm
  lib/MusicBrainz/Server/Data/Editor.pm
  lib/MusicBrainz/Server/Form/Field/Area.pm
  lib/MusicBrainz/Server/Form/Role/UserProfile.pm
  root/account/EditProfile.js
  root/account/Preferences.js
  root/static/scripts/account/components/ApplicationForm.js
  root/static/scripts/account/components/EditProfileForm.js
  root/static/scripts/account/components/PreferencesForm.js
  root/static/scripts/common/components/Autocomplete2.js
  root/static/scripts/common/components/Autocomplete2/constants.js
  root/static/scripts/common/components/Autocomplete2/types.js
  root/static/scripts/common/entity2.js
  root/static/styles/widgets.less
  root/types/formcomponents.js
Labels: Refactoring
